### ISSUE TITLE
Missing Jewels numbers 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#223] opened 2021-04-26 12:41 UTC
> Cannot see the number "4" in a pair, as per the rules of the game "Jewel B"; therefore, cannot complete the game.
![image](https://user-images.githubusercontent.com/82968538/116083829-1640f780-a66b-11eb-80f3-4d5309476ba8.png)

**Comment by avaidyam** [comment] 2021-05-21 17:18
Duplicate of #96.

**Closed by avaidyam** 2021-05-21 17:18 UTC
