### ISSUE TITLE
Activity Timezones

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#417] opened 2021-10-29 13:48 UTC
When activities are scheduled, they default to EST. currently on the dashboard there is no way to specify timezone, or to see what timezone it is in. We want to select the timezone OR if we do not select it, make it the user’s current timezone. 

From a UI perspective, this could be set up so that when there is a schedule for an activity and you see the boxes for a start date, time, interval, and custom times, there can be a fifth box called "Time Zone" that takes the time as a +/- number from GMT. This would be implemented so that only +/- numbers can be inputted. Ex. the box could have -5 GMT to specify the EST time zone. This would also require a resizing of the other boxes. See screenshot for where it could be placed below.

![image](https://user-images.githubusercontent.com/86117379/140804459-86fa29af-b7bc-4770-a448-4796e2d2eccb.png)

**Comment by avaidyam** [comment] 2021-11-16 15:12
To simplify the implementation of this feature (technically a bug), let's change the behavior to use the user's current timezone. 
1. When viewing the Feed in the Dashboard/App, the current timezone can be requested from the browser. 
1. For scheduling push notifications, the server should determine the current timezone based on the latest GPS point automatically. 
    - This change should be entirely implemented within `LAMP-worker`, and should require no new user interface changes.

**Comment by Linoy339** [comment] 2021-11-24 06:59
@avaidyam. Just to clarify:
> 1. When viewing the Feed in the Dashboard/App, the current timezone can be requested from the browser.
Is the timezone which we enter here to be **saved as new sensor_event** like :

```
{
_parent:U123456789,
sensor:"lamp.timezone"
data:{
timezone:"GMT +5"
}
}
```
**or  as tag which would be :**
```
{
_parent:U123456789,
type:"me",
key:"lamp.timezone",
value:timezone:"GMT +5"

}
```
> 2. For scheduling push notifications, the server should determine the current timezone based on the latest GPS point automatically.

Suppose, We have gps data for a particular participant, say :
```
             {
                "latitude": 9.825516752275586,
                "longitude": 76.3456266651752,
                "accuracy": 4.780498660057227,
                "altitude": 7.80199283733964
            }
```
With the latitude and longitude above, we need to find the timezone. Right?
If yes,  we might have to use in particular api (eg:google map api) or npm package(eg:node-geo-tz) to find out the timezone, which seems to be an overhead.

It seems better to send  timezone together with co-ordinates from the app side, so that we can fetch it from sensor_event as `lamp.gps`. 
Please confirm.

**Comment by avaidyam** [comment] 2021-11-29 15:47
You present a good point with the difficulty of reverse geocoding the GPS data to a time zone. I agree that it makes more sense to cache the time zone as a Tag upon loading the dashboard, and then using that instead. This tag should only be updated if the time zone has changed or if no time zone tag was previously created. If this tag doesn't exist when the LAMP-worker is attempting to send push notifications, it should default to UTC.

**Comment by Linoy339** [comment] 2021-11-30 10:04
Thanks for the clarification @avaidyam .
How often the tag should be updated, as there is a chance of change in time zone if the user travels ?
Is it to be updated only while login or do a periodic time zone update has to take place ?
Can you suggest?

**Comment by avaidyam** [comment] 2021-11-30 10:05
For now, only upon login.

**Comment by Linoy339** [comment] 2021-11-30 10:32
Okay. Thanks

**Comment by Linoy339** [comment] 2021-12-02 09:53
@avaidyam : Just to clarify:
The requirement is to have notifications for the same time in any time zone. Right?
We can explain with a scenario here:

Suppose there are 2 participants for a particular study. One of them is in India and other is in Toronto(Canada).
If a researcher from India have set notification at 3.00 PM, the one  of the participants get it at 3.00PM and other will be getting it at  4.20AM(Toronto time). This is what is happening now.

The change which is to be implemented is that both users should get notification on 3.00pm irrespective of the time zone, which means one user will get  it at 3 pm (Indian Time)and other will also get it at 3 pm(Toronto Time).

Can you clarify o confirm it?

**Comment by avaidyam** [comment] 2021-12-02 12:17
Yes, that's correct.

**Comment by Linoy339** [comment] 2021-12-02 17:07
Thanks @avaidyam .
In this case, we also need to save time zone for the particular activity as :
```
{
_parent:{activity_id},
type:"me",
key:"lamp.activity.timezone",
value:"GMT +5"
}
```
This is required to find the local time zone where the activity got saved and from this, we can find the local time of that particular time zone. Thus, we can convert this time to utc time of particular time zone where the user belongs to.

**If we take the above scenario**( 3.00 PM notification for Indian and Canada users ), activity time zone will be Indian and utc time saved would be  9.30 AM. Also the `lamp.activity.timezone"` would be GMT+5.30. From this we can find the local time as 3.00 PM.
The user from canada will be having a time zone offset in the form of tag `lamp.participant.timezone ` as GMT+5.00. Thus, we can find out the utc time for the user as 20.00pm (3.00 PM +5.00= 8.00 PM).
Thus both users gets notification at 3.00 pm irrespective of the time zone

**Comment by Linoy339** [comment] 2021-12-06 10:40
@avaidyam . This is clarified. 
But, we need some more clarity on activity time zone:
As the researchers can have varied time zones, it is required to save schedule based time zones. So, can we have time zone to be saved in schedule object in activity model instead of tag `lamp.activity.timezone`. This makes easier to find out the local time 
and schedule based on participant's time zone.

Please let us know on this

**Comment by avaidyam** [comment] 2021-12-06 17:12
Timezone should only be saved on the participant side, once. The schedule is timezone-agnostic and will be translated to the patient timezone at runtime by the LAMP-worker before scheduling and sending push notifications.

**Comment by sarithapillai8** [comment] 2021-12-07 04:39
@avaidyam 
Sorry, This is confusing. When a schedule is added with a time 3pm. The notifications and feed row should show with the time 3pm in every timezone, right? 
The issue with this is we are saving UTC of this time. Instead if we are just saving the time string we could just use that string in all the timezones without any conversions. As we are saving UTC we  need to find which was the user's timezone while scheduling so that we can find the time he actually used. Otherwise with the UTC how can we find which time they actually scheduled if the participant is in another timezone?

**Comment by sarithapillai8** [comment] 2021-12-10 04:59
@avaidyam Please reply to the above comment so that we can start on this.

**Comment by avaidyam** [comment] 2021-12-10 14:21
@sarithapillai8 Yes, it should show 3pm in every timezone. Researchers are not plugging in a time relative to their timezone, they are ALWAYS dealing with the patient's timezone.

**Comment by sarithapillai8** [comment] 2021-12-13 05:40
@avaidyam 
Can we just save the time string instead of UTC datetime string ? If this is acceptable, let us know how to handle the existing schedules? Currently UTC converted datetime is saved for schedule times (which is calculated by converting the local timezone of the researcher).

**Comment by avaidyam** [comment] 2021-12-13 13:56
You cannot change the current format of the Activity Schedule. Please use the existing data structures and reinterpret them in the dashboard code or server code as required.

**Comment by sarithapillai8** [comment] 2021-12-13 14:04
@avaidyam 
So there should be some way to understand the actual time selected by the researcher. With the current data, the activity schedule time was saving by converting the time selected by the researcher(which is considered as his local time) to UTC time. So we can just use those UTC values without any conversion as we don't have any information of which time the researcher actually selected while creating the schedule. And for future, remove this UTC conversion and just save the time selected. And use this exact time everywhere without any conversions.

**Comment by avaidyam** [comment] 2021-12-13 14:38
Right. While the date-time string has a date, a time, and a timezone, currently we ignore the date. We should also ignore the timezone. There is no other change to the data model this way, and if we support custom time zones in the future then it's possible to use that field again.

**Comment by sarithapillai8** [comment] 2021-12-13 15:19
@avaidyam 
Please correct me if I am wrong : 
The researcher selected the time - Mon Dec 13 2021 14:00:45 GMT+0530 (India Standard Time), which was saved as 2021-12-13T08:30:45.820Z. Then we need to ignore the timezone and date, and consider the time '08:30' in every time-zone. I mean in feed and notifications. ie, we just use the time 08.30 without any conversion.

In future save the time in local datetime format 
new Date(data.time).toLocaleString()
and use this time value without any conversion for notification and feed.

If this is the plan we don't need to bother about custom time-zone changes for now.

**Comment by avaidyam** [comment] 2021-12-13 15:37
Yes that's correct. No changes to how the Researcher sets the schedule. Now the "8:30" they set refers to the patient's local timezone.

**Comment by Linoy339** [comment] 2021-12-13 17:08
@avaidyam . Just to clarify:

1) In this case, there will be mismatch between time for which the notification got set and the same for which 
notification got triggered.
In the above example, from the researcher's perspective, the notifications were supposed to fire at `2 PM` and Instead, it gets fired at `08:30 AM`.

2) Also the key `time` in schedule object would be either `2021-12-13T08:30:45.820Z`(old schedules) or `13/12/2021, 22:25:16 pm` (new schedules). In both cases, we need to fetch the time from the string. In the above case, we need to fetch time as `08:30 Am` from `2021-12-13T08:30:45.820Z` and `22:25:00` from `13/12/2021, 22:25:16 pm`

**Comment by avaidyam** [comment] 2021-12-13 17:13
@Linoy339 @sarithapillai8 The UI should show "8 AM" as if it were UTC, regardless of the Researcher's timezone.

**I don't think we were made aware that there is a change to the data format for schedules? When did this occur and why? Please revert to the old format ASAP.** You cannot break from ISO 8601 date-time formatting and roll a custom format for JSON and have it still be compatible with JSON libraries - both frontend and backend should ALWAYS use `Date` (built-in) and the proper `toString()` format - which is ISO 8601. This needs to be rectified quickly - and existing schedules in the database need to be retroactively fixed.

**Comment by Linoy339** [comment] 2021-12-13 17:35
@avaidyam . Present data format to save a schedule is :

`{"schedule":
[{"start_date":"2021-10-29T11:33:00.000Z",
"time":"2021-10-29T11:34:04.124Z",
"custom_time":null,
"repeat_interval":"biweekly",
"notification_ids":[222496]
}
]}`

Is this format an issue and  to be changed ?

**Comment by avaidyam** [comment] 2021-12-13 18:16
@Linoy339 The format you have shared in the comment is correct, however, **you must remove `notification_ids`**. That cannot be exposed in any API. I was referring to this comment you made: 

> Also the key time in schedule object would be either `2021-12-13T08:30:45.820Z`(old schedules) or `13/12/2021, 22:25:16 pm` (new schedules).

This new schedule format `13/12/2021, 22:25:16 pm` is _illegal_ for JSON + ISO 8601. Please do not use this kind of format anywhere. This format - `2021-12-13T08:30:45.820Z` - is correct and accepted.

**Comment by sarithapillai8** [comment] 2021-12-14 05:20
@avaidyam 
We didn't change anything. The format is still the same as  ISO 8601 date-time formatting.

So our plan is like existing data will have issues like - there will be difference in time the researchers tried to set schedule. ie, With current schedules the notifications and feed will work with UTC time, not the time set by the researcher. 
UI will be changed like the time selected by the researcher will be saved without any conversion in  ISO 8601 date-time format and it will be used without any conversion for notifications and feed.

**Comment by sarithapillai8** [comment] 2021-12-29 09:46
@avaidyam @SuruPa00 
Do you want the date to be keep in the same way as time? I mean as we take the time string from UTC format save datetime, do we need to extract the date or do we need to convert it in local timezone?

**Comment by avaidyam** [comment] 2021-12-29 15:56
Just the time for now

**Comment by sarithapillai8** [comment] 2021-12-30 09:07
LAMP-dashboard updates are completed and QA confirmed. The changes will be updated in dashboard-staging after server side changes.

**Comment by ZCOEngineer** [comment] 2022-01-18 06:50
Done almost 70%, remaining developer testing and QA testing.

**Comment by michaelmenon** [comment] 2022-01-31 13:25
it will be pushed to staging by this week. Have changed it to feature as it as a change form the initial given requirement.

**Comment by Linoy339** [comment] 2022-02-01 11:21
@avaidyam . As we discussed, we will push our code by tomorrow. Before, can you add env variable `TIMEZONE` and keep the value as  'America/New_York'. The purpose of this variable is to take it as default value, if not participant timezone is found.

**Comment by avaidyam** [comment] 2022-02-01 13:52
Sure, we'll make sure this env var is added to both staging and production stacks for server and worker. //cc @lukeoftheshire 

@Linoy339 Just to confirm, however, if this variable is not defined, do the server and worker components use UTC time?

**Comment by lukeoftheshire** [comment] 2022-02-01 14:30
@avaidyam @Linoy339 

I have added the TIMEZONE env variable with the specified value to all 4 services.

**Comment by avaidyam** [comment] 2022-02-01 15:50
Great, thanks!

**Comment by sarithapillai8** [comment] 2022-02-02 12:03
@avaidyam We were planning  to update this update on dashboard-staging today. Can we go with it? We need to do QA on dashboard-staging. Hopefully QA can be completed by Monday. In between if any release is planned, could you please let us know?

**Comment by avaidyam** [comment] 2022-02-02 12:03
Yes, that's fine - thanks for the heads up!

**Comment by avaidyam** [comment] 2022-02-04 20:37
Sharing a status update on this issue below: 

> @michaelmenon: We are hoping to complete QA for activity Timezone by Monday for, but just in case its not complete we will confirm that by Tuesday.

**Comment by Linoy339** [comment] 2022-02-09 08:42
> So our plan will cause some issues with existing data like - With the current schedules the notifications and feed will work with UTC time, not the time set by the researcher. UI will be changed like the time selected by the researcher will be saved without any conversion in ISO 8601 date-time format and it will be used without any conversion for notifications and feed.

FYI:

Just Reminding that older schedules can have issues, because the time saved in scheduler was in utc earlier. Now, its with local timezone of the participant. So,  do we  need to inform all researchers to change the time accordingly ?

**Comment by sarithapillai8** [comment] 2022-02-09 14:56
@avaidyam
This is updated in dashboard-staging. QA completed.

**Comment by avaidyam** [comment] 2022-02-11 21:05
@tlakhtak discovered a scheduling error issue with this: 

1. Using `dashboard-staging...`, scheduled a survey for `10:29am`, with the default start date `Dec 31, 1969`. 
2. Received a survey at `10:14am`. 
3. When clicked edit button and re-saved same schedule as before, received another notification at `10:15am`. 
4. When went to add a new schedule and deleted the default hours to put in a new time, got an error `TypeError: cannot read properties of null (reading ‘getHours’)`.
5. Received another survey notification at `10:17am`.
6. And again at `10:19am`.

@Linoy339 Since this seems to be more in the `LAMP-worker` side, can you comment on whether this is expected and why the issue could be happening? 

@sarithapillai8 Can you try to reproduce the `TypeError` on the `LAMP-dashboard` side?

**Comment by Linoy339** [comment] 2022-02-12 05:39
> * Using `dashboard-staging...`, scheduled a survey for `10:29am`, with the default start date `Dec 31, 1969` (which should be the current date instead, I believe). ⚠️
> * Received a survey at `10:14am`. ⚠️
> * When clicked edit button and re-saved same schedule as before, received another notification at `10:15am`. ❌
> * When went to add a new schedule and deleted the default hours to put in a new time, got an error `TypeError: cannot read properties of null (reading ‘getHours’)`. ❌
> * Received another survey notification at `10:17am`. ❌
> * And again at `10:19am`. ❌





> * In another instance, I scheduled a survey for 10:45am, and it shows up in the calendar settings as scheduled but did NOT show up in the Feed and I did not get a notification. ❌

Can you please provide the activity id for both?

**Comment by sarithapillai8** [comment] 2022-02-14 10:49
>@sarithapillai8 Can you try to reproduce the TypeError on the LAMP-dashboard side?

This is fixed in dashboard-staging.

**Comment by divyav2020** [comment] 2022-02-14 12:11
We are unable to reproduce this issue

**Comment by avaidyam** [comment] 2022-02-14 16:05
That should be correct. //cc @tlakhtak

**Comment by Linoy339** [comment] 2022-02-14 16:15
There are no schedules now for any of these activities. I think, all the schedules has been deleted.
We believe, no notifications are firing now for all these. 
@tlakhtak . Can you please add schedules as you did last week?

**Comment by tlakhtak** [comment] 2022-02-14 16:59
I received notifications last night at 11pm for Cognitive Games activity and 12am for Evening activity. Both activities still have scheduled activities in the Feed, for 7pm and 8pm today respectively.

**Comment by Linoy339** [comment] 2022-02-14 17:24
@tlakhtak . Yes. The notifications are supposed to get fired daily 11pm (Evening activity) and 12 AM (Cognitive Games ). So, its working as expected.

> Both activities still have scheduled activities in the Feed, for 7pm and 8pm today respectively

It seems to be a cache issue, as I am getting displayed it as 11 PM and 12 AM respectively. Please find the screenshot :
![feed](https://user-images.githubusercontent.com/66460654/153914184-e6d46b64-21ad-4f4f-9594-549c98bf03a9.png)

**Comment by Linoy339** [comment] 2022-02-15 09:28
@avaidyam . Here, We doubt on `local notifications` (from mobile app)  that it can happen in UTC too. We might have to do the `utc `to `local time` conversion  in `app` also.

**Comment by Linoy339** [comment] 2022-02-15 16:24
Sure @avaidyam .

**Comment by avaidyam** [comment] 2022-02-18 18:10
@jijopulikkottil Can you please create a new issue detailing the "every two weeks" bug? Let's consider this issue closed but track the status of that bug in an new issue.

**Comment by sarithapillai8** [comment] 2022-02-24 07:38
@avaidyam 
There is one issue reported while our QA. Please see the screenshot attached. 
![Screenshot 2022-02-23 at 11 41 02 PM](https://user-images.githubusercontent.com/63710347/155478958-35486c4a-27e3-4879-8cbc-858c49b03003.jpg)
'Every 2 weeks' schedule is taking the start date for scheduling, as the date field is UTC converted before saving, it is having a mismatch.
We are only considering time field for this timezone change. I have asked about changing the date field in same way and you confirmed not to change. (https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/417#issuecomment-1002500916). So could you please confirm if this is error or what we expect?.

**Comment by avaidyam** [comment] 2022-02-24 17:14
@sarithapillai8 That's correct, the date fields should **always** be in UTC. Even the time field should be **RECORDED** as UTC, but converted to patient timezone by the push notifications scheduler and the frontend. Is the backend converting the timezone for this field or is the frontend? If it's the frontend, this is a simple fix - just turn off the timezone conversion for the date field.

**Comment by sarithapillai8** [comment] 2022-02-25 05:17
@avaidyam 
Time field is recorded in UTC format, but not converted to UTC. Date field is converted and saved in UTC format. These are happening in front end. So can I change it like without converting to UTC, save date field in UTC format?

**Comment by divyav2020** [comment] 2022-03-05 04:33
[LAMP_Admin Website_Time Zone changes.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8189964/LAMP_Admin.Website_Time.Zone.changes.xls)

**Comment by tlakhtak** [comment] 2022-04-12 18:11
This seems to be resolved in staging as I am able to see activities at the time they are scheduled even when I change the timezone, notification schedule does not shift when timezone is changed

**Comment by Linoy339** [comment] 2022-04-13 06:33
@tlakhtak .  This seems like participant  time zone has not git saved. If there is no  time zone saved for particular participant, it would fire notifications in `America/New_York` time zone.
Can you please provide participant  id together with researcher and activity which you were mentioning?

**Comment by tlakhtak** [comment] 2022-04-13 12:55
on staging dashboard, api-staging domain. Phone timezone was changed to IST, and Feed activities were showing correct times but notifications were coming incorrectly. Research id was `b0b9mcsxr7z6eaepnpjv` participant was `U6942434912`. I saw this with an activity called `dbt` which you can see was scheduled for 2:19pm but was notified at 11:49pm.

![IMG_2940](https://user-images.githubusercontent.com/82968538/163184643-7d37863e-03f7-467a-901f-f0a7b396797a.PNG)
![IMG_2940](https://user-images.githubusercontent.com/82968538/163184686-801674d0-53d7-4ab0-9ad4-48ce205c792b.PNG)

**Comment by Linoy339** [comment] 2022-04-13 14:33
@tlakhtak . Can you please tell approximate time which you changed time zone  to IST ?

**Comment by Linoy339** [comment] 2022-04-14 10:21
@tlakhtak . Can you confirm whether you were notified or not on 2.19 pm (14 th april) IST?
From the logs mentioned below, it states that notification has been triggered on 2.19 pm (14 th april) IST. Please find the highlighted section.

```
2022-04-14T08:49:00.003285108Z data while notifying participants [

2022-04-14T08:49:00.003289155Z   {

2022-04-14T08:49:00.003291798Z     device_type: 'ios',

2022-04-14T08:49:00.003294589Z     device_token: '04116a16b89234fb5bc187e578e81448129537428cb17ae74abdd66f8a5f4070',

2022-04-14T08:49:00.003297501Z     timezone: 'Asia/Calcutta',

2022-04-14T08:49:00.003300661Z     participant_id: 'U6942434912'

2022-04-14T08:49:00.003303594Z   }

2022-04-14T08:49:00.003306151Z ]

2022-04-14T08:49:00.003308605Z start_notify true

2022-04-14T08:49:00.003312471Z notified U6942434912

2022-04-14T08:49:00.003335628Z {

2022-04-14T08:49:00.003355416Z   nw: 2022-04-14T08:49:00.003Z,

2022-04-14T08:49:00.003358690Z   device_token: '04116a16b89234fb5bc187e578e81448129537428cb17ae74abdd66f8a5f4070',

2022-04-14T08:49:00.003361642Z   device_type: 'ios',

2022-04-14T08:49:00.003364279Z   payload: {

2022-04-14T08:49:00.003366811Z     participant_id: 'U6942434912',

2022-04-14T08:49:00.003369599Z     activity_id: '9s50tc6zqayz9ynrw0kb',

**2022-04-14T08:49:00.003372265Z     message: 'You have a mindLAMP activity waiting for you: dbt.',**

2022-04-14T08:49:00.003374833Z     title: 'dbt',

2022-04-14T08:49:00.003377325Z     url: '/participant/U6942434912/activity/9s50tc6zqayz9ynrw0kb',

2022-04-14T08:49:00.003388570Z     notificationId: 575427

2022-04-14T08:49:00.003391469Z   }

2022-04-14T08:49:00.003393909Z }
```

**Comment by tlakhtak** [comment] 2022-04-15 12:20
I cannot confirm as the phone was no longer in IST. I will test this again today, allowing the timezone change to sit for a few hours before expecting a notification.

**Comment by tlakhtak** [comment] 2022-04-15 20:24
Can confirm this was fixed in staging.

**Closed** 2022-04-18 13:00 UTC
Labels: feature, 2day, native core, priority MEDIUM
