### ISSUE TITLE
Tip category icons not saving - but individual tips within them are

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#198] opened 2021-04-21 19:07 UTC
> I added icons to all the tips and they all saved. I created myself an account in this study and when i logged in there were no icons on the tips, although it is showing the space for them. Same on dashboard view and iphone. When i click into the tip, the icon IS there. So it seems as though the first one (for the tip category) does not appear but the second one (for the individual tip) DOES appear.
![image](https://user-images.githubusercontent.com/82968538/115607665-3bbcb280-a2b3-11eb-9bd4-562218cd9c3a.png)
![image](https://user-images.githubusercontent.com/82968538/115607676-3f503980-a2b3-11eb-9026-ab8089d7f581.png)

**Comment by avaidyam** [comment] 2021-05-21 15:53
Duplicate of #170!

**Closed by avaidyam** 2021-05-21 15:53 UTC
