### ISSUE TITLE
mindLAMP Participant Dashboard Not Visible

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#805] opened 2024-04-09 20:39 UTC
**Describe the bug**
For certain participants on a collaborators server, we have received two reports of participants and investigators not being able to see participant data on the portal, despite reports that the data had been entered. The reports are as follows:

1. "The participant has been completing daily surveys for the entirety of their participation but the last survey that shows up for both them on their portal section of the app and on my online access is back in December (except for one entry March 5th)."

2. Despite the participant being shown as last active 15 hours ago (as of today, 2:43 PM 4/8), when I click on their user to see their activity and perform the Mindlamp check-in, both the activity and cortex section show up as blank and I am unable to see any of their completed survey dates.

We have received general reports of this happening on another, separate server, but are pending further information. I have requested screenshots of the errors reported, and are pending, but thought it prudent to submit the error quickly while waiting for further intel. Notably, this issue has not replicated on our home server.

**Screenshots**
Pending!

**Smartphone (please complete the following information):**
Report 1:
- Device: iPhone 12 Pro
- OS: IOS 16.4.1

Report 2: 
- Device: iPhone 13 Pro Max
- OS: IOS 16.5

**Comment by carlan1** [comment] 2024-04-09 23:50
Are they reporting that none of the participants' activity data is showing in the portal? Or is each group only reporting that one participant's data is not showing?

**Comment by ertjlane** [comment] 2024-04-10 12:22
@carlan1 The latter!

**Comment by sarithapillai8** [comment] 2024-04-11 06:58
@ertjlane @carlan1 Could you please confirm if all the updates are on the server? As we cannot reproduce this with our version, it will be hard to find the issue. If you can post further details, we can try to figure out what might be missing.

**Comment by ertjlane** [comment] 2024-04-17 19:32
Hello all,

It is possible that there are two distinct issues here masquerading as one, as I've received more information. For one of the users, their dashboard reports them being active (having submitted surveys), yet when looking in the portal no graph appears at all.
<img width="1462" alt="image002" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/1498b9f1-a6cc-4bda-807d-0c3d0b303fdc">

<img width="1461" alt="image003" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/c55b3edd-cc66-4a01-804b-939fd0db5539">

For the latter case, the graph appears, and the user reports that they have been completing surveys since December, but their visual only demonstrates one survey completed since, that being in March.
<img width="1462" alt="image005" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/406e9790-70ee-4cd0-9224-ab93f76e0aba">

<img width="1465" alt="image006" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/d500aa52-2832-4756-b72e-7001adff75a1">

**Comment by ertjlane** [comment] 2024-04-22 13:54
@sarithapillai8 Understood, thank you for looking at this. I will email you a set of a test credentials.

**Comment by sarithapillai8** [comment] 2024-04-23 11:38
@ertjlane Can we submit some surveys to debug the condition with the provided test credentials?

**Comment by ertjlane** [comment] 2024-04-24 13:08
@sarithapillai8 Yes absolutely!

**Comment by evinkalengaden** [comment] 2024-04-25 08:27
Hi @ertjlane , We were unable to reproduce the Survey issue associated with the Portal. Could you please confirm. Also please refer the screenshots
![Portal View 1](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/74286138/ac186a26-c69e-4a2a-946e-4285a7909dc3)
![Portal View 2](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/74286138/1fe5e869-0253-4b31-8dd9-ad99d794c781)
 attached.

**Comment by ertjlane** [comment] 2024-04-25 13:42
@evinkalengaden Thank you for looking into this, the fact that you were not able to reproduce it is useful information as well. I will get back to you if/when we have more information.

**Comment by carlan1** [comment] 2024-05-22 13:58
Closing for now

**Closed by carlan1** 2024-05-22 13:58 UTC
Labels: bug, frontend, cannot reproduce, on hold
