### ISSUE TITLE
mindLAMP iOS Application crashing with iPhone 12

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#659] opened 2022-06-21 19:29 UTC
We have one study participant who has iPhone 12. Study participant installed the mindLAMP2 iOS app on her iPhone, and entered all her information on the log in page and clicked 'log in', the app booted her out. When she tried to re-open it, the app would just flash and kick her out again. Study team confirmed Location services is enabled, Low Power mode is disabled and participant has proper settings for the mindLAMP2 app to collect sensors data.

Is there a way to debug the participant application crashing issue with mindLAMP app in iPhone 12 to provide the solution?

**Comment by jijopulikkottil** [comment] 2022-06-22 06:53
Hope the user using the App Store version!.
Is it possible to try login on iPhone's native Safari app ?
Also is it possible to provide test user details if its different domain?

@divyav2020 Could you test with iPhone 12

**Comment by divyav2020** [comment] 2022-06-22 12:04
I have checked  iPhone12 device with OS versions 15.0.2, 15.5 and 14.7.1 (Checked with Appstore build). Successfully Logged in and could navigate to all tabs.  
Could you please provide test user details if its different domain?

**Comment by michaelmenon** [comment] 2022-06-27 13:06
Hi @jeydude we have sent you an email on this. please check.

**Comment by jeydude** [comment] 2022-06-27 16:59
Thanks @michaelmenon I have emailed Divya with login information.

**Comment by michaelmenon** [comment] 2022-06-28 11:20
Hi @jeydude,  we checked on six iPhone12 devices with OS versions 15.0.2, 15.3.1, 15.5, 15.1, 15.3.1 and 14.7.1 (Checked with Appstore build). Successfully Logged in and could navigate to all tabs.
We checked with Location services  enabled and Disabled State and also Low Power mode is disabled. But couldn't reproduce the crash.    

Could you please let us know if the user is using the latest build from the AppStore ? Also can let us know did the app close on the user or did it sho any error alert before closing the app ?  

Also can you please check if the user can login to the  LAMP on the iPhone browser and not using the iPhone App. ?

**Comment by jeydude** [comment] 2022-06-28 15:17
Thanks for checking on iPhone 12 devices, I will inform the study team and share the info.

**Comment by jeydude** [comment] 2022-07-12 18:50
We tried again today, study participant downloaded most recent version of mindLAMP 2 from App Store, Location Service was ON and Low Power Mode was disabled. Once she entered the domain name, email address and password clicks Login button then app just crashed. 

After that every time she clicks on the mindLAMP 2 icon from the home screen of her iPhone 12, it just flashing/crashing, not opening the home screen.

There is no issue with login information, we tested in Safari Browser.

**Comment by jeydude** [comment] 2022-07-13 13:59
Yes @jijopulikkottil, we tried with 2022.6.29 version of the iOS app from app store.  I have asked for iPhone version with study team, once i hear from them I will share it.

**Comment by jeydude** [comment] 2022-07-13 19:00
Study participant is using iPhone 12 with software version 15.5

**Comment by jijopulikkottil** [comment] 2022-07-18 07:48
When we check with crash reports, we couldn't see any from iPhone 12. Could you add some text in 'Report' option when getting a crash.

Also In login page, can you try the 'Try It' option  (as participant) and see is there any crash or not ?

**Comment by michaelmenon** [comment] 2022-09-19 12:09
@jeydude is there any update on this or should we close this ticket.

**Closed** 2022-09-20 01:38 UTC
Labels: bug, NO ETA, native core, cannot reproduce, priority MEDIUM

**Comment by jeydude** [comment] 2022-10-11 07:16
Hi Divya,

Here is the login information for the participant. I do not have an iPhone
12 to test.

Domain name: *pep.api.mayo.edu/mlpapiservice/v1
<http://pep.api.mayo.edu/mlpapiservice/v1> *

email: ***@***.***

password: mindlamp1


Thanks for your help to troubleshoot this issue. Thanks!


Thanks,

Jeyakumar Raman

**Comment by divyav2020** [comment] 2022-10-11 11:28
@jeydude Could you please provide Email id of the user

**Comment by ertjlane** [comment] 2022-10-13 17:58
Hello all! Please do not share mindLAMP credentials for anyone (users or administrators) in github. I've deleted them from the comment here for this reason. If user credentials need to be shared, please email them to our team (digital psych) and we will pass them on to the developers. Thank you!
