### ISSUE TITLE
Mark as complete does not do anything under Learn/Tip

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#279] opened 2021-06-01 15:56 UTC
When a study participant clicks "Mark as complete" button under Learn/Tip, does it provide any information to researcher?

It does not call any API to update the server.

**Comment by avaidyam** [comment] 2021-11-17 14:50
Duplicate of #411.

**Closed by avaidyam** 2021-11-17 14:50 UTC
Labels: bug, frontend
