### ISSUE TITLE
Android user not receiving notifications

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#206] opened 2021-04-21 19:20 UTC
> My participant said that they followed the instructions but have not received any notifications, other than one saying active data collection, that doesn't ever go away. Today, they uninstalled and reinstalled the app and are still not receiving notifications.

**Comment by avaidyam** [comment] 2021-05-21 16:53
Duplicate of #120!

**Closed by avaidyam** 2021-05-21 16:53 UTC
