### ISSUE TITLE
Partially translated survey pages

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#225] opened 2021-04-26 12:43 UTC
> Surveys (both PHQ-9 and sleep) are showing partially translated (English to Hindi) survey pages. Assuming the full translation was submitted to you, the app should show the fully translated pages.
![image](https://user-images.githubusercontent.com/82968538/116084131-733cad80-a66b-11eb-88f5-98e8589c7deb.png)
![image](https://user-images.githubusercontent.com/82968538/116084151-7768cb00-a66b-11eb-9957-337ce06054bc.png)

**Comment by avaidyam** [comment] 2021-05-21 17:23
Duplicate of #138.

**Closed by avaidyam** 2021-05-21 17:23 UTC
