### ISSUE TITLE
Auto-logout

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#323] opened 2021-07-20 13:06 UTC
Participants reporting being logged out of the app and being required to sign back in every time they open it up, which defeats the purpose of passive data collection.

**Comment by SuruPa00** [comment] 2021-07-20 14:18
The participants reporting this issue are U5021714125 and U8974761142

**Comment by divyav2020** [comment] 2021-07-23 14:24
We created a participant under the NIH2 study & TECC study and tried different scenarios, but unable to reproduce the issue.
Scenario 1: Logged in to the app and kept the application idle( for approx. 20-30 minutes). Then refreshed the screen.
Scenario 2: Logged in to the app and kept the application idle ( for approx. 20-30 minutes). Then killed the app from background and reopened it.
Scenario 3: Logged in to the app and waited for push. From the background, selected the push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity.
Scenario 4: Logged in to the app and killed the app from background. Waited for push. From the background, selected the push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity

We shall continue with testing more scenarios. Meanwhile, it could be helpful if you could provide us with more precise steps / participants to reproduce the issue

**Comment by SuruPa00** [comment] 2021-07-23 15:52
The participants struggling with this issue are U8974761142 and U5021714125

**Comment by divyav2020** [comment] 2021-07-26 07:32
Could you please provide the password also?

**Comment by tlakhtak** [comment] 2021-07-26 12:28
Can admin password be used to log in? If not, we can make a temporary password

**Comment by SuruPa00** [comment] 2021-07-26 13:30
U8974761142 has the temporary login email test1@lamp.com and pw test1 and U5021714125 has the email test2@lamp.com and pw test2

**Comment by SuruPa00** [comment] 2021-08-23 14:23
@avaidyam can you check in on this since we're getting more instances of this

**Comment by avaidyam** [comment] 2021-08-23 15:09
@ZCOEngineer @sarithapillai8 I believe the issue may be in `LAMP-dashboard` in `App.tsx` - the credentials are being cleared incorrectly from `localStorage` before the code can validate whether the app is logged in. **As a reminder, the app should NEVER log anyone out unless "Log Out" is clicked and the confirmation dialog is presented FIRST.**

**Comment by sijugeorge-zco** [comment] 2021-08-25 05:55
@avaidyam @SuruPa00 

Since we cannot reproduce the issue here, can you please provide iPhone Model and iOS version for the devices having auto-logout issue ?

**Comment by SuruPa00** [comment] 2021-11-05 15:38
@divyav2020 any update?

**Comment by michaelmenon** [comment] 2021-11-05 15:48
Hi @SuruPa00 I will check on it on Monday and get back to you.

**Comment by divyav2020** [comment] 2021-11-08 10:58
@SuruPa00 I couldn't reproduce the issue
I have checked the following scenarios. But couldn't reproduce the auto logout issue
Scenario 1: Logged in to the app and kept the application idle ( for approx. 30 minutes). Then killed the app from background and reopened it. - Tested

Scenario 2: Logged in to the app and kept the application idle( for approx. 30 minutes). Then refreshed the screen. - Tested

Scenario 3: Logged in to the app and killed the app from background. Waited for push. From the background, selected the push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity - Tested

Scenario 3: Logged in to the app and killed the app from background. From the background, selected the push message which is already fired before killing the app from the background. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity  - Tested 

Scenario 4: Logged in to the app and kept the application idle( for approx. 2hrs) and waited for push. From the background, selected the push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity

Scenario 5: Logged in to the app and waited for push. From the background, selected the push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity. - Tested

Scenario 6: Logged in to the app and kept the application idle( for approx. 2hrs) and waited for push. From the background, selected the push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity. - Tested

Scenario 7: Logged in to the app and kept the application idle ( for approx. 30 minutes). Then attended a phone call. Then opened the app - Tested

Scenario 8: Logged in to the app and kept the application idle ( for approx. 30 minutes). Then attended a phone call. Then killed the app from background and reopened it. - Tested

Scenario 9: Logged in to the app and kept the application idle . Then attended a phone call. Then from the background, selected a push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity - Tested

Scenario 10: Logged in to the app and kept the application idle . Then attended a phone call. Then  killed the app from background. Then from the background, selected a push message. Application moved to Login screen. After 1-2 seconds, screen automatically navigated to the corresponding activity - Tested
. 
Scenario 11 : Logged in to the app and kept the application idle ( for approx. 1hr). Then opened many apps (eg: youtube, face book etc) in the background. Then opened the app - Tested

Scenario 12 : Logged in to the app and kept the application idle ( for approx. 1hr). Then opened many apps (eg: youtube, face book etc) in the background. Then killed the app from background and reopened it. - Tested

Scenario 13 : Logged in to the app and kept the application idle ( for approx. 48hrs). opened the app. Application shows inner screens - Tested

Scenario 14 : Opened the app and attended all the activties including notification activities. then kept the app in the background for 48hrs. Then switched off the phone. Then switched on the phone after 24hrs. Got 2 push notification. Opened one notification and attended. After completing that activity (it was breathe), clicked back option. Then application showed white screen. Then Killed the app and opened again. Application showed assess screen - Tested

**Comment by jtorous** [comment] 2021-11-08 11:56
Thank you for looking into this so thoroughly. We will continue to test
too, but your testing above is most helpful!

-John

**Comment by Linoy339** [comment] 2021-12-07 07:00
@SuruPa00 @avaidyam . This can also happen when sudden crash in LAMP-server ([https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/431](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/431)).
We yet need to find out why the container is getting crashed and restarts. The auto logout might get resolved if we resolve the above issue

**Comment by avaidyam** [comment] 2022-01-31 14:19
@Linoy339 From our discussion this morning - please update the initialization of NATS and Redis to be failsafe ("fail gracefully") so it does not crash the API Server if NATS/Redis are not found.

**Comment by Linoy339** [comment] 2022-02-01 11:29
@avaidyam. Its done in such a way that the api server won't crash  even when  the NATS/Redis are not found.

**Comment by tlakhtak** [comment] 2022-02-01 15:57
Another user experienced the log out issue. User U1456972679 (email: U1456972679@lamp.com, pass: U1456972679) has to re-log in to the app everytime they open it to respond to notifications, as opposed to being persistently logged in as they should be. This issue has been happening since Jan 27, which is when the account was made, and continues today, Feb 1. The device being used is an iPhone XR.

**Comment by tlakhtak** [comment] 2022-02-08 13:46
U3826134542 also experienced the auto-log out issue as per the comment above (email: U3826134542@lamp.com, password: U3826134542)

**Comment by avaidyam** [comment] 2022-02-08 16:52
> But the login page will appear first and then navigating to activity page automatically within 1 or 2 seconds. So slow network may lead to showing the login screen longer time.

This is great feedback - it sounds exactly like what I predicted, and more of a `frontend` issue than a `backend` or `native core` issue. For now, @jijopulikkottil and @Linoy339 please continue to investigate the login flow on those sides.

@sarithapillai8 I'll update this issue to reflect that it's likely a frontend issue so please investigate why the login screen shows up at first even if the user is logged in already. The bug likely exists in the `App.tsx` file with the routing handlers that may not be working as expected.

**Comment by sarithapillai8** [comment] 2022-02-09 04:56
>@sarithapillai8 I'll update this issue to reflect that it's likely a frontend issue so please investigate why the login screen shows up at first even if the user is logged in already. The bug likely exists in the App.tsx file with the routing handlers that may not be working as expected.

@avaidyam
LAMP.Auth.refresh_identity - this API will be called for each URL while login check. All the routes are written with a checking for the session check (state.identity) and if this is false/undefined the login page will be loaded. In between while we call this API, the login page will load and after setting this state with API call, it will be redirected to the page requested. This is common for all the routes and are working as expected. Recently we have a change like all the pages are with different URLs, so the same working for those too as expected. But when there are network issues, this API will not be triggered and there is no way to set state identity now. So do you think a localStorage or something to be used for this as a solution? Please suggest.

**Comment by jijopulikkottil** [comment] 2022-02-22 00:50
@sarithapillai8 @avaidyam 
Done a quick test on app side, When open in new web view which  has session storage item  LAMP._auth, It still shows same behaviour [loading login first and then navigating to activity page] even if use without `?a='.
[In LAMP._auth, we are setting 3 key-values which are serverAddress, id and password]

But it works fine (no login screen flashes) if we open in existing web view of lamp dashboard.

**Comment by jijopulikkottil** [comment] 2022-03-07 04:59
@avaidyam  On app side, do we need to open the activity page in the same web view of lamp dashboard to avoid 'login' page appearance ?

**Comment by jijopulikkottil** [comment] 2022-03-07 15:25
on tapping push notification, if we open the activity page in the same web view, we need to make sure few more things:
1. on front end, in the succeeding screens of activity, there should be a back button (`<-`) to return to loaded dashboard.
2. on app side, need to test what will happen when tapping on second activity when first one is loaded!

**Comment by saranya-sajeev** [comment] 2022-03-07 15:44
@avaidyam In Android , opening the activity page in the same webview of Lamp dashboard avoids login page as in iOS. In Android also we have to check [above items](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/323#issuecomment-1060808208).

**Comment by avaidyam** [comment] 2022-03-07 21:43
@jijopulikkottil @saranya-sajeev Is it possible to re-use the WKWebView, even if we're loading the activity from a notification instead of inside the app? If so, that should be fine. If you do test this, please share a screen recording here so we can see what it looks like.

**Comment by jijopulikkottil** [comment] 2022-03-09 11:16
@avaidyam  please see the screen recording [here](https://www.fromsmash.com/mdr6vExmeG-dt) 
At 00:35, The new activity page is not loading when user is interacting another activity. Android also have the same issue. We need to investigate this.
At the end of the video, the 'Success' screen doesn't have the back button to load the dashboard. This have to fix on front-end.

**Comment by saranya-sajeev** [comment] 2022-03-09 11:34
@avaidyam please find the Android screen recording attached. In Android, using the device back button we can move to the dashboard.  https://user-images.githubusercontent.com/81216000/157433559-c7bacb6a-02f7-4d4f-9f2c-4f55fa535642.mp4

**Comment by avaidyam** [comment] 2022-03-22 12:54
Since we're tracking this issue in #560 with a better scope of work, I'll close this issue for now.

**Closed by avaidyam** 2022-03-22 12:54 UTC
Labels: bug, 4day, frontend, priority HIGH

**Comment by tlakhtak** [comment] 2022-04-12 18:57
Could not reproduce in staging account, so possible no longer an issue but cannot confirm since this was only affecting some users.
