### ISSUE TITLE
Can't exit Tip on Mobile device

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#548] opened 2022-03-04 16:15 UTC
When I attempt to exit a Tip on my mobile device, the screen displays the loading icon (and sends the activityevent, as displayed in Portal/Prevent) but does not return me to the Tips page.

This does not happen on desktop.

https://user-images.githubusercontent.com/34659264/156799122-ac20561a-3ae9-4895-980f-02e80d2a9dda.mp4

**Comment by lukeoftheshire** [comment] 2022-03-05 20:25
As an update this does NOT happen if I use the back button in the navbar at the bottom of my phone - but I don't get the streak notification either so I suspect no ActivityEvent is being fired

**Comment by sarithapillai8** [comment] 2022-03-07 05:50
@lukeoftheshire 
>I don't get the streak notification either so I suspect no ActivityEvent is being fired

The activity event can be saved on the activity back button. 

We are trying to reproduce this issue. Is this coming with notification?

**Comment by divyav2020** [comment] 2022-03-07 06:58
@lukeoftheshire 
We have checked in Both iOS and Android devices (from Normal screen and Notification). But we are unable to reproduce this issue

**Comment by divyav2020** [comment] 2022-03-07 13:57
Updated in staging
[LAMP_Admin Website_Tip Issue.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8198172/LAMP_Admin.Website_Tip.Issue.xls)

**Closed** 2022-03-07 21:43 UTC
Labels: bug, 1day, frontend, priority MEDIUM

**Comment by tlakhtak** [comment] 2022-04-15 20:28
Fixed in staging.
