### ISSUE TITLE
Several Issues for one user

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#645] opened 2022-06-02 20:15 UTC
**Describe the bug**
User U3600685320 on Android device Samsung Galaxy S22 Ultra reported that they were experiencing 'Uncaught Exception' and ' app not responding' errors (screenshots attached). These come up randomly when clicking into an activity, a mindfulness activity, or even when click lamp app from home screen. This issue has been going on for about a month (since the last update). The user works around it by closing things out and rebooting.

Also, similar to issue #593 , notifications for feed-scheduled activities did not directly lead to the activity - the app would default to a loading screen and then Assess page. 

**Screenshots**
![Screenshot_20220523-191735_mindLAMP](https://user-images.githubusercontent.com/103677721/171729538-c1b6ba1a-efe0-41cf-80eb-ce1a74fc0df8.jpg)

![Screenshot_20220523-191722_mindLAMP](https://user-images.githubusercontent.com/103677721/171729410-03042707-291f-4307-a30f-a9bf1dd72e0d.jpg)

**Comment by saranya-sajeev** [comment] 2022-06-08 05:41
@Devayani0102 We have fixed the  invalid end date issue and is available in beta build. Could you please check the beta build. Is it possible to share the log file to check the not responding error?

**Comment by avaidyam** [comment] 2022-06-10 17:54
@saranya-sajeev If this is fixed in the beta build, can you mark issues with the `QA testing` label? Please have your team test this first as we cannot ask patients to test bugs routinely.

**Comment by saranya-sajeev** [comment] 2022-06-13 06:35
@avaidyam We will test and update you on this.

**Comment by divyav2020** [comment] 2022-06-13 11:22
We have checked this issue in latest Beta build and we couldn't reproduce it

**Comment by michaelmenon** [comment] 2022-06-13 12:37
It's fixed in beta, once beta is pushed to production it should get resolved.

**Closed** 2022-06-27 13:11 UTC
Labels: bug, NO ETA, native core, priority HIGH
