### ISSUE TITLE
User hierarchy changes

### ISSUE THREAD

**Issue by sarithapillai8** [BIDMCDigitalPsychiatry/LAMP-platform#378] opened 2021-09-10 03:39 UTC
@avaidyam @SuruPa00 @michaelmenon @ZCOEngineer 

As per the discussion we had, please find the summery of the requirement below : 

**Super admin :** 
The additional feature will be managing clinical admins and user admins. User admins and clinical admins will be created as admins and they will be managed through the tag “gov.lacounty.dmh.admin_permissions” in the format : {“test@dmh.lacounty.gov”: “edit”,   “test2@dmh.lacounty.gov”: “view”}. The values - 'edit' for user admins and 'view' for clinical admins. And the credentials will be created with origin = null for all type admins.

Load this Tag upon admin-level login; if Tag does not exist, ignore this feature entirely. 

- LA DMH’s server will have this Tag set up - feature must be enabled
- BIDMC server will NOT have this Tag set up - feature is disabled 

**Clinical admin :** 
 - They can see the list of researchers and can impersonate as each.

**User Admin:**
 - They can manage the researchers, but they cannot enter into researcher view.

**Researcher :** 
We will be introducing 2 separate options - simplified and advanced.

1. **Simplified view - Clinician** - Who can create studies along with users. Only the third option 'Add user and group' will be available and only users tab will be shown.
2. **Advanced view - Researcher** - We will keep the current functionality without any change.

@avaidyam 

1. Can we use the current listing method(implemented with user hierarchy change -![listing](https://user-images.githubusercontent.com/63710347/132794913-3022364d-3db1-4dc2-901f-9a45ee771345.PNG)
) for super admin view with a sub-text saying the type of user(Researcher, Practice lead, User Administrator) Or do we need to introduce a new tab for admins? If the first method is ok, then what should come in the place of heading - 'Researchers'.

2.  As a clinical admin or super admin, there will be an option to impersonate as researcher. Do we need to have a toggle option in the top of researcher page to switch between clinician and researcher? If yes, can we use the same for researcher/clinician login without having separate login button?

3.  **_If Tag "gov.lacounty.dmh.admin_permissions'' does not exist, ignore this feature entirely_** - So in this case, we won't have an option to create user/clinical admins and also there will not be a separate view for clinicians and researchers , right?.

Please confirm on these.

**Comment by ZCOEngineer** [comment] 2021-09-10 03:44
@SuruPa00 @avaidyam Could you confirm this ?

**Comment by avaidyam** [comment] 2021-09-10 12:02
@sarithapillai8 
1. No - please make modifications to show administrator type in the `Manage Credentials` dialog box only. The subtext should be removed as that page shall only list `Researcher` otherwise.
2. To simplify things, we are moving to the language "Simple mode" and "Advanced mode" - this toggle can be at the top toolbar of the Researcher view page and this should be remembered in `localStorage` as a global setting that applies to ALL Researcher views. **The default should be Simple mode.** This way we will not need to implement multiple login buttons. 
3. Yes - that is correct; if the tag does not exist then this feature is disabled and the dashboard will behave the same way as it does right no. If the tag exists (i.e. enable this feature by creating a blank `{}` tag) then this new UI will be turned on. **However,** the Simple mode and Advanced mode toggle will ALWAYS be available and is NOT tied to this Tag. 

Please keep in mind that "user/clinic admin" and "simple/advanced mode" are two entirely different independent features - there is no overlap in functionality or implementation.

**Comment by SuruPa00** [comment] 2021-09-10 15:20
Am attaching the [powerpoint](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7144763/User.Hierarchy.pptx) after our discussion here as well for future reference

**Comment by sarithapillai8** [comment] 2021-09-11 04:08
@avaidyam 
Thanks. This clarifies all confusions. 
Just one more thing - By the global setting for all researchers, do you mean to have an array like  
 { "researcher_id1":"simple", "researcher_id2":"advanced"
}
 in localstorage? And if the researcher logins through another device, he will have simple mode by default. right?

**Comment by sarithapillai8** [comment] 2021-09-13 16:58
@avaidyam @SuruPa00  Could you please clarify the question asked above?

**Comment by avaidyam** [comment] 2021-09-13 18:17
@sarithapillai8 
1. Yes, manage it with the role field (ONLY if logged in at the admin level, convert it to a drop down with 3 options: system admin, user admin, clinical admin. Otherwise should be a text field as it is now.) 
2. No, I mean that the simple/advanced setting is preserved across ALL researcher views. If I view r1 in simple mode, go back, and open r2, it should also be in simple mode. From here I can still toggle it to advanced mode - and now if I go back to r1, it will show in advanced mode too.

**Comment by sarithapillai8** [comment] 2021-09-14 01:20
@avaidyam 
2) How to manage this functionality in the direct researcher login? same way?

**Comment by avaidyam** [comment] 2021-09-14 01:36
What do you mean by "same way"? I don't understand the question.

**Comment by sarithapillai8** [comment] 2021-09-14 02:07
@avaidyam 
When a researcher logins, we save the mode used. Suppose another researcher  logins through the same system, the previously saved mode to be used?

**Comment by avaidyam** [comment] 2021-09-14 02:37
That is the correct implementation.

**Comment by sarithapillai8** [comment] 2021-09-14 12:17
@avaidyam @SuruPa00 
Aditya,
I tried setting tag for user/clinical admins - **_LAMP.Type.setAttachment(null, "me", "gov.lacounty.dmh.admin_permissions", permissions)._** This is getting saved. But while returning through getAttachment through **_LAMP.Type.getAttachment(null, "gov.lacounty.dmh.admin_permissions")_** - I am getting error like -
 {
    "error": "(intermediate value) is not iterable"
}
Could you please suggest a solution ?

**Comment by avaidyam** [comment] 2021-09-14 12:21
This sounds like a backend bug - @Linoy339 can you double check that `null` is supported? If not, it should be supported with admin-level credentials only.

**Comment by Linoy339** [comment] 2021-09-14 13:20
@avaidyam . In [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/master/src/repository/mongo/TypeRepository.ts#L14](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/master/src/repository/mongo/TypeRepository.ts#L14), we get undefined when null passed as typeid.
As this type do not includes in researcher,participant or any resource it always returns undefined.

If the typeid is null, do we need to tweak the condition here
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/master/src/repository/mongo/TypeRepository.ts#L119](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/master/src/repository/mongo/TypeRepository.ts#L119)

Can you suggest?

**Comment by avaidyam** [comment] 2021-09-14 13:23
Yes, please tweak the conditions to allow for null values. This should only apply for `Credential.*` methods and `Tag.*` methods.

**Comment by Linoy339** [comment] 2021-09-14 13:36
> Yes, please tweak the conditions to allow for null values. This should only apply for `Credential.*` methods and `Tag.*` methods.
How can we do it specifically, if you can give some hints, it would be more helpful.




> Please also ensure all SensorSpec and ActivitySpec methods are fully functional ASAP.

We have tested it once. Any way, we will go for a round asap and update you

**Comment by sarithapillai8** [comment] 2021-09-16 08:56
@avaidyam 
ithink you have missed this in previous comment.
Yes, please tweak the conditions to allow for null values. This should only apply for Credential.* methods and Tag.* methods.

**How can we do it specifically, if you can give some hints, it would be more helpful.**

**Comment by sarithapillai8** [comment] 2021-09-16 09:46
@SuruPa00 @avaidyam 
I have updated simple/advanced mode in dashboard-staging. If you can take a look and everything seems ok, it can be released with https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/363

**Comment by SuruPa00** [comment] 2021-09-16 12:12
@sarithapillai8 shouldnt i be seeing the two logins on the main login page? as of right now, there is still the single big login option - also tried in incognito

**Comment by avaidyam** [comment] 2021-09-16 12:14
@sarithapillai8 Is there a toggle button once the user has logged in? That implementation works too.

**Comment by sarithapillai8** [comment] 2021-09-16 12:15
@SuruPa00 
Please see what @avaidyam confirmed - https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/378#issuecomment-916850832.
@avaidyam There is toggle button on top toolbar for researcher page.

**Comment by sarithapillai8** [comment] 2021-09-16 12:18
@avaidyam 
Could you please reply to this?
https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/378#issuecomment-920717543

**Comment by SuruPa00** [comment] 2021-09-16 12:39
@sarithapillai8 the simple/advanced modes seem to be working as intended, is the user admin/practice lead part of the hierarchy being worked on separately? just confirming

**Comment by avaidyam** [comment] 2021-09-16 12:41
@sarithapillai8 @Linoy339 I mean to say that the API methods for Tag and Credential should allow `null`. I don't understand the confusion here?

**Comment by sarithapillai8** [comment] 2021-09-16 12:41
@SuruPa00 
Admin side changes are in progress. I am waiting for API fixes which commented above. In the meantime working on other priority task https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/384

**Comment by Linoy339** [comment] 2021-09-16 12:43
@avaidyam . Got it.  We had some other thoughts. Thank you

**Comment by Linoy339** [comment] 2021-09-16 17:10
@avaidyam . Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/132](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/132) for user-hierarchy changes. We need to test it in staging  and may have more fixes related with tag and credential apis. 

There was an issue in activity spec and sensor spec get api for which we fetch spec for particular id(/activity_spec/lamp.gps) and it was listed even if it was deleted. This too fixed in above PR.

**Comment by sarithapillai8** [comment] 2021-09-17 10:52
@SuruPa00 @avaidyam 
Just to confirm, Do we need to hide the new tab 'Data Portal' for Practice Lead and User administrator ?

**Comment by avaidyam** [comment] 2021-09-17 12:12
Yes. System admin should still see it.

**Comment by sarithapillai8** [comment] 2021-09-24 13:06
@avaidyam @ZCOEngineer @michaelmenon @SuruPa00 
This is updated in production. Please check with api-staging login for user hierarchy changes where the tag was created. You can use production api for the other case.

**Comment by SuruPa00** [comment] 2021-09-24 13:28
@sarithapillai8 can you explain how practice lead vs user admin is accessible in the dashboard? This is the admin level we've collectively discussed in the powerpoint. I am in staging and not seeing anything outside the simple/advanced mode, which is on the researcher level

**Comment by sarithapillai8** [comment] 2021-09-24 13:52
@SuruPa00 
As per the requirement, you can use the manage credentials option to create practice lead and user administrator. As the tag gov.lacounty.dmh.admin_permissions is available in api-staging db, you can use admin login of that and can use manage credentials option for this. There are already such credentials available there.

**Comment by SuruPa00** [comment] 2021-09-24 18:22
@sarithapillai8 we received feedback from LA - is it possible to assign groups to the clinicians/researchers that you can view when you are in admin view? There is a request that all researchers/clinicians are assigned a group. This could be similar to how users are assigned a group when in advanced mode of a researcher view.

**Comment by SuruPa00** [comment] 2021-09-24 19:23
@sarithapillai8  i've checked on it and the user hierarchy seems good to go. Can this be pushed to production? Additionally, can you provide/explain what needs to be done in the command line for LA to enable this on their backend? Thanks

**Comment by sarithapillai8** [comment] 2021-09-25 00:05
@SuruPa00 
Thanks. This is updated in production. The tag gov.lacounty.dmh.admin_permissions is ro be created For  LA. 
@avaidyam  Could you please create tag or help @SuruPa00 on this. We don't used to do that.

**Comment by avaidyam** [comment] 2021-09-25 00:08
@sarithapillai8 How did you create the Tag for the staging server? I believe that is what @SuruPa00 is asking about.

**Comment by sarithapillai8** [comment] 2021-09-25 04:44
@SuruPa00 @avaidyam 
I have created it through code. Not with commands.

**Comment by SuruPa00** [comment] 2021-09-28 18:00
@sarithapillai8 this is pushed in production right? Im looking in the manage credentials tab, but am not being given the option to assign 1 of the 3 roles (system admin, user admin, practice lead) when i am trying to create a new admin credential

**Comment by sarithapillai8** [comment] 2021-09-29 01:47
@SuruPa00  Those options will be available if you have the tag gov.lacounty.dmh.admin_permissions there. You can login with api-staging.lamp.digital to check the changes.

**Comment by SuruPa00** [comment] 2021-11-04 12:16
@sarithapillai8 can you make the user hierarchy now no longer be tied to a tag and by default be available for all users?

**Comment by sarithapillai8** [comment] 2021-11-05 04:43
@SuruPa00 
Currently these credentials are managed through the tag "gov.lacounty.dmh.admin_permissions" as per the requirement.. So if this same tag available in the database on server side as it expected to have for LA County, the functionality will work. Nothing to do from the codebase then.
@avaidyam Please confirm.

**Comment by avaidyam** [comment] 2021-11-05 11:54
I think @SuruPa00 is suggesting to remove the Tag check so the feature is always enabled. I think that should be fine now.

**Comment by SuruPa00** [comment] 2021-11-05 12:18
@sarithapillai8 - Yes, what @avaidyam said, we would like there to be no tag check anymore and have the feature always enabled.

**Comment by sarithapillai8** [comment] 2021-11-08 11:32
@SuruPa00 @avaidyam 
Please confirm we can use this same tag to store the user admin and practice lead information (edit/view) or do we need to se a different tag?

**Comment by avaidyam** [comment] 2021-11-08 11:50
Please use a different tag - "lamp.dashboard.admin_permissions".

**Comment by sarithapillai8** [comment] 2021-11-08 11:53
@avaidyam 
For all Server URLs , right? I hope there are nothing saved for the tag used for LA county.

**Comment by sarithapillai8** [comment] 2021-11-10 09:16
@SuruPa00 
This is updated in production.

**Comment by SuruPa00** [comment] 2021-11-15 13:20
@sarithapillai8 is it possible the old tag that was implemented is causing conflict with the new tag that was made? Can you confirm that the old tag is not broken. The LA team is encountering the following issue after their deployment of this updated version:

`After the deployment, we are able to load v1445 dashboard. However, it seems the credentials we have created in QA all stopped working including the System Admin credential. At this point, we are unable to create/modify any account. Does this mean we need to redeploy the database? Do you hare any insight you can share with us?`

**Comment by avaidyam** [comment] 2021-11-17 14:14
@SuruPa00 It looks like there was no backwards compatibility path considered to keep `gov.lacounty.dmh.admin_permissions` working if `lamp.dashboard.admin_permissions` is not defined. The following could resolve this:

```python
import LAMP
LAMP.connect("ADMIN_USERNAME", "ADMIN_PASSWORD", "SERVER_ADDRESS")
data = LAMP.Type.get_attachment("null", "gov.lacounty.dmh.admin_permissions")["data"]
LAMP.Type.set_attachment("null", "lamp.dashboard.admin_permissions", data)
```

**Closed** 2021-11-17 15:24 UTC
Labels: feature, 7day, frontend
