### ISSUE TITLE
Sometimes all of the jewels aren't on the screen

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#219] opened 2021-04-22 14:52 UTC
> Sometimes all of the jewels aren't there.
![image](https://user-images.githubusercontent.com/82968538/115735914-da4f1f00-a358-11eb-9ee6-37fbc123cb3e.png)

**Comment by avaidyam** [comment] 2021-05-21 17:14
Duplicate of #96.

**Closed by avaidyam** 2021-05-21 17:14 UTC
