### ISSUE TITLE
Survey Branching

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#407] opened 2021-10-20 17:42 UTC
We have been reported a request to make survey questions work as efficiently as possible. The main point is that now that we have it fixed so you cannot proceed without answering an item, it makes conditional questions difficult to make. See the text from a collaborator below: 
> I am noticing a related (and new) issue with the survey questionnaire function. We have a final question (type: text) that enables participants to expand on a question if they answered “Yes” to the prior Y/N question. Often this field will be blank and in the past users were able to successfully Submit the questionnaire if this was blank. As of the last update, I am seeing an error message reading “Some responses are missing. Please complete all questions before submitting” and am unable to submit questionnaire responses unless I enter something in this field. Can you please advise? An ideal solution would be to have a branched logic where this question only appears if users select “yes” to the prior question, but they should at minimum be able to submit a blank response. Thank you!

**Comment by SuruPa00** [comment] 2021-11-01 13:02
When this is made, let's make it so it's this advanced, branching survey is a different spec from the current survey

**Comment by avaidyam** [comment] 2021-11-17 15:29
Duplicate of #265.

**Closed by avaidyam** 2021-11-17 15:29 UTC
Labels: feature, frontend, on hold
