### ISSUE TITLE
Mismatch in steps data with Android/iOS mindlamp app

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#156] opened 2021-04-15 13:57 UTC
We have been testing beta version of Android/iOS mindlamp application, we are noticing mismatch in steps value in iOS/Android mindLAMP app.

We are using third-party wearables - VeryFitPro. Step value we are seeing in VeryFitPro seems correct. But the Google Fit/Health App steps values are not 100% match with VeryFitPro. Step value in mindLAMP couchdb is not matching 100% with VeryFitPro steps or Google Fit/Health App apps.

In mindLAMP sometimes we get step values at midnight, even though we did not sync or walked at midnight.

Have you seen these issues, is there any fix for this? Let me know if you need any more information. Thanks!

**Comment by avaidyam** [comment] 2021-04-16 21:26
This should no longer be an issue in the staging iOS and Android apps. Can @jijopulikkottil and @saranya-sajeev confirm? (If this is a duplicate issue let me know and we can close it and move the conversation to the original issue instead.

**Comment by jijopulikkottil** [comment] 2021-05-03 09:48
@jeydude we have done some improvement (https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/133) with latest iOS beta build.

**Comment by jeydude** [comment] 2021-05-03 14:34
@jijopulikkottil Thanks for the update, yes, I noticed that around 4/25 onwards we are getting data similar to Android. Appreciate much for the update!

**Comment by jeydude** [comment] 2021-05-06 14:33
@jijopulikkottil, For steps mismatch with iOS, I am seeing a pattern with Apple Health app and mindLAMP database. Looks like Apple Health App shows data for every 15 minutes, rarely I see multiple entries for the 15 minutes period, mindLAMP is not collecting those multiple entry data that causes mismatch with steps in iOS.

Look at the screens data from iOS and mindLAMP
![ios-health-steps-image](https://user-images.githubusercontent.com/841011/117316210-0042ec00-ae4e-11eb-9156-57e8d52f9052.png)

Data from 9:00 PM to 10:00 PM 
![mindlamp-step-missing](https://user-images.githubusercontent.com/841011/117316218-033ddc80-ae4e-11eb-99c1-802c0f28a7bc.png)

**Comment by jeydude** [comment] 2021-05-06 14:56
@jijopulikkottil, I am not getting some of the sensors value recently, I am using latest test flight version of mindLAMP in iOS. Enabled all the permissions with privacy, health app, mindlamp, wearables app. Any reason? Thanks!

![image](https://user-images.githubusercontent.com/841011/117319408-e35be800-ae50-11eb-9bed-2736aa710a48.png)

**Comment by jijopulikkottil** [comment] 2021-05-08 10:35
> mindLAMP is not collecting those multiple entry data that causes mismatch with steps in iOS.

@jeydude @avaidyam we didn't expect multiple entry at same time from same source.
We will have lot of duplicate entries If we support to collect those kind of multiple entries. I think we can eliminate it when query from database using unique timestamps. Please confirm to proceed.

**Comment by jijopulikkottil** [comment] 2021-05-08 10:54
> I am not getting some of the sensors value recently

@jeydude You mean, not getting the sensors lamp.gps, lamp.device_motion, lamp.accelerometer, lamp.sleep and lamp.activity_recognition. Hope you have added all these against the Study.

**Comment by avaidyam** [comment] 2021-05-08 11:41
@jijopulikkottil I think it's okay to collect duplicate timestamp entries. We want to basically clone the entire HealthKir database anyway.

**Comment by jeydude** [comment] 2021-05-10 13:31
Thanks @jijopulikkottil, I do have all those sensors added to the study. I was getting those sensor values before April 20. Only difference is
1. Applied latest image -  image: bidmcdigitalpsychiatry/lamp-server:2021 
2. Updated iOS mindLAMP app to latest beta version

We are getting those sensor values for android mindLAMP app (if we logout and login).

Can you check on your side if you are getting those sensors values with latest beta version of iOS mindLAMP app. Thanks!

**Comment by jeydude** [comment] 2021-05-11 13:48
@jijopulikkottil here are the sensors added to the patient profile, let me know if missed anything. Thanks!

![image](https://user-images.githubusercontent.com/841011/117826161-90f63f00-b235-11eb-99aa-dcd0742cb2de.png)

**Comment by jeydude** [comment] 2021-05-12 14:45
@saranya-sajeev, We are continue to see the mismatch in steps among Third party app, Google Fit and mindLAMP, not sure if you are having issue or not. Please let us know. Thanks!

@jijopulikkottil for iOS, with source data field in the JSON, the steps data looks accurate, sometimes we see mismatch in steps only if we get multiple entries for the same source at same interval like I have mentioned in the above thread.

**Comment by avaidyam** [comment] 2021-05-12 14:47
> for iOS, with source data field in the JSON, the steps data looks accurate, sometimes we see mismatch in steps only if we get multiple entries for the same source at same interval like I have mentioned in the above thread.
@jeydude This is expected behavior and you are required to filter by `source` on your end. 

> We are continue to see the mismatch in steps among Third party app, Google Fit and mindLAMP, not sure if you are having issue or not. 
@saranya-sajeev Are we receiving the `source` parameter for the Android code the same way as the iOS code?

**Comment by saranya-sajeev** [comment] 2021-05-12 15:28
Yes the source parameter is there in Android.

**Comment by saranya-sajeev** [comment] 2021-05-12 15:29
@jeydude let me check.

**Comment by jijopulikkottil** [comment] 2021-05-14 18:47
> @jijopulikkottil I think it's okay to collect duplicate timestamp entries. We want to basically clone the entire HealthKir database anyway.

With new logic, a (HealthKit) step data will have at least 2 duplicates, and it will have multiple duplicates if no new step data found for our every 5 minutes fetch. below is a sample response from sensor_event API

```
   {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
        {
            "sensor": "lamp.steps",
            "data": {
                "value": 12,
                "unit": "count",
                "source": "com.apple.health.BA2F6275-6CA9-4BC9-8990-D9BC027A3BAF"
            },
            "timestamp": 1620985340403
        },
```

@avaidyam The logic change we done is, earlier we do sample query from last record'd end-date, with new logic, we do query from last record's start-date. So we reduce the possibly of missing records. Hope this change will solve the mentioned issue.

**Comment by jijopulikkottil** [comment] 2021-05-17 11:14
We have done the above changes with latest build.

**Comment by avaidyam** [comment] 2021-05-17 14:46
@jijopulikkottil Do you think there's a way to reduce duplicates? This looks like a significant number of duplicates, not a small number.

**Comment by jijopulikkottil** [comment] 2021-05-17 15:09
maybe can we cache last record and skip for next fetch?

**Comment by avaidyam** [comment] 2021-05-17 15:12
I think that should work, as the assumption here is step count AND timestamp are identical.

**Comment by jijopulikkottil** [comment] 2021-05-17 17:18
I can make PR tomorrow.

**Comment by jeydude** [comment] 2021-05-18 13:33
@saranya-sajeev, were you able to see the mismatch between Google Fit and mindLAMP database in steps count. One of my colleague just used only Google Fit and mindLAMP during the weekend with his android phone, no wearables. He did not open the apps during the weekend and did not close/kill Google Fit/mindLAMP background service. Permissions were enabled.

According to Google Fit (with phone only)  4751 steps on Saturday-5/15, 7297 steps on Sunday 5/16. But in mindLAMP 553 Steps on Saturday, 604 steps on Sunday. Please let me know if you need anything else. Thanks!

**Comment by saranya-sajeev** [comment] 2021-05-18 13:37
Could you please check whether it is updated after killing and taking the app or after re-login?

**Comment by jeydude** [comment] 2021-05-18 13:44
One of my colleague is doing re-login to mindLAMP android app everyday to get the sleep data for about 2 weeks. Re-login helps to get yesterdays sleep data, other sensor data.  But it is NOT collecting any skipped/mismatched steps data.

**Comment by saranya-sajeev** [comment] 2021-05-18 14:12
Ok thank you Jey. I will check this issue.

**Comment by saranya-sajeev** [comment] 2021-05-27 06:20
Hi Jey,
Could you please check the sleep data and step count getting properly in the attached build?
[mindLamp05272021.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6551535/mindLamp05272021.zip)

**Comment by jeydude** [comment] 2021-05-27 13:53
Thanks @saranya-sajeev we will check and let you know. Thanks for the build.

**Comment by jeydude** [comment] 2021-05-28 13:27
@saranya-sajeev we are not getting any sensor values with 05272021 build. Do we have correct build? 2 of my colleagues installed on their android phones yesterday 05/27 around 9:32 am. Both of them are not getting any sensor values.
![image](https://user-images.githubusercontent.com/841011/119990935-87d3d480-bf8e-11eb-9a8d-e4de47204111.png)

**Comment by saranya-sajeev** [comment] 2021-05-28 14:48
Hi Jey,
Apk is working fine for me. Could you please share the log file?

**Comment by jeydude** [comment] 2021-05-28 15:11
![image](https://user-images.githubusercontent.com/841011/120005005-09326380-bf9d-11eb-8174-9cfc89109ff4.png)

**Comment by saranya-sajeev** [comment] 2021-05-31 13:17
Hi Jey,
Could you please install the attached apk and share the log file. I have added more logs in this apk to figure out the issue. [mindLamp05312021.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6570445/mindLamp05312021.zip)

**Comment by jeydude** [comment] 2021-06-01 15:08
Thanks @saranya-sajeev for the new build, is there any recommendation on how to use the android app, most of my colleagues they close the mindlamp app once they installed the APK file and all the permission is enabled, but they will leave the mindlamp data collection service running.

Do you want to us to leave the mindlamp android app open always? or open every hour or any other process or recommendation?

If you don't mind, can you share what kind of wearable you guys are using to test. We are using letscom veryfitpro app, needs manual sync with Google Fit.

**Comment by jeydude** [comment] 2021-06-01 16:27
@saranya-sajeev, Please find the log file after latest build APK install - [LampLog-06012021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6577720/LampLog-06012021.txt)

**Comment by saranya-sajeev** [comment] 2021-06-02 06:12
@jey are you getting the sensor values in the new build?

**Comment by jeydude** [comment] 2021-06-02 13:27
No sensor after the latest apk install.

**Comment by saranya-sajeev** [comment] 2021-06-02 14:17
Is app running in background or is it in killed state?

**Comment by jeydude** [comment] 2021-06-02 14:30
The mindLAMP data collection service is running all the time. But the mindLAMP android app may not be in running state all the time, we close the mindlamp app once we are done with taking surveys or learning resources. 

We also open the mindLAMP app in the morning and evening to sync the sensors data from veryfitpro/googlefit app with mindLAMP database.

Let us know if you have any recommendations.

**Comment by jeydude** [comment] 2021-06-02 17:42
@saranya-sajeev Every time if we logout and login then we get sensor data one-time, after that, new more new sensor data feed coming from mindLAMP app.

**Comment by jeydude** [comment] 2021-06-02 17:59
@saranya-sajeev Looks like you are detecting latest sensor data but may be not storing them into couchdb, please look at the log latest files.

Step count 695 and others was stored into couchdb after user logout and login back to the app at  10:36 am

Step count 1064 detected at 12:21 pm but never pushed to couchdb.

[LampLog-06022021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6586569/LampLog-06022021.txt)

**Comment by avaidyam** [comment] 2021-06-02 19:08
Hi @saranya-sajeev and @jeydude - it looks like there is really great diagnostics and troubleshooting going on here, but @saranya-sajeev could you work with @michaelmenon and the team to test a few internal releases to the level of quality @jeydude is looking for? Once that is prepared you can ping me/my team and we'll share our reports here too. I think that will streamline your efforts too, @jeydude. Thanks again.

**Comment by saranya-sajeev** [comment] 2021-06-03 06:22
@jey thanks for the latest log file. I will check and update you.

**Comment by jeydude** [comment] 2021-06-03 22:11
@saranya-sajeev,  we noticed with your latest android APK build we are getting cumulative value of steps instead of individual steps.

**Comment by saranya-sajeev** [comment] 2021-06-09 10:13
Hi Jey,

We have fixed both data sync issue and step count issue.

From Google fit, app can read daily step total and also step count within a time range.The daily total is computed from midnight of the current day on the device's current timezone.From our app we are reading the step count within a time range.

Here is how we are fetching step count from Google fit.
When the user logged in for the first time start time will be 1 and end time will be current time. So we will get step count till current time as a list and we will sync that data. We will keep the end time of most recent record in app. Next time onward we will fetch the data with start time as last saved time and end time as current time.Currently we are not fetching the daily step total.

Please check the attached build and let me know your comments.
[mindLamp06092021.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6622952/mindLamp06092021.zip)

Thanks

**Comment by jeydude** [comment] 2021-06-10 17:59
Thanks for new build @saranya-sajeev, we will check and let you know. Thanks!

**Comment by jeydude** [comment] 2021-06-10 21:44
Hi @saranya-sajeev,

Some of my colleagues tried your android build. Initially it updated the step could to match with Google Fit and VeryFitPro. After that it did not update the step count. 

I have attached their log file. Please look at it and let us know if we are missing anything. Thanks!
[LampLog-06102021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6634591/LampLog-06102021.txt)

**Comment by saranya-sajeev** [comment] 2021-06-11 11:39
1. Are you getting only initial step count? It seems that log file contains step counts. Are those values updated in DB?
2. Are you getting other sensor values?

**Comment by jeydude** [comment] 2021-06-11 16:54
Yes Saranya, we are seeing the proper step counts in the log file and log file steps are matching with GoogleFit step counts. But those steps data is not updated to CouchDB. 

Can you share the LAMP API that you are calling to store the sensor data into CouchDB, so I can make sure we have the API listed in our server.  (No data issues from testflight iOS mindLAMP app.)

Please check if you are calling LAMP  API to store the data after initial login and if there is any failure with API call, can you verify you are logging the exception in the log file. Thanks!

About other sensor values: Accelerometer data is coming in to CouchDB continuously if the application is open. Other sensor values we are not seeing them after initial login.

**Comment by jeydude** [comment] 2021-06-11 17:04
I am sharing one of my colleagues latest log file
[LampLog-06112021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6639991/LampLog-06112021.txt)
```
Here is his comment:
6/10/21 - Total is 2978 (Matches the step count from the log file starting with 888 value). For 6/11/21 - 775 matches with log file. except data is not in couchDB.
```

On June 10:
Google Fit count: 2978 
Log file count is : 2978 (888+793+807+490)
CouchDB count is: 888 

On June 11:
Google Fit count: 775 
Log file count is : 775 (220+335+220)
CouchDB count is: none

Either LAMP API is not called or there could be issue with storing data while calling LAMP API. 

Please let us know what else we can do to fix this issue. Thanks for your help!

**Comment by saranya-sajeev** [comment] 2021-06-14 06:22
@jeydude could you please share the device OS version and model?

**Comment by jeydude** [comment] 2021-06-14 16:29
@saranya-sajeev, please look at the attached screens contains OS version, model etc.
![Screenshot_20210614-111824_Settings](https://user-images.githubusercontent.com/841011/121926632-c3e39500-cd03-11eb-8fd6-09131219d1cb.png)
![Screenshot_20210614-112038_Settings](https://user-images.githubusercontent.com/841011/121926634-c3e39500-cd03-11eb-95b5-87417404c564.jpg)

**Comment by saranya-sajeev** [comment] 2021-06-15 10:19
Thank you @jeydude .

**Comment by saranya-sajeev** [comment] 2021-06-21 13:30
Hi Jey,
We have tested in our devices and we are not able to reproduce the issue here. So we need your help to figure out the issue.
Could you please install the attached apk and share the log file. I have added more logs in this apk. We have tested using following user and we are seeing data uploaded under these user.
User id:U0613654925@lamp.com

[mindLamp06212021.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6686835/mindLamp06212021.zip)

**Comment by jeydude** [comment] 2021-06-21 17:12
Thanks @saranya-sajeev, I have installed your latest APK and I tried with our server setup. I used only Google Fit Tracking to test this.

I see only Analytics and GPS data getting pushed to our API and Couch database. No other sensor data (Steps, HR etc)  getting pushed to our CouchDB.

Please see the attached log file

[LampLog_06212021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6688347/LampLog_06212021.txt)

**Comment by jeydude** [comment] 2021-06-21 17:21
I have tried mindLAMP app using U0613654925@lamp.com with your mindLAM API server as domain (not our API server),  all sensor data is getting pushed to your mindLAM API server and your database.

While comparing the two server log files I have noticed:
With your mindLAMP API Server, I see these logs in the android app:
```
21/6/2021 09:32:59: Google Fit Data : [{"data":{"source":"com.google.android.gms","steps":12,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979563E12},{"data":{"source":"com.google.android.gms","steps":6,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979567E12},{"data":{"source":"com.google.android.gms","type":"calories","unit":"kcal","value":0.028442765},"sensor":"lamp.nutrition","timestamp":1.624285979741E12}]
21/6/2021 09:32:59: CoroutineScope initialized getGoogleFitData
21/6/2021 09:32:59: **Google Fit Data 1**: [{"data":{"source":"com.google.android.gms","steps":12,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979563E12},{"data":{"source":"com.google.android.gms","steps":6,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979567E12},{"data":{"source":"com.google.android.gms","type":"calories","unit":"kcal","value":0.028442765},"sensor":"lamp.nutrition","timestamp":1.624285979741E12}]
21/6/2021 09:33:48: ScreenState Data : {"data":{"battery_level":30,"representation":"screen_on","value":0},"sensor":"lamp.screen_state","timestamp":1.624286028794E12}
21/6/2021 09:33:48: CoroutineScope initialized getScreenState
21/6/2021 09:33:48: **ScreenState Data 1**: {"data":{"battery_level":30,"representation":"screen_on","value":0},"sensor":"lamp.screen_state","timestamp":1.624286028794E12}


```

With our mindLAMP API Server, I see these logs in the android app:
```
21/6/2021 09:32:59: Google Fit Data : [{"data":{"source":"com.google.android.gms","steps":12,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979563E12},{"data":{"source":"com.google.android.gms","steps":6,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979567E12},{"data":{"source":"com.google.android.gms","type":"calories","unit":"kcal","value":0.028442765},"sensor":"lamp.nutrition","timestamp":1.624285979741E12}]
21/6/2021 09:32:59: CoroutineScope initialized getGoogleFitData
21/6/2021 09:32:59: Google Fit Data 1: [{"data":{"source":"com.google.android.gms","steps":12,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979563E12},{"data":{"source":"com.google.android.gms","steps":6,"type":"step_count_delta"},"sensor":"lamp.steps","timestamp":1.624285979567E12},{"data":{"source":"com.google.android.gms","type":"calories","unit":"kcal","value":0.028442765},"sensor":"lamp.nutrition","timestamp":1.624285979741E12}]
21/6/2021 11:55:25: ScreenState Data : {"data":{"battery_level":28,"representation":"screen_off","value":1},"sensor":"lamp.screen_state","timestamp":1.624294525254E12}

```

while pointing at our Domain API server, android log does not show
Google Fit Data 1 and ScreenState Data 1 log entries and no exception also.

Please let us know if you want us to try anything else. Thanks!

**Comment by jeydude** [comment] 2021-06-21 17:31
@saranya-sajeev Do you use the same API call for sending GPS and health data? if they are different APIs then let me know which API calls you are using for health data so I can confirm they are published in our API Server. Thanks!

**Comment by rvolety** [comment] 2021-06-21 19:19
@saranya-sajeev :
I also tested the latest .apk file on my Samsung Android phone. We are not seeing the Step count data in our Couch DB here.
Is it possible that we are using different APIs here? If you can send us the API you are using we an check with our Akana server here.

I attached my logfile here FYI.
[LampLog-Rama-06212021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6688985/LampLog-Rama-06212021.txt)

Thanks,
Rama Volety

**Comment by saranya-sajeev** [comment] 2021-06-22 10:36
@jeydude , @rvolety Could you please confirm that either you have added no sensors for the user or added all needed sensors. In Users->UpdateProfile.

**Comment by rvolety** [comment] 2021-06-22 12:03
Hi Saranya:

We did not add all the sensors. The following are added:

1. Heart rate 2. Sleep 3. Steps 4. Accelerometer 5. Analytics 6. GPS 7. Screen State and 8. Calls.

Thanks,
Rama Volety

Sent from Workspace ONE Boxer

On Jun 22, 2021 5:36 AM, saranya-sajeev ***@***.***> wrote:

@jeydude<https://github.com/jeydude> , @rvolety<https://github.com/rvolety> Could you please confirm that either you have added no sensors for the user or added all needed sensors. In Users->UpdateProfile.

**Comment by saranya-sajeev** [comment] 2021-06-22 12:06
Thanks Rama. Could you please confirm whether you are getting GPS data?

**Comment by rvolety** [comment] 2021-06-22 12:28
Yes. We are getting the GPS data.

Rama Volety | IT Lead Analyst/Programmer | Research Application Solutions Unit | Phone: 507-266-2781| Fax: 507-284-4585| ***@***.***
Mayo Clinic | 200 First Street S.W. | Rochester, MN 55905 | www.mayoclinic.org

From: saranya-sajeev ***@***.***>
Sent: Tuesday, June 22, 2021 7:06 AM
To: BIDMCDigitalPsychiatry/LAMP-platform ***@***.***>
Cc: Volety, Rama M. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [BIDMCDigitalPsychiatry/LAMP-platform] Mismatch in steps data with Android/iOS mindlamp app (#156)


Thanks Rama. Could you please confirm whether you are getting GPS data?

**Comment by jeydude** [comment] 2021-06-22 12:30
@saranya-sajeev We are getting GPS and Analytics data.

I can share one of the test patient account and login information to you to test with our domain server, can you send an email to jeydudue1@yahoo.com

**Comment by saranya-sajeev** [comment] 2021-06-22 12:30
ok thank you @rvolety

**Comment by saranya-sajeev** [comment] 2021-06-22 12:36
Ok Thank you @jeydude . I will send the mail.  We are using same api for sending GPS data and health data. But I have made some changes in writing GPS data to local DB. Shall I share one more build with same change in other sensors too to confirm ?

**Comment by jeydude** [comment] 2021-06-22 12:38
Sure Saranya. 

Please send an email to my yahoo id privately so I can share test account and domain URL so that you can debug more on your side. Thanks!

**Comment by saranya-sajeev** [comment] 2021-06-22 13:10
Hi ,
Please find the apk attached.
[mindLamp06222021.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6694398/mindLamp06222021.zip)

**Comment by rvolety** [comment] 2021-06-22 14:19
Hi Saranya:
Installed the new apk file. It looks like we have received the step count accurately for today (449).  Line 397 plus  line 560 in the attached log file. What we have seen in the past is that it only brings these values at the time of new install and brings no values there after. example : on 6/10/21 we installed new apk file and it brought the step count value of 888. After that no data was brought in until now. I hope and wish that is not the case going forward. We also see GPS data and other sensor data.
We will confirm if this is the case tomorrow.

Please note that there is an ongoing issue  between VeryFitPro and Google Fit. At this time only Stpe count data is being synced. No Sleep data or HR data is being sent from VeryFitPro. Therefore, GoogleFit is sending the last known values for these  every time when mindLAMP syncs data from Google Fit.

Thanks,
rvolety
[LampLog-Rama-06222021-B.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6695026/LampLog-Rama-06222021-B.txt)

**Comment by saranya-sajeev** [comment] 2021-06-22 14:58
> 
> 
> @saranya-sajeev, we will check the new build and let you know. Thanks!

Thank you jey

**Comment by saranya-sajeev** [comment] 2021-06-22 15:00
@rvolety thank you so much for the quick response.

**Comment by jeydude** [comment] 2021-06-22 23:07
@saranya-sajeev, we are getting steps data properly now and it is in sync with Google Fit. Thanks for making changes to the app.

Also noticed, followings are the sensor frequency updated with your new build
GPS data for every 10 seconds
Accelerometer data for every 3 seconds
Device motion data for every 1 second

Is it possible to control above frequency?

**Comment by saranya-sajeev** [comment] 2021-06-23 07:29
Could you please share the frequencies you have set? Maximum value for frequency that Android app can accept is 1.

**Comment by jeydude** [comment] 2021-06-23 13:17
Interesting, I have the frequency to 1 for GPS and Accelerometer, here is the output for 
https://{APIURL}/participant/{Particiapant ID}/sensor. Let me know if I am missing anything. Thanks!
```
{
  "data": [
    {
      "id": "a0dhh5wty34th4n17cew",
      "timestamp": 1616532925174,
      "spec": "lamp.analytics",
      "name": "analytics",
      "settings": {}
    },
    {
      "id": "mqppvpn4qwqmx1bx8wdm",
      "timestamp": 1616532945282,
      "spec": "lamp.heart_rate",
      "name": "HR",
      "settings": {}
    },
    {
      "id": "aqfb40nrnr5n035gqfqq",
      "timestamp": 1616532964156,
      "spec": "lamp.screen_state",
      "name": "Screen Status",
      "settings": {}
    },
    {
      "id": "mc4f1yd4sf3yvt4w4e2a",
      "timestamp": 1616532970516,
      "spec": "lamp.sleep",
      "name": "Sleep",
      "settings": {}
    },
    {
      "id": "t928ka5nc4fv9g60r0wp",
      "timestamp": 1616532976301,
      "spec": "lamp.steps",
      "name": "steps",
      "settings": {}
    },
    {
      "id": "wvcarrj57jedaje8sa2x",
      "timestamp": 1616532981861,
      "spec": "lamp.telephony",
      "name": "calls",
      "settings": {}
    },
    {
      "id": "3ewpt11q4y656pgwxj8j",
      "timestamp": 1623077614569,
      "spec": "lamp.accelerometer",
      "name": "Accelerometer",
      "settings": {
        "frequency": 1
      }
    },
    {
      "id": "5pb6j7e88amnvwrzph72",
      "timestamp": 1623077622389,
      "spec": "lamp.gps",
      "name": "GPS",
      "settings": {
        "frequency": 1
      }
    }
  ]
}
```

Here is most  recent accelerometer data 
```
  {
"timestamp": 1624453499846,
"sensor": "lamp.accelerometer",
"data": {
"motion": {
"x": -0.44781622290611267,
"y": -0.3024943768978119,
"z": 9.574481010437012
}
}
},
  {
"timestamp": 1624453496768,
"sensor": "lamp.accelerometer",
"data": {
"motion": {
"x": -0.44709792733192444,
"y": -0.302853524684906,
"z": 9.574361801147461
}
}
}
```

here is most recent GPS data
```
  {
"timestamp": 1624424317830,
"sensor": "lamp.gps",
"data": {
"accuracy": 9.194,
"altitude": 303.65489616068413,
"latitude": 44.0860459,
"longitude": -92.5309438
}
},
  {
"timestamp": 1624424317823,
"sensor": "lamp.gps",
"data": {
"accuracy": 9.194,
"altitude": 303.65489616068413,
"latitude": 44.0860459,
"longitude": -92.5309438
}
}
```

**Comment by jeydude** [comment] 2021-06-23 13:41
Yes Saranya, we are getting all the sensors data now. Thanks!

**Comment by saranya-sajeev** [comment] 2021-06-23 13:43
Ok Thank you Jey.

**Comment by saranya-sajeev** [comment] 2021-06-25 14:17
Hi Jey,
Default frequency is Android is 0.33 (3 seconds). When I have checked GPS and Accelerometer with frequency 1  it is working fine.
Accelerometer Data
```
{
      "data": {
        "motion": {
          "x": 0.03799999877810478,
          "y": 0.6890000104904175,
          "z": 9.574000358581543
        }
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1624630033765
    },
    {
      "data": {
        "motion": {
          "x": 0.07599999755620956,
          "y": 0.6890000104904175,
          "z": 9.574000358581543
        }
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1624630032760
    },
```
GPS Data

```
{
      "data": {
        "accuracy": 1437,
        "altitude": 11.231366623961751,
        "latitude": 10.1745923,
        "longitude": 76.2261063
      },
      "sensor": "lamp.gps",
      "timestamp": 1624630049381
    },{
      "data": {
        "accuracy": 1437,
        "altitude": 11.231366623961751,
        "latitude": 10.1745923,
        "longitude": 76.2261063
      },
      "sensor": "lamp.gps",
      "timestamp": 1624630048212
    }
```

**Closed** 2021-09-10 15:10 UTC
Labels: bug, NO ETA, native core
