### ISSUE TITLE
Screen Resolution Error

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#301] opened 2021-06-18 14:49 UTC
> The screen is not fully visible on the iPhone (the next button is cut off and requires to be scrolled down, but when you scroll up, you have to scroll up in the middle after scrolling down on the bottom to make sure nothing is cut off)
>![image](https://user-images.githubusercontent.com/82968538/122578797-dcacbd00-d019-11eb-98d7-c7ca624cc917.png)
>![image](https://user-images.githubusercontent.com/82968538/122578830-e33b3480-d019-11eb-9a64-4348b3ee97cb.png)

**Comment by avaidyam** [comment] 2022-02-11 21:09
@sarithapillai8 This issue appears to be occurring again according to @tlakhtak:
> For all the games, I saw a scrollbar. Only for Jewels A and B this was an issue as the ‘starting jewel’ indication was only visible upon scrolling.
> Furthermore, jewels are not always responsive to touch and need to be tapped more than once sometimes to get the app to respond.

**Comment by sarithapillai8** [comment] 2022-02-14 09:19
@avaidyam The issue with scrolling seems to be appearing because of the status bar in the top. With Android/web, the screen fits to the height. Can we change it like hiding status bar on iOS? I am asking this because, we are seeing some weird screen while scrolling. Please see the top portion :
![D9025BB4-D2A1-4D36-93C4-6620D3AEDD29](https://user-images.githubusercontent.com/63710347/153835215-b9b7a875-99b7-45ed-a986-2983951f9dc6.png)

>Furthermore, jewels are not always responsive to touch and need to be tapped more than once sometimes to get the app to respond.

We are not able to reproduce this. Can we get any scenario or device information?

>The font for the Back button on surveys (to go back to a previous question) is in some Serif font, not consistent with the rest of LAMP.

Fixed in staging.

**Comment by jijopulikkottil** [comment] 2022-02-14 16:16
@avaidyam  I can work with @sarithapillai8 to try some workarounds.

**Comment by jijopulikkottil** [comment] 2022-02-22 16:43
Thanks @sarithapillai8 for posting the above [screenshot](
![](https://user-images.githubusercontent.com/63710347/153835215-b9b7a875-99b7-45ed-a986-2983951f9dc6.png)
) to identify the issue. It has been fixed on app side by setting the web view constraint with respect to safe area layout.

![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 21 41 41](https://user-images.githubusercontent.com/63795052/155178158-5e24541c-7f0c-4617-aa33-0a19d8a8c042.png)

**Comment by jijopulikkottil** [comment] 2022-02-23 17:10
@avaidyam  in iPhone XR, we found no issues. 
But on iPhone13 (simulator) some activity pages [see 'Balloon Risk'] not fit well. [but  Jewels looks fine] 


![Simulator Screen Shot - iPhone 13 - 2022-02-23 at 21 56 52](https://user-images.githubusercontent.com/63795052/155369581-9e036648-1301-40d7-9c3d-29755481bc1e.png)

![Simulator Screen Shot - iPhone 13 - 2022-02-23 at 22 37 09](https://user-images.githubusercontent.com/63795052/155370328-43343d39-cae4-4ec3-b85b-a4995dc5a810.png)

**Comment by avaidyam** [comment] 2022-02-23 18:31
@jijopulikkottil Thanks for sharing this. I'll reopen the issue as this means we're not actually fixing the underlying problem. @sarithapillai8 Can you double check **all the activity code** to confirm we're **NOT hardcoding ANY constants such as screen width and height anywhere?**

**Comment by sarithapillai8** [comment] 2022-02-24 05:23
@avaidyam I can check and let you know once I am done with #442.

**Comment by jijopulikkottil** [comment] 2022-03-21 02:16
@sarithapillai8, @divyav2020 When we tested, the `Balloon` activity [issue](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/301#issuecomment-1049010014) is fixed. [against staging server].

**Comment by divyav2020** [comment] 2022-03-21 12:46
Checking the following issues in android build

**Comment by divyav2020** [comment] 2022-03-21 12:47
Checking the above issues in android build

**Comment by divyav2020** [comment] 2022-03-22 12:44
This issue is fixed in iOS and Android

**Closed** 2022-03-22 13:00 UTC
Labels: bug, 5day, native core, frontend, priority LOW

**Comment by tlakhtak** [comment] 2022-04-15 20:24
This appears fixed.
