### ISSUE TITLE
Trails Task Appearance Issue - Android Phone

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#741] opened 2023-03-09 16:06 UTC
On the trails trask (A and B) a participant is reporting being unable to complete the task as some of the Jewels are not appearing in the field of view, as described here:

https://mindlamp.discourse.group/t/jewels-appearing-outside-the-phones-field-of-view/761/2

This participant was using Motorola Z2 phone.

**Comment by ZCOEngineer** [comment] 2023-03-10 03:14
@carlan1 we shall check this

**Comment by ZCOEngineer** [comment] 2023-03-15 10:41
@carlan1 https://mindlamp.discourse.group/t/jewels-appearing-outside-the-phones-field-of-view/761/2 
When we try to access it says the page is private. Could you provide the details here with screenshots if possible?

**Comment by sarithapillai8** [comment] 2023-03-15 12:22
@carlan1 the attached image is not accessible to us.
![image](https://user-images.githubusercontent.com/63710347/225307573-8e1cbd2b-966a-4f85-9576-3b4d02e78bfd.png)

**Comment by ZCOEngineer** [comment] 2023-03-22 02:35
thanks @carlan1. 
We shall check in device closer to Motorola Z2 in specs. Shall update you the findings.

**Comment by divyav2020** [comment] 2023-03-22 10:24
We have tested the issue in devices like Device : 

Moto g60  Android version 12
Moto g 5G   Android version 11
Google Pixel 4 XL (Unlocked) (Android version 10)
Google Pixel 7 Pro  (Android versionOS 13)
Samsung Galaxy A13 5G (Android version 11)
OnePlus 8T  (Android version 11)
Galaxy M31 (Android version 12)
Galaxy F12 (Android version 13)
and 
Realme Narzo (version 11)

We couldn't reproduce the issue in these devices. We will check some more device and try to reproduce the same

**Comment by ZCOEngineer** [comment] 2023-03-29 07:02
@carlan1 we tried on different android flavors while starting a call during a game or starting a screen recording during a game but could not reproduce, any chance we can check on that participant phone one time?

**Comment by ZCOEngineer** [comment] 2023-03-29 13:47
we shall wait for screenshots on this from @carlan1 and then will check more on this

**Comment by carlan1** [comment] 2023-03-31 13:08
Attached are two screenshots of the issue provided by the participant.

![JewelsTest_Issue1](https://user-images.githubusercontent.com/103652751/229128359-b6aad413-9da3-4201-bd14-fbb5b97be8b9.jpg)
![JewelsTest_Issue2](https://user-images.githubusercontent.com/103652751/229128366-06f29401-a13f-4cb9-b774-0ac13d9663e7.jpg)

**Comment by ZCOEngineer** [comment] 2023-04-05 08:50
@carlan1 we got the issue similar to one attached in the images in one of our test devices. we are working on a fix for this.

**Comment by ZCOEngineer** [comment] 2023-04-19 05:54
@carlan1 we are currently working on this, shall provide an update by this week

**Closed** 2023-05-01 18:18 UTC
Labels: bug, 2day, frontend, priority MEDIUM
