### ISSUE TITLE
Uncaught Exception Error

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#648] opened 2022-06-03 19:31 UTC
**Describe the bug**
User U7851221787 on android device LG K30 experienced random 'Uncaught Exception' error. Restarting the app removes the error. 

**Additional context**
Similar error in issue #645 

**Screenshots**
![Screenshot_20220429-191357](https://user-images.githubusercontent.com/103677721/171936649-e1cf9909-9cf8-4471-8782-765823ba4359.png)

**Smartphone (please complete the following information):**
 - Device: LG K30

**Comment by saranya-sajeev** [comment] 2022-06-08 05:34
@Devayani0102 We have already fixed this issue and is available in beta build. Could please check the beta build?

**Comment by saranya-sajeev** [comment] 2022-06-13 07:04
@Devayani0102 We will test here and update you.

**Comment by divyav2020** [comment] 2022-06-13 11:22
We have checked this issue in latest Beta build and we couldn't reproduce it.

**Comment by ZCOEngineer** [comment] 2022-06-13 12:19
We shall check more in detail and update

**Comment by michaelmenon** [comment] 2022-06-13 12:21
This seems to be fixed in beta. it should get resolved once we push beta to production.

**Comment by ZCOEngineer** [comment] 2022-06-13 13:06
This issue appears same as #645 , as that was handled and pushed to beta please test this on current beta android version.

**Comment by ZCOEngineer** [comment] 2022-06-20 03:13
We got this exception once last day. we have updated the library for google fit and given for testing. shall update beta if we does not get this exception.

**Comment by saranya-sajeev** [comment] 2022-06-21 13:07
@avaidyam Invalid end time issue not got reproduced after library update so we have pushed the code to beta and is in review status.

**Comment by avaidyam** [comment] 2022-07-11 13:47
@Devayani0102 If you feel the participant is willing to test the staging build then they may do so and provide feedback, but otherwise you will need to wait for this fix to reach production status before the issue is resolved for the participant. 

The GitHub issue will be closed as the issue is resolved in staging and can be reopened if you or others test staging and still encounter the issue.

**Comment by ertjlane** [comment] 2022-10-14 15:47
We've recently had two users experience this same issue. For one the issue would arise spontaneously, and does not pop up specifically when opening mindLAMP but opens spontaneously. 

Samsung Galaxy S21 and Samsung Galaxy S8+ (android version 9). 
![Screenshot_20221009-223156_mindLAMP](https://user-images.githubusercontent.com/104088715/195887922-104a2290-d3d9-46c5-8c98-798d16ec5bb9.jpg)

**Comment by zcobacktrackview** [comment] 2022-10-17 06:04
@ertjlane are they using production build or beta?

**Comment by ertjlane** [comment] 2022-10-17 14:06
Production!

**Comment by divyav2020** [comment] 2022-10-17 15:08
Could you please check this in beta build? Currently this change is not updated in production

 We are also trying to reproduce this issue in current beta build.

**Comment by avaidyam** [comment] 2022-10-17 16:15
@divyav2020 This should have been released to production already. @saranya-sajeev @michaelmenon Can you check on/confirm what happened to the build?

**Comment by ZCOEngineer** [comment] 2022-10-18 06:36
@avaidyam we had informed @carlan1 to move android to production from beta [.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/692#issuecomment-1251893603) 

Currently when release is created production pointed build is pushed to beta. We believe last time you moved it to production.

**Comment by ZCOEngineer** [comment] 2022-10-18 06:36
@avaidyam we had informed @carlan1 to move android to production from beta [.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/692#issuecomment-1251893603) 

Currently when release is created production pointed build is pushed to beta. We believe last time you moved it to production.

**Comment by michaelmenon** [comment] 2022-10-18 11:07
Hi @avaidyam , I think once we move to beta your team tests the beta and then move that to production. I will confirm with @carlan1 in our call this week to move this to production.

**Comment by avaidyam** [comment] 2022-10-19 13:21
@michaelmenon Thanks for the clarification, we’ll make sure to do that ASAP.

**Comment by carlan1** [comment] 2022-10-19 14:34
Android release has been made and is in review.

**Closed by carlan1** 2022-10-19 14:34 UTC
Labels: bug, 1day, native core, priority HIGH, in progress
