### ISSUE TITLE
mindLAMP Opens Blank

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#651] opened 2022-06-10 20:46 UTC
**Describe the bug**
When opened from the home screen mindLAMP comes up with a perfectly blank screen. The app will reopen to the assessment screen when closed and opened again.

**To Reproduce**
See video included.

**Screenshots**

https://user-images.githubusercontent.com/104088715/173146591-695e6699-8a39-40c5-b173-0ad01f6c9c6e.mov

**Smartphone (please complete the following information):**
 - Device: [iPhone8]
 - OS: [iOS 15.5] (based on google of iphone 8 current OS), not user report
 - Version [14.8]

**Comment by ZCOEngineer** [comment] 2022-06-13 04:55
We shall check this and update our findings.

**Comment by jijopulikkottil** [comment] 2022-06-13 11:23
We are able to reproduce the blank-white screen with unstable internet connectivity!.
[But it is not receiving on web view Fail callbacks.]

**Comment by jijopulikkottil** [comment] 2022-06-13 13:15
We can monitor the connectivity and can try to show warning/alert with retry option.

**Comment by jijopulikkottil** [comment] 2022-06-20 05:47
As we are getting WebView's `didConnect` delegate in both (blank-white and home page) scenarios, we inject a script to check the count of <div> elements and will consider the page is properly loaded only if the div-count is nonzero or the login event.

**Comment by jijopulikkottil** [comment] 2022-07-07 07:56
This fix is available on latest test flight build.

**Comment by jijopulikkottil** [comment] 2022-08-01 12:23
Due to the script injection, the app [load time increases.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/670) So we can remove it and do another workaround to fix this issue. We can try to invoke a javascript function from WebView's didConnect delegate and can check the response to determine it is loaded or not!

**Comment by jijopulikkottil** [comment] 2022-08-04 16:08
As the issue mentioned in #670 is not related to script injection, we are closing this.

**Closed by jijopulikkottil** 2022-08-04 16:08 UTC
Labels: bug, 2day, native core, priority HIGH
