### ISSUE TITLE
Photos in Learn don't show up after you've uploaded them

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#177] opened 2021-04-21 18:14 UTC
> Unable to add photos to Learn section. I can upload them, but they will not show when I go to patient view
![image](https://user-images.githubusercontent.com/82968538/115601451-d5806180-a2ab-11eb-9a74-3f386c3e7e64.png)

**Comment by avaidyam** [comment] 2021-05-21 15:36
Duplicate of #170!

**Closed by avaidyam** 2021-05-21 15:36 UTC
Labels: bug, duplicate, frontend
