### ISSUE TITLE
Icons for surveys show up in "Assess" but not in the Feed

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#192] opened 2021-04-21 18:49 UTC
> icon shows up under assess but not when task is assigned in feed
![image](https://user-images.githubusercontent.com/82968538/115605639-be903e00-a2b0-11eb-8cd1-f551f48aaaae.png)
![image](https://user-images.githubusercontent.com/82968538/115605646-c223c500-a2b0-11eb-92cf-793052b7639f.png)

**Comment by avaidyam** [comment] 2021-05-21 15:48
Duplicate of #170!

**Closed by avaidyam** 2021-05-21 15:48 UTC
Labels: bug, duplicate, frontend
