### ISSUE TITLE
Jewels A and B not opening. Blue screen visible

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#244] opened 2021-05-06 12:24 UTC
> Jewels A and B not opening. Blue screen visible
![image](https://user-images.githubusercontent.com/82968538/117297617-70e50b00-ae44-11eb-80ee-a0baa130f1a6.png)

**Comment by avaidyam** [comment] 2021-05-21 17:32
Resolved; possible duplicate of #96.

**Closed by avaidyam** 2021-05-21 17:32 UTC
Labels: bug, frontend
