### ISSUE TITLE
Hide Specific Surveys from Patients

### ISSUE THREAD

**Issue by rbilden** [BIDMCDigitalPsychiatry/LAMP-platform#137] opened 2021-03-16 13:25 UTC
> **MAPNET**: The QR code and link bring the client directly to the "assess" section and they can see all content including the sections usually completed by the clinician. Instead, clients should be directly brought to specific questionnaires only.

**Comment by avaidyam** [comment] 2021-05-21 15:25
Duplicate of #165!

**Closed by avaidyam** 2021-05-21 15:25 UTC
Labels: NO ETA, feature, frontend, on hold
