### ISSUE TITLE
API Server crashes when NATS fails

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#75] opened 2020-12-22 15:43 UTC
The server should handle this gracefully instead of hard-crashing.

```
NatsError: Could not connect to server: Error: read ECONNRESET
--
at Object.handlers.error (/usr/src/app/node_modules/src/protocolhandler.ts:472:43)
at Socket.<anonymous> (/usr/src/app/node_modules/src/tcptransport.ts:87:35)
at Socket.emit (events.js:315:20)
at Socket.EventEmitter.emit (domain.js:467:12)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This also causes the App Gateway to crash too, which needs to be handled gracefully as well:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: read ECONNRESET)
    at ClientHttp2Session.destroy (internal/http2/core.js:1335:20)
    at TLSSocket.socketOnError (internal/http2/core.js:2727:13)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Linoy339** [comment] 2020-12-22 18:02
1.NatsError: Could not connect to server: Error: read ECONNRESET:
Could you please tell scenario how  the error got originated? Is it causing the server to crash?

2. On app-gateway part, Is it for APNSpush?

**Comment by avaidyam** [comment] 2020-12-22 18:28
1. The NATS server itself crashed because of a “too many open files” error that I believe is just a configuration thing that can be fixed later. Then, the API server crashed because the TCP socket closed.
2. I believe this is `APNSpush` but it could also be `GCMpush` — but you added the correct error checking so I am not sure how/why it’s crashing (it specifically says `HTTP2` in the error code so perhaps you need to catch it inside of the functions too?).

**Comment by Linoy339** [comment] 2020-12-22 19:15
@avaidyam 
1. Is there a way to recreate it? 
2. I think, we have to fix APNSPUSH as we did for GCMPUSH. I'll check it

**Comment by avaidyam** [comment] 2020-12-22 19:19
Try to kill the NATS server after the API server has connected to it and it'll also crash.

**Comment by Linoy339** [comment] 2020-12-27 13:15
1. Killing nats server couldn't reproduce the issue. If we kill nats server, an error occured which is as follows:
"TypeError: Cannot read property 'publish' of undefined". This is because the nats is offline. But, this won't cause a server crash.

2. We couldn't reproduce the issue. But, as the changes which we did for GCMpush was not included in APNSPush,  We have proposed a fix in app gateway. Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/compare/master...Linoy339:patch-5](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/compare/master...Linoy339:patch-5)

**Comment by avaidyam** [comment] 2020-12-28 17:57
Can you catch and handle the error? It is not good practice to let errors go uncaught. Instead you could just console log that the NATS server was disconnected.

**Comment by Linoy339** [comment] 2020-12-31 05:41
@avaidyam . Its handled with the message - "NATS server is  disconnected"

**Comment by avaidyam** [comment] 2021-01-12 18:39
@Linoy339 It appears that this issue has not been resolved yet; can you check the logs on AWS and see why it continues to crash?

**Comment by avaidyam** [comment] 2021-01-14 13:39
@Linoy339 Here's the new crash: 
```
NatsError: 'Maximum Payload Violation'
at Function.toError (/usr/src/app/node_modules/src/protocolhandler.ts:968:20)
at ProtocolHandler.processErr (/usr/src/app/node_modules/src/protocolhandler.ts:980:35)
at ProtocolHandler.processInbound (/usr/src/app/node_modules/src/protocolhandler.ts:634:34)
at Object.handlers.data (/usr/src/app/node_modules/src/protocolhandler.ts:484:18)
at Socket.<anonymous> (/usr/src/app/node_modules/src/tcptransport.ts:99:31)
at Socket.emit (events.js:315:20)
at Socket.EventEmitter.emit (domain.js:467:12)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at Socket.Readable.push (internal/streams/readable.js:223:10)
```

**Comment by Linoy339** [comment] 2021-01-14 13:55
@avaidyam .I'll check and let you know

**Comment by Linoy339** [comment] 2021-01-15 12:39
@avaidyam . Nats comes with default maximum payload size as 1 MB(=1048576 bytes). So whenever, an image or video comes as attachment in some api, it would results in this error. 
What we can do is :
1)We can configure server to hold atleast 10 MB. This , we can do it with a config file. Create a config.json file with content as {max_payload:10485760} (which means it can accept 10 mb) and start the nats-server using the command: nats-server --config /path/to/`config.json`
This makes nats to receive payload more than 1 MB and not more than 10 MB.

2)Inorder to prevent the worse condition, we can place a variable in env (NATS_PAYLOAD_SIZE =10485760). Now, we can check the incoming payload size against NATS_PAYLOAD_SIZE  in env and bypass the nats maximum payload error, which means before nats gets the content, we can console the error, so that the crash won't happen.

**Comment by Linoy339** [comment] 2021-01-21 12:39
@avaidyam . Please increase the maximum payload size in nats  server  as said in the above.
We have fixed by checking against the max payload size of nats server.  For this, a variable NATS_PAYLOAD_SIZE has been kept in env. Please put the maximum payload size which the nats server accepts

If the maximum payload size in nats is increased to 10 MB, then the NATS_PAYLOAD_SIZE in env should be 10485760 (1048576*10).
Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/44](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/44)

**Comment by avaidyam** [comment] 2021-01-21 16:27
Instead of just erroring out in the condition where the payload is greater than the maximum size, I recall that @michaelmenon had suggested to just submit the object's ID to NATS and instead retrieve the object from the database (using the repository functions) at the listener-side. Could you update your implementation in that PR to match this strategy?

**Comment by Linoy339** [comment] 2021-01-21 16:47
@avaidyam Yes. We were testing it. We can push that too by tomorrow

**Comment by avaidyam** [comment] 2021-02-02 20:14
@Linoy339 Is there an update on this? You mentioned it would be pushed out ~11 days ago.

**Comment by Linoy339** [comment] 2021-02-03 04:49
@avaidyam . We were testing and got some issues. In between, Mongodb change task and api optimization came in priority. 
We will fix it soon and push it by monday.

**Comment by Linoy339** [comment] 2021-02-08 09:52
Hi @avaidyam . Please find :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/50](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/50)
Please put the following variable in env:
NATS_PAYLOAD_SIZE ={keep the max payload size of nats server here }

Nats server payload size can be increased with the following steps
1.Set Nats server to accept more data. Make a config file (eg : nats_conf1_1.json) with content as {max_payload:10485760}. (10MB)
We have set with our docker image by running following commands: 
a)docker run -p 4222:4222 -d --restart unless-stopped nats  -c nats_conf1_1.json
An output is received from above command. eg: 656573e3eff2f1033d60sdasfasdfasdasdasd
b)docker images.
This will container id (eg:656573e3eff2)
c)docker start 656573e3eff2

**Closed** 2021-02-09 14:20 UTC
Labels: 4day, NO ETA, backend, bug
