### ISSUE TITLE
DBT Bug: Portal display error

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#466] opened 2022-01-10 21:04 UTC
Another calendar/time-related issue. On Portal page, observed for the diary card output, when a graph is displaying a range of time (1/4-1/10, for example), the actual graph display shows a range starting and ending one day earlier than the range selected(1/3-1/9) on the x-axis.

**Comment by tlakhtak** [comment] 2022-01-11 15:17
Another Portal timing issue - it appears as though the data is not populating correctly, and showing inaccurate timelines of 52 years ago for recently collected data.
![Timing Issue in Graph](https://user-images.githubusercontent.com/82968538/148969498-b2210420-df1f-4adb-840e-7dc07a177e1e.png)

**Comment by sarithapillai8** [comment] 2022-01-24 09:04
Could you share the credentials for checking this?

**Comment by tlakhtak** [comment] 2022-01-24 14:37
api.lamp.digital, testtanvi@lamp.com, test3

**Comment by sarithapillai8** [comment] 2022-01-25 08:48
@tlakhtak Can we get the details of U4785505885 for checking the issue with portal page - "52 years ago"?

**Comment by avaidyam** [comment] 2022-01-25 13:49
@sarithapillai8 I believe that's what the provided credentials are for.

**Comment by tlakhtak** [comment] 2022-01-26 17:18
Updates on this bug: This error is seen on both our server and LAC server, and the problem seems to go beyond just the visualization being one day off from the range. This is happening for all the plots on the DBT card, making it seems as thought the visualizations are not rendering until a day after they are entered. Here, you see that entries made on January 26th do not appear to be reflected as such.

![image](https://user-images.githubusercontent.com/82968538/151211965-1f1b2841-186e-4f9d-b4b1-b1059930039d.png)
![image](https://user-images.githubusercontent.com/82968538/151212007-8b2b2cd9-294d-4aa5-bd8c-82622987f866.png)
![image](https://user-images.githubusercontent.com/82968538/151212766-183c5cb5-d867-4689-8279-e3f89700a1b0.png)
![image](https://user-images.githubusercontent.com/82968538/151212784-e690bf33-868f-45f2-800f-cfb1cfef6dbb.png)
![image](https://user-images.githubusercontent.com/82968538/151212802-985120da-e36f-4232-bdb6-5895b40a25b0.png)

![image](https://user-images.githubusercontent.com/82968538/151212955-861e0a65-e585-4eac-95d0-858eb4c37a8a.png)
![image](https://user-images.githubusercontent.com/82968538/151213139-576c17c6-8b9d-4e46-a95b-98d06d1a8e8a.png)

**Comment by sarithapillai8** [comment] 2022-01-27 05:33
@avaidyam The given credentials not showing the data with '52 years ago'.
@tlakhtak We are working on this. We will update soon.

**Comment by divyav2020** [comment] 2022-01-31 06:05
We are unable to reproduce this issue. Could please check whether the issue still shows in dashboard- staging?
To check this specific issue could you please provide the participant credentials ?

**Comment by sarithapillai8** [comment] 2022-02-01 02:34
@tlakhtak The credentials are not working. Could you recheck? let me know the server address used.

**Comment by tlakhtak** [comment] 2022-02-01 13:29
We are using the api-staging server for this.

**Comment by sarithapillai8** [comment] 2022-02-01 13:42
@tlakhtak 
We are not able to login with these details. Could you recheck?

**Comment by tlakhtak** [comment] 2022-02-01 13:49
Apologies - can you retry with U4319433467@lamp.com, pass: U4319433467, domain: api-staging.lamp.digital

**Comment by sarithapillai8** [comment] 2022-02-01 14:17
@tlakhtak This seems fixed.
![image](https://user-images.githubusercontent.com/63710347/151984407-2c189a81-22a9-417f-a280-9a9ea66788c9.png)
@avaidyam This is already fixed with #444 in dashboard-staging. If possible can you move this to production with other changes?

**Comment by avaidyam** [comment] 2022-02-01 14:21
@sarithapillai8 I can mark this issue closed if @tlakhtak confirms that it's resolved for her.

**Comment by sarithapillai8** [comment] 2022-02-01 14:25
@avaidyam I believe @tlakhtak is checking production where the fixes are not updated.

**Comment by ZCOEngineer** [comment] 2022-02-07 14:24
@avaidyam, @tlakhtak could you check this?

**Comment by tlakhtak** [comment] 2022-02-07 14:35
Apologies - timezone is in Eastern Standard Time, and we are also observing this in Pacific Standard Time.

**Comment by avaidyam** [comment] 2022-02-11 21:22
> @tlakhtak: It seems like when you respond to the DBT once, for some of the graphs it doesn’t show any points or markers on the plot, but it does add a legend for the specific behaviors that were added.
> @akmeyer3: I replicated this issue as well in terms of markers not showing up but legend being added. Points will show up only on some of the graphs, if not only one of them, if you respond more than once.

@sarithapillai8 It looks like there's a remaining minor issue with the graphs. Could you take a look at that and resolve it if it's a simple fix?

**Comment by sarithapillai8** [comment] 2022-02-13 04:59
@avaidyam 
This is a known issue and it was said to leave it a it is ad lines cannot be drawn with single point and our graph design was not with marks. So can I point marks on graph to  fix this issue? It will look like below :
![image](https://user-images.githubusercontent.com/63710347/153739316-40f9bb15-dc6a-4cd8-b0b1-70ec862fca51.png)
![image](https://user-images.githubusercontent.com/63710347/153739376-ae9ceca2-8f6b-4d57-a579-5c942184127c.png)

**Comment by avaidyam** [comment] 2022-02-14 15:43
@sarithapillai8 I agree, it's not possible to draw a line, so your suggestion makes more sense as this is likely what our collaborators want. Please implement that!

**Comment by sarithapillai8** [comment] 2022-02-15 10:50
@avaidyam 
These changes are updated in dashboard staging, which are already available on production.

**Closed** 2022-02-15 13:57 UTC
Labels: bug, 2day, frontend, priority HIGH
