### ISSUE TITLE
Spinning wheel when loading schedules

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#625] opened 2022-04-26 13:25 UTC
A collaborator reports:

In attempting to confirm the survey schedule for an active participant (by clicking on the gear icon next to the participant ID), I’m encountering a white spinning wheel that is not resolving.

This is happening on multiple browsers, for all participants and persists after clearing the cache.

EDIT by @avaidyam: [The original forum thread can be found here.](https://mindlamp.discourse.group/t/spinning-wheel-on-participant-activity-configuration-within-researcher-portal/603/20)

**Comment by lukeoftheshire** [comment] 2022-04-26 17:51
More info:

As for the activities, we have configured 7 separate studies that have a different combination of scheduled surveys (7:30pm or 9pm each night), +/- sensors, “informant” vs. “participant”, and pilot testing. But the only activity schedule we are running is a nightly 5-question survey. I can confirm that I’m seeing the spinning wheel for each participant, and also when I click on the “activities” tab to the left (but not when I’m in the general users, sensors, studies, or data portal tabs). The start dates vary by the study - some date back to 2021, and others were created more recently (April 2022).

**Comment by sarithapillai8** [comment] 2022-04-28 10:34
@lukeoftheshire 
Is the loading spin appears both on the activities tab and on opening participant settings page? Can we get any video recording of the issue?

**Comment by lukeoftheshire** [comment] 2022-05-03 14:22
Hi @sarithapillai8 yes, the spinning wheel is appearing for particpants and the activities tab.

I will try to get a video recording.

**Comment by ZCOEngineer** [comment] 2022-05-09 11:44
Hi @lukeoftheshire , @avaidyam we were not able to reproduce this issue

**Comment by lukeoftheshire** [comment] 2022-05-09 15:50
Hi @ZCOEngineer the user sent along this video in question of the issue occuring.

They have the console open but I don't see any (relevant) errors:

https://user-images.githubusercontent.com/34659264/167448003-c3257b44-6003-445e-946a-0dfd75a57c38.mov

**Comment by sarithapillai8** [comment] 2022-05-10 12:50
@lukeoftheshire We are not yet able to reproduce this kind of issue in our test studies. I don't think it is related to activity schedules, but because of some old invalid data or something. Can we get the whole activity data to reproduce?

**Comment by ertjlane** [comment] 2022-06-24 17:27
Hello all, I'm going to be taking Luke's place as the point person for this issue! As an update, we've just had someone else on a team we're working with bring up the same problem. They report spinning wheel when they click on the activity tab, in their MGB mind lamp instance on AWS. They can open other tabs like users, sensors, and data portal. I've included a screenshot. I'm moving this issue to high priority and urgent, as this is affecting key members of a team we are working with. @michaelmenon What do you mean by 'send the whole activity data'? 

![fea6b361a6a8d1e51227b877eaee8c9dc16b44c0_2_1035x405](https://user-images.githubusercontent.com/104088715/175612069-aa1b7f27-6882-4e8c-b479-e22fe16fc725.png)

**Comment by sarithapillai8** [comment] 2022-06-27 05:09
@lukeoftheshire The console errors showing in the screenshot does not seems relevant with this issue. 

>What do you mean by 'send the whole activity data'?

As we are not able to reproduce this issue with our data. To reproduce this we need some other details. We doubt if this is something related to old invalid activity data. That is why we are asking for the activity data to reproduce this. We understand sharing the credentials is not possible always. That is why we are asking for activity data. If you can export the activity data and share it with us, we can debug the issue here.

**Comment by michaelmenon** [comment] 2022-06-27 13:57
Hi @ertjlane  as mentioned by @sarithapillai8  in the post above we think this issue is due to some invalid data in the DB, not able to reproduce it here as well so could you please import the activity data for this user through export option in the activity list, so we can check on the data to figure out what's wrong.

**Comment by ertjlane** [comment] 2022-06-27 15:14
@michaelmenon @sarithapillai8, understood. I just updated the forum post where this was brought up with instructions for the users to send us this data (instructions written curtesy of Luke). I will let you know as soon as they have sent that to us.

**Comment by ertjlane** [comment] 2022-06-28 14:58
One of the users has pulled the following data:
[
{
“id”: “zxndrg27psjgpmczk5mx”,
“spec”: “lamp.survey”,
“name”: “Daily Survey”,
“schedule”: [
{
“start_date”: “2021-09-29T23:30:00.000Z”,
“time”: “2021-11-20T19:30:00.000Z”,
“custom_time”: null,
“repeat_interval”: “daily”,
“notification_ids”: [
554264
]
}
],
“category”: [
“assess”
]
}
]

They commented: 'To clarify, the entire activity tab is spinning/inaccessible to add or edit, and houses multiple different surveys & schedules corresponding to different studies. The result above was consistent for all of these studies. The surveys are however working within the app and collecting data (with the exception of the logout/other intermittent bugs)."

**Comment by ZCOEngineer** [comment] 2022-06-29 10:14
@ertjlane we shall check with this data and update you on our findings

**Comment by sarithapillai8** [comment] 2022-06-29 12:07
@ertjlane 
The given survey have no settings. So I am not able to import this data in to any test study. Could you please confirm this is the actual survey data?

**Comment by sarithapillai8** [comment] 2022-07-01 05:49
@lukeoftheshire Can we get the whole activity data to debug which one is causing the issue or get the credentials to debug? The above given data didn't help in debugging.

**Comment by sarithapillai8** [comment] 2022-07-01 12:23
@lukeoftheshire While checking the issue, we found a condition that if no studies are selected, the activity tab loader never ends. Fixed that issue and updated in dashboard-staging. Not sure if the actual issue related to this, as I can see some activities(in the screenshot and attached video) in the background which requires study selection in the top.

**Comment by avaidyam** [comment] 2022-07-04 17:59
> we found a condition that if no studies are selected, the activity tab loader never ends

@sarithapillai8 Can you submit that to QA testing so we can push that fix to staging? That way the collaborators can test it and confirm.

**Comment by divyav2020** [comment] 2022-07-05 11:31
We have updated in Staging

**Comment by avaidyam** [comment] 2022-07-05 12:27
@ertjlane @lukeoftheshire Can you have the collaborators experiencing this issue check on staging now? I'm closing the issue for now as QA testing was completed on the suspected fix but please do reopen if the issue isn't resolved.

**Comment by ertjlane** [comment] 2022-07-05 17:24
@avaidyam Done, I'll update when they've verified if this fixed the issue.

**Comment by ertjlane** [comment] 2022-07-06 22:48
The collaborator reports that they are still experiencing this issue in the staging dashboard. An additional collaborator has reported that they are seeing the spinning wheel both in staging, and in other investigator accounts they are running under the same server, without any activity .json files imported into them. The .json files uploaded by the second collaborator is the same as that used in a previous study, where this issue did not arise. This same server was working fine a month or so ago. Please let me know if you need any additional information.

**Comment by sarithapillai8** [comment] 2022-07-07 05:01
@ertjlane We are not able to investigate on this with the above information. Can we get any test researcher account with which we can debug the issue? As the data imported into another account is not experiencing the same, we need a researcher account with which we can actually experience the issue.

**Comment by sarithapillai8** [comment] 2022-07-08 05:11
@ertjlane 
The given credentials is a participant/patient account. Not the researcher.
We have to reproduce the issue and debug. With the provided details we are not able to do that. Please provide a test researcher account with which we can reproduce the scenario.

**Comment by ertjlane** [comment] 2022-07-11 16:05
Understood, the user accidentally sent the incorrect credentials - these should give you access to the appropriate user account.
domain: api.mindlamp.itpmclean.org
email: ycTest@lamp.com
pw: yc123







[2:44](https://chr-dataflow.slack.com/archives/D03FELQULAG/p1657305864765319)
pw:yc123

**Comment by sarithapillai8** [comment] 2022-07-12 11:26
@avaidyam @lukeoftheshire @ertjlane 
The issue is fixed in dashboard staging.
Note :  There are no activity specs available on this given server. The loading issue was related to that.

**Closed** 2022-07-12 16:50 UTC
Labels: bug, 1day, frontend, priority HIGH

**Comment by ertjlane** [comment] 2022-07-27 21:16
This seems to be fixed in staging!
