### ISSUE TITLE
1. Notification not appearing when they're scheduled to 2. App goes to blank screen when game finishes and eventually crashes

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#212] opened 2021-04-21 19:33 UTC
> Essentially, the games are not all popping up on my cell phone at the 
> time and date I've setup. I don't have a list of the exact problems but 
> here are two examples.
> 
> -I've setup Spatial Span Back to repeat weekly on Fridays and I'm 
> getting notifications about it on Tuesday (see attached screenshot from 
> today).
> -I've setup Jewels A to notify me at 1pm and setup a custom repeat for 
> Noon. There is no ability to specify frequency (daily, weekly, etc and 
> it does not mention what the "custom" repeat interval is). It has been 
> notifying me every day at Noon, which probably is fine, but is not 
> clear.
> -I've setup a few game to popup 1x/month and I have not gotten the 
> notifications, but I'm not 100% sure about this since these are so rare 
> but I don't recall doing any of the popup games other than Jewels A and 
> Spatial Span.
> 
> In addition, there is no instruction for spatial span back (to 
> differentiate it from spatial span forward)
> 
> Also, when you finish the games, the app  frequently goes to a blank 
> blue screen and does not automatically exit the game for you. When you 
> touch the back arrow, it takes you to a blank white screen and crashes
> 
> ---
> 
> Thank you for your email. It seems that the same problem still persists for the Android. Except this time, every time I get on the app, it signs me automaticlly onto a demo account, which I have to log out of to sign into my account.
> 
> I have also noticed that sometimes I have a notification banner that suggests that mindlamp is collecting active data, when the app suggests that I am not logged into my account. Even when the banner is present, I have not been receiving notifications for tasks, when my PI (who has an iPhone) has been. The pictures I've attached for reference were just taken moments ago.
> 
> Please let me know if I can provide any more information!
![image](https://user-images.githubusercontent.com/82968538/115610491-f00c0800-a2b6-11eb-8087-6d85b14773fd.png)

**Comment by avaidyam** [comment] 2021-05-21 17:04
Duplicate of #202 (or #86 and #59), #94 + #55, and #170.

**Closed by avaidyam** 2021-05-21 17:04 UTC
