### ISSUE TITLE
Download data from Portal distorted and not usable

### ISSUE THREAD

**Issue by changchunlei** [BIDMCDigitalPsychiatry/LAMP-platform#507] opened 2022-02-09 05:37 UTC
**Describe the bug**
When I download data with the tick box in the first option cleared (snapshot below), the exported file is distorted and not usable (attached). 

![bug1](https://user-images.githubusercontent.com/3335476/153128193-d2134202-db9c-4335-b3bf-ed1c20040e09.png)
[Bug_LAMP_Mi_Research Study_Activity_Data_2_9_2022.csv](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8029786/Bug_LAMP_Mi_Research.Study_Activity_Data_2_9_2022.csv)

**To Reproduce**
1. Go to web -> Data portal
2. Click on '.download data.'
3. just download data for all activities for this Study.

**Comment by lukeoftheshire** [comment] 2022-02-10 15:38
Hi @changchunlei 

Thank you very much for bringing this to our attention, for your description of how to reproduce this bug and especially for your attached file to show the issue in question!

I have looked into this and I think I may have found (at least part) of the issue, which may be simply that you have a great deal of data. As you can see in the [Excel support docs](https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3), the max number of characters supported in a single cell is 32,767. When I looked into your data in Python it looks like your first activityevents cell contains 32,743 characters - very close to this limit (the difference is probably due to escape characters for quotes).

What I think may have happened, if your csv was loaded into Excel and then saved, is that Excel split the csv into multiple lines -- which does make the data quite unusable. I tried something similar with a test user of mine that has enough data to overload the Excel character limit and saw the same thing. You might also notice that your two test users don't show this issue - their activityEvent cells have 3712 and 1834 characters, respectively.


I think there are two ways you can solve this problem:
1. If you want to look at the data in excel, you should be able to if you separate the activity data into individual rows (or perhaps even just participant data) using the checkboxes. I suspect this will allow you to get around the character limit.
2. You could also try loading the data into an analysis framework, like pandas in Python. I tried the following script:
```
import pandas as pd
pd.read_csv('luke_test_data.csv')
```
where [`luke_test_data.csv`](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8042237/luke_test_data.csv) is some activity data from my sample users. If you run this code, the data frame is correctly made and can be worked on -- but if the file is opened in excel, one of the rows is distorted. This should mean that the data is correctly formatted when it is downloaded from LAMP. Please note that you may have to re-download your data if you saved it in Excel.

I hope that this helps (and was not too lengthy)! If either of these solutions don't work for you, you see this issue again, or I can give more information about this, please let me know.

**Comment by avaidyam** [comment] 2022-02-10 16:38
@lukeoftheshire Thinking more about the CSV file itself, here's what it looks like when I open it: 
<img width="944" alt="Screen Shot 2022-02-10 at 11 36 45 AM" src="https://user-images.githubusercontent.com/1361003/153453642-2207639e-7704-43a4-a7db-1243943cbaaf.png">

Is that expected formatting? I imagine with a CSV or Excel file, we should be exporting natively as a tabular format and not as a nested JSON document?

**Comment by avaidyam** [comment] 2022-02-10 20:26
> To summarize, this issue appears to be related to spreadsheet programs having a character limit for a single cell

✅ Agreed! 

> option of exploding the activityevent JSON before download is also possible

I would argue this should be the natural state of things? Do you think we should spin that out into a separate GitHub issue?

**Comment by avaidyam** [comment] 2022-02-10 20:48
> default behavior is to explode both activity events

I see what you mean - that makes sense, thanks!

**Comment by lukeoftheshire** [comment] 2022-02-25 16:39
I'm going to close this as it seems like we have found the root cause of this issue. We can of course re-open it if need be.

**Closed by lukeoftheshire** 2022-02-25 16:39 UTC
Labels: bug, NO ETA, frontend, priority LOW
