### ISSUE TITLE
Mandatory response before preceding

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#237] opened 2021-04-30 12:03 UTC
> All questions should be mandatory in PHQ-9 and sleep questionnaire. Right now, one can proceed ahead even without answering any particular question

**Comment by avaidyam** [comment] 2021-05-21 17:29
This was actually the original behavior of surveys from mindLAMP v1 and early v2. This was modified (for MAPNET reasons) but should likely be a parameter for each survey question (`required: boolean`) to selectively enable it.

**Comment by avaidyam** [comment] 2021-11-17 15:30
Duplicate of #427 and #385.

**Closed by avaidyam** 2021-11-17 15:30 UTC
Labels: feature, frontend
