### ISSUE TITLE
Calendar feed loading error 

### ISSUE THREAD

**Issue by changchunlei** [BIDMCDigitalPsychiatry/LAMP-platform#480] opened 2022-01-24 08:11 UTC
**Describe the bug**
Hi team,

We’ve encountered RangeError in calendar feed (on both andriod iPhone and webpage).
If you click/view more than 4 days on the feed, it will lead to an error page as attached.

**To Reproduce**
**One of our researcher created a caldenar feed with reminders. but she forgot to set the "Repeat Interval" (left blank).**
becuase it didn't appear in "feed" so we went back and reset the "Repeat Interval" to "Do not repeat". The caldendar item shows alright in the "Feed". However, from then, we have encounter a system-wide error message when user's view more than 3 days of "feed" for both iPhone and Andriod app and website. 

1. Go to app 'Feed'
2. Click on 4 different date ''
error showing up.

**Expected behavior**
to show calendar without exception

**Screenshots**
attached

**Desktop (please complete the following information):**
both ios, andrio app, and dashboard website.

![image](https://user-images.githubusercontent.com/3335476/150745234-9391429b-59a8-4d7b-95d3-5140bddfe282.png)
![image](https://user-images.githubusercontent.com/3335476/150745251-5c1a3333-3b61-4b97-a5f5-aa24e5aa44d0.png)

**Comment by divyav2020** [comment] 2022-01-24 11:38
We are unable to reproduce this issue. Hence kindly provide us Your Researcher details and Participant ID

**Comment by changchunlei** [comment] 2022-01-24 11:55
We are using the our own server: https://dash.monashlamp.com/
please use below testing information to reproduce the issue. 
api.monashlamp.com
U8220630168@lamp.com
U8220630168
Thanks!

**Comment by sarithapillai8** [comment] 2022-01-31 14:23
@avaidyam 
This is fixed in dashboard-staging. QA done.

**Closed** 2022-01-31 14:23 UTC
Labels: bug, 2day, frontend, priority LOW, QA testing
