### ISSUE TITLE
Activities in Prevent page should be automatically expanded.

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#419] opened 2021-10-29 13:49 UTC
Activities in Prevent page should be automatically expanded.

**Comment by sarithapillai8** [comment] 2021-11-15 12:27
@SuruPa00 
Could you please provide more details on this?

**Comment by avaidyam** [comment] 2021-11-17 15:25
Duplicate of #344.

**Comment by SuruPa00** [comment] 2021-11-17 15:42
@sarithapillai8 

Currently, only the sensor data are automatically shown in the Portal page, see below:

![image](https://user-images.githubusercontent.com/86117379/142231909-7d937e2c-e573-4d4e-b4b3-4055824be45f.png)

We would like the activity graphs to be automatically shown upon entering the portal page instead of having to manually click on each on as seen below:

![image](https://user-images.githubusercontent.com/86117379/142232345-a0d1144a-297c-458b-8d74-80c3889b471e.png)

**Comment by SuruPa00** [comment] 2021-11-17 15:45
also, duplicate of #344

**Comment by sarithapillai8** [comment] 2021-11-19 05:27
@SuruPa00 
This is working differently. We are not showing the activity/sensor data automatically here. The visualization graph is showing automatically by mistake. It was a requirement to save the selections made and show them on next login.  So do you actually want to show these by default or apply the same condition of activity/sensor selections for visualizations?
@avaidyam Please confirm on this.

**Comment by SuruPa00** [comment] 2021-11-30 18:06
@sarithapillai8, lets have it all show by default, the visualization graphs should be showing anyways - that is the current intended functionality

**Comment by sarithapillai8** [comment] 2021-12-01 05:27
@SuruPa00 
@avaidyam Please confirm on this change as you were asked to do like this. We are using these tags for this - "lamp.selectedActivities", "lamp.selectedSensors",  "lamp.selectedExperimental". Already the users have selections with these tags. So let me know how to proceed with this. Do we need to just ignore these tags?

**Comment by avaidyam** [comment] 2021-12-01 14:58
@sarithapillai8 Yes, let's drop these tags entirely from the codebase and just default to opening them all the time. This will make the user experience more consistent.

**Comment by lukeoftheshire** [comment] 2021-12-01 19:16
Hi @sarithapillai8 
I just spoke with @avaidyam and if you could actually *NOT* remove any code relating to 'lamp.selectedExperimental' that would be for the best - that tag only controls (to my knowledge) which graphs are shown in the *Cortex* section, not the activities - and we currently need to maintain control of that for some of our studies.

selectedActivities and selectedSensors should still be fine to drop. Thank you for understanding!

**Comment by sarithapillai8** [comment] 2021-12-02 05:22
@avaidyam @lukeoftheshire 
I can keep 'lamp.selectedExperimental' and can remove other 2 tags. Please confirm whether we need the multiselect popup for all the activities/sensors for the selected view or can we remove that also?

**Comment by avaidyam** [comment] 2021-12-02 12:15
We want this popup to remain, but everything is enabled by default and we will no longer use the tags to track it.

**Comment by sarithapillai8** [comment] 2021-12-06 09:18
@avaidyam @SuruPa00 
This is updated in production.

**Closed** 2021-12-06 13:35 UTC
Labels: bug, 2day, frontend
