### ISSUE TITLE
Limit data frequency of Sensor data collection (Accelerometer, GPS)

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#290] opened 2021-06-07 14:26 UTC
Hi,

Is there a way to limit the data collection frequency of sensor like Accelerometer, GPS, with TestFlight beta build for iOS I am seeing about every 200 milliseconds we are getting Accelerometer data. Is there a way to limit to every 30 seconds or 1 minute. Thanks!

```
"timestamp": 1623071248486,
"sensor": "lamp.accelerometer",
"data": {
"x": 0.0286102294921875,
"y": -0.264404296875,
"z": -0.9575653076171875
}
},
  {
"timestamp": 1623071248287,
"sensor": "lamp.accelerometer",
"data": {
"x": 0.0345611572265625,
"y": -0.2652130126953125,
"z": -0.9506072998046875
}
},
  {
"timestamp": 1623071248086,
"sensor": "lamp.accelerometer",
"data": {
"x": 0.032012939453125,
"y": -0.2533416748046875,
"z": -0.95745849609375
}
```

**Comment by jijopulikkottil** [comment] 2021-06-23 15:28
Yes we can set frequency for gps, accelerometer/device_motion. The default frequency of accelerometer/device_motion is  5 (200 milliseconds). 
If we need to limit to every 30 seconds or 1 minute., we have to set frequency 0.0333 (1/30) or 0.0166 (1/60)

We have integrated this in app side. Ref: https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/145
But I think its counter part in web/server side is not done. @sarithapillai8 @avaidyam  can confirm it.

**Comment by jeydude** [comment] 2021-06-23 15:35
Thanks @jijopulikkottil
```
jijopulikkottil wrote:
If we need to limit to every 30 seconds or 1 minute., we have to set frequency 0.0333 (1/30) or 0.0166 (1/60)
```
assuming same logic applies to android app also.

**Comment by avaidyam** [comment] 2021-06-23 15:46
@jijopulikkottil @saranya-sajeev I believe we had discussed the units of this parameter should be in Hertz, as the parameter name is "frequency". That is, 5 Hz = 1/5 = 0.2 sec interval.

**Comment by jijopulikkottil** [comment] 2021-06-23 15:54
@avaidyam  yes. correct.
frequency  5 Hz = 1/5 = 0.2 sec interval.
frequency  0.0333 Hz = 1/30 = 30 sec interval.

> assuming same logic applies to android app also.
Yes.

**Comment by avaidyam** [comment] 2021-06-23 15:59
@jijopulikkottil Okay, I see - I originally misunderstood your comment and this makes more sense now. Sorry!

**Comment by jeydude** [comment] 2021-06-23 16:19
@jijopulikkottil, is this correct in the sensor configuration to collect data for every one minute in future?

  {
"id": "3ewpt11q4y656pgwxj8j",
"timestamp": 1623077614569,
"spec": "lamp.accelerometer",
"name": "Accelerometer",
"settings": {
"frequency": 0.0166
}
},
  {
"id": "5pb6j7e88amnvwrzph72",
"timestamp": 1623077622389,
"spec": "lamp.gps",
"name": "GPS",
"settings": {
"frequency": 0.0166
}
}

**Comment by jijopulikkottil** [comment] 2021-06-23 16:40
Hi @jeydude 
```
{
"id": "3ewpt11q4y656pgwxj8j",
"timestamp": 1623077614569,
"spec": "lamp.accelerometer",
"name": "Accelerometer",
"settings": {
"frequency": 0.0166,
"cellular_upload": true
}

```
You can add 'cellular_upload' field to any of the settings block. Then only the sensor should upload data on a cellular/LTE connection in addition to WiFi.

------
If not specified the field 'cellular_upload', It should be able to upload data using both network. There is a bug handling it. It can fix soon.

**Comment by jeydude** [comment] 2021-06-23 16:44
Sure, I will include them. Thanks!

**Comment by avaidyam** [comment] 2021-11-17 14:54
Duplicate of #145.

**Closed by avaidyam** 2021-11-17 14:54 UTC
Labels: feature, native core, backend
