### ISSUE TITLE
Bug: activity name runs over icon if it is long, Feature request: separate surveys and cognitive tests into different categories, set an icon for cognitive tests

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#215] opened 2021-04-21 19:40 UTC
> Our team would really like to see a separation of the surveys and cognitive tests similar to what was on mindLAMP 1 where there was a tab for surveys and brain games. The "Assess" page on mindLAMP 2 is very cluttered as it also shows the notification schedules. It seems very unnecessary to have the notification schedules here. We would like to see a clean assess page with different tabs or sections for the brain games and surveys. It would also be very ideal if you guys could bring back the icons that were shown for each of the brain games on mindLAMP 1. I understand that we are able to set our own images as icons, however; it would be nice to have these set icons for the cognitive tests. Lastly, if the name of the activity is longer it overlaps on the icon symbol which looks a bit unprofessional and undeveloped.

**Comment by avaidyam** [comment] 2021-05-21 17:09
Duplicate of #170 and #175.

**Closed by avaidyam** 2021-05-21 17:09 UTC
