### ISSUE TITLE
Activities not available to add

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#303] opened 2021-06-21 15:05 UTC
> All activities are not showing up properly see attached photos

> 
![image](https://user-images.githubusercontent.com/86117379/122784337-6362d380-d280-11eb-803f-16a9cd7e4e03.png)
![image](https://user-images.githubusercontent.com/86117379/122784355-678ef100-d280-11eb-91a0-0bdd2bded89e.png)

**Comment by sarithapillai8** [comment] 2021-06-22 08:07
We couldn't reproduce this one. Please recheck and confirm the study you selected for creating activity is in 'selected mode' in study filter.

**Comment by SuruPa00** [comment] 2021-06-22 19:26
we double checked and it seemed the issue is happening when the user is using the safari browser, incognito, and logged in as admin. perhaps try it like that and see if the issue is still not reproducible

**Comment by sarithapillai8** [comment] 2021-06-23 13:34
We checked in safari, incognito and as admin. We are not able to reproduce this issue. Can you see the scroll bar in the dialog with activity specs?

**Comment by SuruPa00** [comment] 2021-06-23 17:20
There is no scroll bar in the dialog and even more oddly, sometimes there are no activities available to add instead of only half the activities available in the original screenshot

**Comment by sarithapillai8** [comment] 2021-06-24 06:48
Which device are you checking this?

**Comment by ZCOEngineer** [comment] 2021-06-24 08:54
Could you provide Device, Browser, OS version, Browser version details?

**Comment by SuruPa00** [comment] 2021-06-24 12:57
MacBook Pro (15-inch, 2018), Safari, macOS Version 11.2.3 (20D91), Safari Version 14.0.3 (16610.4.3.1.7)

**Comment by michaelmenon** [comment] 2021-06-25 15:54
Thanks team is looking into it and will update asap. Seems like its not happening on our end.. need to check if its a specific browser version issue. Will update.

**Comment by sarithapillai8** [comment] 2021-06-28 10:59
<img width="1438" alt="Screen Shot 2021-06-28 at 6 20 14 AM" src="https://user-images.githubusercontent.com/63710347/123625198-24f38880-d82d-11eb-8127-f963510eaba6.png">
<img width="1434" alt="Screen Shot 2021-06-28 at 6 22 15 AM" src="https://user-images.githubusercontent.com/63710347/123625204-2755e280-d82d-11eb-979d-1cded8c62e05.png">

Please check the screenshots. We checked in different devices(Mac browsers, Safari 14, incognito window, etc) and we are not able to reproduce this in any of this.

@avaidyam Could you please check this from your side to reproduce this?

**Closed** 2021-11-17 13:51 UTC
Labels: bug, frontend, cannot reproduce
