### ISSUE TITLE
Repeated Logout from Mindlamp 2

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#639] opened 2022-05-19 15:43 UTC
**Describe the bug**
App logs out intermittently, usually after several hours. The app would then log back in on its own. Was replicated across multiple phones. Backend examination of lamp activity for one of the phones gave timestamps of logout instances (screenshots below).

**To Reproduce**
1. Open mindlamp after login. 
2. See error

**Expected behavior**
Click on app from home screen, app opens to logged in user on the 'assess' page.

**Screenshots**
![Image](https://user-images.githubusercontent.com/104088715/169360753-78486c0a-8c9c-442b-9970-d8fa38d3d578.jpeg)
![Image (1)](https://user-images.githubusercontent.com/104088715/169360777-56de73f7-81a3-4312-8860-f6a721bb3b0d.jpeg)
![issue](https://user-images.githubusercontent.com/104088715/169336102-cd7bdab0-cdff-47e0-96b5-f86979280225.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iPhone 11 Pro ]
 - OS: [iOS 15.3]

**Additional context**
*Appeared on 2 phones of same model and OS.

**Comment by ZCOEngineer** [comment] 2022-05-20 05:19
We are checking this, shall update our findings/questions soon

**Comment by jijopulikkottil** [comment] 2022-05-20 10:41
Hope you are getting issue when using other than the production domain (api.lamp.digital).

Could you give us the domain name and test username/password to test?

**Comment by jtorous** [comment] 2022-05-20 10:56
It is not our BIDMC/Boston one, but instead:
mindlamp-api-dev.pronet.med.yale.edu

My test account that had a logout in the issue is:

Email: ***@***.***

Password: 45yQVEEu!wsp

**Comment by jijopulikkottil** [comment] 2022-05-20 11:07
Could you send the email (username) to @michaelmenon 's email

**Comment by jtorous** [comment] 2022-05-20 11:45
Yes, just did!

**Comment by divyav2020** [comment] 2022-05-20 14:42
We have kept the phone with the user logged in status to see if the logout issue can be reproduced, so far we have not experienced any issues, we are watching it over the weekend, shall update here as soon as we find anything

**Comment by jtorous** [comment] 2022-05-20 14:46
Thanks - it seemed to happen with notifications for activities once. But I
understand it may be hard to catch.

-John

**Comment by jijopulikkottil** [comment] 2022-05-20 15:24
Just to confirm that.. Are you using the above given researcher account and experience the logout issue with the same account?  Or getting logout issue with any participant account under this researcher ?

**Comment by jijopulikkottil** [comment] 2022-05-20 17:09
Tested on iOS, When login with given credentials (researcher account) on mindlamp-api-dev.pronet.med.yale.edu, it doesn't return authorization token and identity object from web page to native.

As the basic auth details are not available in the app, it will navigate to login page on next launch. This is happening now.

We can investigate this with @Linoy339. 
@avaidyam

**Comment by jijopulikkottil** [comment] 2022-05-20 17:31
But When we login using a participant (e@.com), on same domain  mindlamp-api-dev.pronet.med.yale.edu, it does return authorisation token and identity object correctly. So no issues with this participant login.

**Comment by jijopulikkottil** [comment] 2022-05-27 17:49
@avaidyam It doesn't seems to be any connection with Push notification. 
On native side, we are facing the issue that, app doesn't receive login message (login message with authentication details)  when a researcher logged in. 
As the authentication token is not received, app will prompt login again when relaunch app

**Comment by avaidyam** [comment] 2022-05-27 17:56
I think you may be misunderstanding the issue we are trying to solve. When a **patient** is logged in, at some arbitrary point thereafter they reopen the app to find they are now "logged out", and then a few hours later they open the app again to find that they are "logged back in". It's not related at all to researcher login.

**Comment by jijopulikkottil** [comment] 2022-05-27 18:07
@avaidyam  Thanks to the clarification of issue

**Comment by jijopulikkottil** [comment] 2022-06-02 14:08
Hope this issue is experiencing only in iOS device. @avaidyam So [this](https://stackoverflow.com/questions/20269116/nsuserdefaults-losing-its-keys-values-when-phone-is-rebooted-but-not-unlocked) could be the problem. We are also keeping the token in UserDefaults.

But as per the first [this](https://user-images.githubusercontent.com/104088715/169336102-cd7bdab0-cdff-47e0-96b5-f86979280225.JPG) comment, it received 'logout' event, but this is not expected with this(UserDefault-lock) case.

**Comment by avaidyam** [comment] 2022-06-02 15:17
@jijopulikkottil The fix for the suspected issue was already merged into master. Can you please pull from master and test the iOS build with the staging dashboard?

**Comment by michaelmenon** [comment] 2022-06-03 16:35
Hi @avaidyam  hope these were the fixes you were talking about. 

This seems to be fixing the researcher logout issue which we thought initially the main issue was : 

https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/622/commits/d3ed07ff2e1a01d5a1401f8d7f98c865fab79ed9


Also there seems to be one update on the iOS side : 
https://github.com/BIDMCDigitalPsychiatry/LAMP-core-ios/pull/47

Not sure if this has resolved the suspected issue of participant logout as that is not always reproducible. Team was testing today and we can share our updates Monday in our call.

**Comment by ZCOEngineer** [comment] 2022-06-06 04:44
With the new iOS build too we are not getting this issue.

**Comment by jijopulikkottil** [comment] 2022-07-01 04:56
Hi @Devayani0102 Could you confirm the app version using. AppStore app or Test flight app ?
The above [fix](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/639#issuecomment-1144987187) is not yet available on  appstore app.

**Comment by ZCOEngineer** [comment] 2022-07-04 07:53
@Devayani0102 were you able to check this?

**Comment by avaidyam** [comment] 2022-07-04 17:40
@jijopulikkottil I had @ertjlane check this, and it seems like the TestFlight build didn't get pushed to production yet. I'll take care of that right now. Do you know if we can make this process automatic in the CI/CD (i.e. submit to app store for production) for when we create a GitHub Release?

**Closed by avaidyam** 2022-07-04 17:40 UTC
Labels: bug, NO ETA, frontend, priority HIGH

**Comment by jijopulikkottil** [comment] 2022-07-04 17:45
Yes @avaidyam . We have done this. If we push/merge to master, then it will make a staging pointed build. And if we create a release, it will be production pointed.

**Comment by avaidyam** [comment] 2022-07-04 17:58
@jijopulikkottil Yes, but does it automatically create a release and submit the build for app store review?

**Comment by jijopulikkottil** [comment] 2022-07-05 07:54
No. 
You mean create new version, add 'Whats New' etc.. and submit for review. right ? So are we supposed to use [fastlane deliver](https://docs.fastlane.tools/actions/deliver/) ?

**Comment by Tuna9129** [comment] 2022-08-08 00:19
This seems to be fixed in staging!

**Comment by ertjlane** [comment] 2024-02-22 16:41
I'm making a quick note here. Another user has reported this issue, specifically with a 
- iPhone 13
- iOS Version 17.2
They are repeatedly being logged out, and having to log back in again. Before re-opening the issue I want to assess potential troubleshooting strategies or features to double check. Purportedly the user has uninstalled and reinstalled the app already, they are not in low power mode, and have consistent wifi/cell connection. Let me know your thoughts. If it is not readily resolvable we will re-open the issue and look further.

**Comment by ZCOEngineer** [comment] 2024-02-26 02:54
@ertjlane lets first try to reproduce this here in the same os version.

**Comment by jijopulikkottil** [comment] 2024-02-26 14:12
@ertjlane Thanks for posting the issue here rather than create new one.
Hope the issue is same https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/639#issuecomment-1139897285

Also could the user confirm the below scenario ?
When you see the login screen when reopening the app, could you[ force quit the app and relaunch](https://support.apple.com/en-in/guide/iphone/iph83bfec492/ios) and check wether it is loading home page or login page ?

**Comment by ertjlane** [comment] 2024-02-26 19:38
@jijopulikkottil Thanks. It is actually distinct from the comment you linked, in that the user stays logged out, and must login again manually. Like the original issue, however, it is disconnected from the researcher login. I will reach out and inquire if the user would implement the strategy you mentioned.
