### ISSUE TITLE
Data portal visualization error

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#718] opened 2022-12-01 15:29 UTC
It appears that for any researcher, visualizations in the data portal produce an error.

Bug originally reported here: https://mindlamp.discourse.group/t/cortex-visualizations-show-react-error-310/726

**To Reproduce**
Example steps to reproduce error:
1. Enter LAMP dashboard
2. Enter data portal
3. Enter GUI mode
4. Select researcher
5. Select "data quality tags"

Output for error: 
![image](https://user-images.githubusercontent.com/103652751/205092613-a3938cc3-0885-4781-97d7-467f3e3375c1.png)

**Comment by falmeida-orangeloops** [comment] 2022-12-06 19:19
@ertjlane Hi! I've followed those steps in staging for different researchers and unfortunately I'm not getting that error.
However, some things I've noticed make me suspect that this issue is a duplicate of [#717](717):
- Both issues are related to the same screen
- The screenshots in both issues match perfectly
- [#717](717) was recently solved ([closed on 11/28](717#event-7906492866))
- The [report](https://mindlamp.discourse.group/t/cortex-visualizations-show-react-error-310/726) that was linked in the description of this new issue is from 11/22, which was shortly before [#717](717) was closed.

Considering this and the fact that I don't seem to be able to reproduce this error, is it possible that this is a duplicate of [#717](717)?

**Closed** 2022-12-07 19:10 UTC
Labels: bug, 1day, frontend, priority HIGH
