### ISSUE TITLE
Sensor Configuration

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#426] opened 2021-11-08 15:33 UTC
As per our conversation about the way sensor data is collected, let's have sensor collection return to the way it was where:
- If no sensors are created in a study/user, no sensor data is collected from
any sensor. 
- When no GPS sensor is created, IF it has to be collected no matter what (to keep the app alive in the background), make it so that the frequency is very low and the data is NOT uploaded to the server. 
- These updates will render `lamp.none` useless, but this is fine and this can be deleted after we test all the collection is working as intended.

Let's work on this AFTER automation is ready and item #139 is begun to be worked on.

**Comment by avaidyam** [comment] 2021-11-17 15:55
Duplicate of #145.

**Closed as completed by avaidyam** 2021-11-17 15:55 UTC
Labels: bug, backend
