### ISSUE TITLE
DBT Diary Card Target Behavior Error

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#104] opened 2021-01-27 13:12 UTC
> Collaborator: When creating a new DBT diary card and adding a target behavior, error screen popped up after typing in a custom "Measure of Action". Error displayed when measure of action was selected under target behaviors when we typed on the "clear X button"
> ![image](https://user-images.githubusercontent.com/1361003/105995672-50542a80-6077-11eb-977d-53d64db13cdd.png)

**Comment by divyav2020** [comment] 2021-01-28 12:05
@avaidyam We are unable to reproduce this issue. We have checked in both chrome and Firefox. Kindly provide us with more details.

**Comment by avaidyam** [comment] 2021-01-28 14:06
@divyav2020 @sarithapillai8 There is no need to reproduce the issue. 

The error reads `TypeError: Cannot read property 'toLowerCase' of null` -- if you are overriding types or using `any` please do not do that. TypeScript should not have allowed the code to compile if a variable was expected to be a `string` but could also be `null`. Furthermore, guarding the `toLowerCase` call in the DBT Creator UI will resolve this issue.

**Closed** 2021-05-21 15:12 UTC
Labels: 1day, bug, frontend
