### ISSUE TITLE
Problem with transferring data from Redis to CouchDB

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#527] opened 2022-02-21 23:54 UTC
Hi,

 I have  CACHE_SIZE: 100 in the yaml file. I have noticed CouchDB did not get data from Redis for quite sometime.

I was looking at the LAMP API Server log noticed the Store_Size value is increasing and Redis cache is growing faster but Redis cache data is not getting transferred to CouchDB as I am expecting.

Here is the log entries from LAMP API Server which has Store_Size value indicating size of the Redis cache.

```
Line 214: 2022-02-17T23:18:51.790764123Z Store_Size 108
	Line 336: 2022-02-17T23:39:10.992338466Z Store_Size 110
	Line 444: 2022-02-18T00:00:48.063188060Z Store_Size 111
	Line 554: 2022-02-18T00:20:52.839246444Z Store_Size 107
	Line 658: 2022-02-18T00:40:57.546205910Z Store_Size 103
	Line 778: 2022-02-18T01:03:36.472354102Z Store_Size 116
	Line 878: 2022-02-18T01:21:28.511102992Z Store_Size 106
	Line 1134: 2022-02-18T01:47:24.632255012Z Store_Size 104
	Line 1200: 2022-02-18T01:57:45.758995650Z Store_Size 110
	Line 1268: 2022-02-18T02:07:44.366183227Z Store_Size 102
	Line 1334: 2022-02-18T02:17:47.767167815Z Store_Size 101
	Line 1384: 2022-02-18T02:23:40.786790461Z Store_Size 112
	Line 1400: 2022-02-18T02:25:02.780189945Z Store_Size 2216
	Line 1408: 2022-02-18T02:25:04.357171317Z Store_Size 6610
	Line 1416: 2022-02-18T02:25:05.915613387Z Store_Size 10958
	Line 1424: 2022-02-18T02:25:07.412533396Z Store_Size 15358
	Line 1432: 2022-02-18T02:25:08.845441891Z Store_Size 19904
	Line 1440: 2022-02-18T02:25:10.299987581Z Store_Size 24105
	Line 1448: 2022-02-18T02:25:11.572778038Z Store_Size 28431
	Line 1456: 2022-02-18T02:25:12.751672722Z Store_Size 32810
	Line 1466: 2022-02-18T02:25:13.992063082Z Store_Size 37174
	Line 1474: 2022-02-18T02:25:15.427265630Z Store_Size 41505
	Line 1482: 2022-02-18T02:25:16.692744465Z Store_Size 45832
	Line 1490: 2022-02-18T02:25:17.890798034Z Store_Size 50174
	Line 1498: 2022-02-18T02:25:19.319762115Z Store_Size 54512
	Line 1506: 2022-02-18T02:25:20.435759456Z Store_Size 58838
	Line 1514: 2022-02-18T02:25:21.677953778Z Store_Size 63184
	Line 1522: 2022-02-18T02:25:22.902992844Z Store_Size 67518
	Line 1530: 2022-02-18T02:25:24.686110270Z Store_Size 72045
	Line 1538: 2022-02-18T02:25:25.857211509Z Store_Size 76256
	Line 1546: 2022-02-18T02:25:27.189613138Z Store_Size 80585
	Line 1554: 2022-02-18T02:25:28.290021609Z Store_Size 84911
	Line 1562: 2022-02-18T02:25:29.462521579Z Store_Size 89168
	Line 1570: 2022-02-18T02:25:30.670493599Z Store_Size 93422
	Line 1578: 2022-02-18T02:25:31.858326216Z Store_Size 97755
	Line 1586: 2022-02-18T02:25:32.964006483Z Store_Size 102093
	Line 1594: 2022-02-18T02:25:34.115314614Z Store_Size 106428
	Line 1602: 2022-02-18T02:25:35.270038050Z Store_Size 110753
	Line 1610: 2022-02-18T02:25:36.516931116Z Store_Size 115077
	Line 1618: 2022-02-18T02:25:37.614224080Z Store_Size 119542
	Line 1626: 2022-02-18T02:25:38.774475100Z Store_Size 124077
	Line 1630: 2022-02-18T02:25:39.741289098Z Store_Size 128340
	Line 1644: 2022-02-18T02:25:40.933678897Z Store_Size 132916
	Line 1648: 2022-02-18T02:25:40.978519063Z Store_Size 133216
	Line 1650: 2022-02-18T02:25:41.152278743Z Store_Size 134428
	Line 1676: 2022-02-18T02:27:48.977026453Z Store_Size 134338
	Line 1680: 2022-02-18T02:27:49.089707582Z Store_Size 134250
	Line 1684: 2022-02-18T02:27:49.203062396Z Store_Size 134160
	Line 1688: 2022-02-18T02:27:49.209829628Z Store_Size 134072
	Line 1694: 2022-02-18T02:27:49.335490367Z Store_Size 133995
	Line 1696: 2022-02-18T02:27:49.336825398Z Store_Size 133896
	Line 1700: 2022-02-18T02:27:49.447667389Z Store_Size 133806
	Line 1704: 2022-02-18T02:27:49.452637539Z Store_Size 133715
	Line 1710: 2022-02-18T02:27:49.565983219Z Store_Size 133637
.....
	Line 72056: 2022-02-21T23:03:24.820036299Z Store_Size 6418022
	Line 72060: 2022-02-21T23:03:24.885769529Z Store_Size 6417932
	Line 72086: 2022-02-21T23:07:07.291249252Z Store_Size 6417844
	Line 72090: 2022-02-21T23:07:07.324990532Z Store_Size 6417767
	Line 72106: 2022-02-21T23:08:15.876339386Z Store_Size 6417677
	Line 72110: 2022-02-21T23:08:15.974301393Z Store_Size 6417599
	Line 72146: 2022-02-21T23:13:25.973128744Z Store_Size 6417509
	Line 72150: 2022-02-21T23:13:26.060962024Z Store_Size 6417419
	Line 72212: 2022-02-21T23:18:01.102676367Z Store_Size 6417335
	Line 72216: 2022-02-21T23:18:01.157103970Z Store_Size 6417251
	Line 72236: 2022-02-21T23:18:17.312452758Z Store_Size 6417161
	Line 72240: 2022-02-21T23:18:17.395410487Z Store_Size 6417072
	Line 72338: 2022-02-21T23:23:29.697732821Z Store_Size 6416982
	Line 72342: 2022-02-21T23:23:29.766886769Z Store_Size 6416892
```

**Comment by avaidyam** [comment] 2022-02-23 16:54
@Linoy339 It looks like the flushing logic may need to be tested better. Can you identify the root cause of the issue here? Thanks!

**Comment by Linoy339** [comment] 2022-02-24 04:58
@jeydude . Can you please provide the `YAML `file here?

**Comment by Linoy339** [comment] 2022-02-24 06:13
@jeydude . Can you please take `ghcr.io/bidmcdigitalpsychiatry/lamp-server:latest`, as I have pushed some more logging related with this issue?

**Comment by Linoy339** [comment] 2022-02-24 08:07
@avaidyam @jeydude .  The issue is that only `100 data` (CACHE_SIZE) is inserted to db at a time. As, the frequency of `sensor_event` is getting much higher in certain times (from the logs), data insert to db becomes lower. 
From the below logs:
> Line 1384: 2022-02-18T02:23:40.786790461Z Store_Size 112
> 	Line 1400: 2022-02-18T02:25:02.780189945Z Store_Size 2216
> 	Line 1408: 2022-02-18T02:25:04.357171317Z Store_Size 6610
> 	Line 1416: 2022-02-18T02:25:05.915613387Z Store_Size 10958
> 	Line 1424: 2022-02-18T02:25:07.412533396Z Store_Size 15358
> 	Line 1432: 2022-02-18T02:25:08.845441891Z Store_Size 19904
> 	Line 1440: 2022-02-18T02:25:10.299987581Z Store_Size 24105
> 	Line 1448: 2022-02-18T02:25:11.572778038Z Store_Size 28431
> 	Line 1456: 2022-02-18T02:25:12.751672722Z Store_Size 32810,
It is understood that data frequency is adding up much higher`(112 to 2216,2216 to  6610 and so on)`. 
If we are taking the figure  `6610 ` as example, 6510 data will be there still in cache and 100 data will be inserted to db. Also these 100 data would be trimmed off. If high frequency of data is noted, we recommend to make `CACHE_SIZE` as `30000`.

From [https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/489](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/489), it was mentioned that only lesser amount of data would be arriving as `sensor_events`(). But from the logs above, there can be higher frequency in certain times. 
This seems to be not an issue, but the data insert to db becomes slower.

@jeydude . Can you switch the `CACHE_SIZE` to `10000`, as quick fix, so that data get inserted fastly?
Also, its always recommended to keep this value  as more than 5000, as the frequency of data from single participant is assumed as 5000.

**Comment by Linoy339** [comment] 2022-02-24 08:47
@avaidyam @jeydude . The issue is that only 100 data (`CACHE_SIZE` from env) is inserted to db at a time. As, the frequency of sensor_event is getting much higher in certain times (from the logs), data insert to db becomes lower.
From the below logs:

Line 1384: 2022-02-18T02:23:40.786790461Z Store_Size 112
Line 1400: 2022-02-18T02:25:02.780189945Z Store_Size 2216
Line 1408: 2022-02-18T02:25:04.357171317Z Store_Size 6610
Line 1416: 2022-02-18T02:25:05.915613387Z Store_Size 10958
Line 1424: 2022-02-18T02:25:07.412533396Z Store_Size 15358
Line 1432: 2022-02-18T02:25:08.845441891Z Store_Size 19904
Line 1440: 2022-02-18T02:25:10.299987581Z Store_Size 24105
Line 1448: 2022-02-18T02:25:11.572778038Z Store_Size 28431
Line 1456: 2022-02-18T02:25:12.751672722Z Store_Size 32810,
It is understood that data frequency is adding up much higher(112 to 2216,2216 to 6610 and so on).
If we are taking the figure 6610 as example, 6510 data will be there still in cache and 100 data will be inserted to db. Also these 100 data would be trimmed off. If high frequency of data is noted, we recommend to make CACHE_SIZE as 30000.

From #489, it was mentioned that only lesser amount of data would be arriving as sensor_events. But from the logs above, there can be higher frequency in certain times.
This seems to be not an issue, but the data insert to db becomes slower.

@jeydude . Can you switch the CACHE_SIZE to 10000, as quick fix, so that data get inserted fastly?
Also, its always recommended to keep this value as more than 5000, as the frequency of data from single participant is assumed as 5000. We will also push a fix to increase `CACHE_SIZE ` to `5000 `, if  its less than that.

**Comment by avaidyam** [comment] 2022-02-24 16:57
@Linoy339 I'm not sure why `CACHE_SIZE` is implemented this way. **It should not act this way.** It should be the number of cached events required before the **ENTIRE cache** is flushed to database. Please update the implementation. `MAX_STORE_SIZE` should not be a variable in the code at all anymore, `CACHE_SIZE` is supposed to have replaced it.

**Comment by Linoy339** [comment] 2022-02-25 05:35
@avaidyam . `CACHE_SIZE` is implemented in the way which was proposed here:
[https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/489#issuecomment-1035165981](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/489#issuecomment-1035165981).
Here, we implemented in a way that a **fixed number of data from cache gets flushed to db  instead of entire cached data.**
and this fixed number will be the `MAX_STORE_SIZE ` which would be 30000 in our case and 100 in case of @jeydude.

For example:
Let's say  `CACHE_SIZE` is 10000, which will be the `MAX_STORE_SIZE ` . Whenever the redis cache of `sensor events` reaches 10000 or more than 10000, the first 10000 data gets flushed to db and also, the same gets trimmed from cache.
Here, even if cached events length is 10002, it will **handle first 10000 data** and **2 data remains in the cache itself**. It was done to a**void much conflicts between incoming data to redis cache and those which is ready to flush  to db**. Also, we get a proper number which would insert to db at a time.

**Comment by Linoy339** [comment] 2022-02-28 14:49
> Hi,
> 
> I have CACHE_SIZE: 100 in the yaml file. I have noticed CouchDB did not get data from Redis for quite sometime.
> 
> I was looking at the LAMP API Server log noticed the Store_Size value is increasing and Redis cache is growing faster but Redis cache data is not getting transferred to CouchDB as I am expecting.
> 
> Here is the log entries from LAMP API Server which has Store_Size value indicating size of the Redis cache.
> 
> ```
> Line 214: 2022-02-17T23:18:51.790764123Z Store_Size 108
> 	Line 336: 2022-02-17T23:39:10.992338466Z Store_Size 110
> 	Line 444: 2022-02-18T00:00:48.063188060Z Store_Size 111
> 	Line 554: 2022-02-18T00:20:52.839246444Z Store_Size 107
> 	Line 658: 2022-02-18T00:40:57.546205910Z Store_Size 103
> 	Line 778: 2022-02-18T01:03:36.472354102Z Store_Size 116
> 	Line 878: 2022-02-18T01:21:28.511102992Z Store_Size 106
> 	Line 1134: 2022-02-18T01:47:24.632255012Z Store_Size 104
> 	Line 1200: 2022-02-18T01:57:45.758995650Z Store_Size 110
> 	Line 1268: 2022-02-18T02:07:44.366183227Z Store_Size 102
> 	Line 1334: 2022-02-18T02:17:47.767167815Z Store_Size 101
> 	Line 1384: 2022-02-18T02:23:40.786790461Z Store_Size 112
> 	Line 1400: 2022-02-18T02:25:02.780189945Z Store_Size 2216
> 	Line 1408: 2022-02-18T02:25:04.357171317Z Store_Size 6610
> 	Line 1416: 2022-02-18T02:25:05.915613387Z Store_Size 10958
> 	Line 1424: 2022-02-18T02:25:07.412533396Z Store_Size 15358
> 	Line 1432: 2022-02-18T02:25:08.845441891Z Store_Size 19904
> 	Line 1440: 2022-02-18T02:25:10.299987581Z Store_Size 24105
> 	Line 1448: 2022-02-18T02:25:11.572778038Z Store_Size 28431
> 	Line 1456: 2022-02-18T02:25:12.751672722Z Store_Size 32810
> 	Line 1466: 2022-02-18T02:25:13.992063082Z Store_Size 37174
> 	Line 1474: 2022-02-18T02:25:15.427265630Z Store_Size 41505
> 	Line 1482: 2022-02-18T02:25:16.692744465Z Store_Size 45832
> 	Line 1490: 2022-02-18T02:25:17.890798034Z Store_Size 50174
> 	Line 1498: 2022-02-18T02:25:19.319762115Z Store_Size 54512
> 	Line 1506: 2022-02-18T02:25:20.435759456Z Store_Size 58838
> 	Line 1514: 2022-02-18T02:25:21.677953778Z Store_Size 63184
> 	Line 1522: 2022-02-18T02:25:22.902992844Z Store_Size 67518
> 	Line 1530: 2022-02-18T02:25:24.686110270Z Store_Size 72045
> 	Line 1538: 2022-02-18T02:25:25.857211509Z Store_Size 76256
> 	Line 1546: 2022-02-18T02:25:27.189613138Z Store_Size 80585
> 	Line 1554: 2022-02-18T02:25:28.290021609Z Store_Size 84911
> 	Line 1562: 2022-02-18T02:25:29.462521579Z Store_Size 89168
> 	Line 1570: 2022-02-18T02:25:30.670493599Z Store_Size 93422
> 	Line 1578: 2022-02-18T02:25:31.858326216Z Store_Size 97755
> 	Line 1586: 2022-02-18T02:25:32.964006483Z Store_Size 102093
> 	Line 1594: 2022-02-18T02:25:34.115314614Z Store_Size 106428
> 	Line 1602: 2022-02-18T02:25:35.270038050Z Store_Size 110753
> 	Line 1610: 2022-02-18T02:25:36.516931116Z Store_Size 115077
> 	Line 1618: 2022-02-18T02:25:37.614224080Z Store_Size 119542
> 	Line 1626: 2022-02-18T02:25:38.774475100Z Store_Size 124077
> 	Line 1630: 2022-02-18T02:25:39.741289098Z Store_Size 128340
> 	Line 1644: 2022-02-18T02:25:40.933678897Z Store_Size 132916
> 	Line 1648: 2022-02-18T02:25:40.978519063Z Store_Size 133216
> 	Line 1650: 2022-02-18T02:25:41.152278743Z Store_Size 134428
> 	Line 1676: 2022-02-18T02:27:48.977026453Z Store_Size 134338
> 	Line 1680: 2022-02-18T02:27:49.089707582Z Store_Size 134250
> 	Line 1684: 2022-02-18T02:27:49.203062396Z Store_Size 134160
> 	Line 1688: 2022-02-18T02:27:49.209829628Z Store_Size 134072
> 	Line 1694: 2022-02-18T02:27:49.335490367Z Store_Size 133995
> 	Line 1696: 2022-02-18T02:27:49.336825398Z Store_Size 133896
> 	Line 1700: 2022-02-18T02:27:49.447667389Z Store_Size 133806
> 	Line 1704: 2022-02-18T02:27:49.452637539Z Store_Size 133715
> 	Line 1710: 2022-02-18T02:27:49.565983219Z Store_Size 133637
> .....
> 	Line 72056: 2022-02-21T23:03:24.820036299Z Store_Size 6418022
> 	Line 72060: 2022-02-21T23:03:24.885769529Z Store_Size 6417932
> 	Line 72086: 2022-02-21T23:07:07.291249252Z Store_Size 6417844
> 	Line 72090: 2022-02-21T23:07:07.324990532Z Store_Size 6417767
> 	Line 72106: 2022-02-21T23:08:15.876339386Z Store_Size 6417677
> 	Line 72110: 2022-02-21T23:08:15.974301393Z Store_Size 6417599
> 	Line 72146: 2022-02-21T23:13:25.973128744Z Store_Size 6417509
> 	Line 72150: 2022-02-21T23:13:26.060962024Z Store_Size 6417419
> 	Line 72212: 2022-02-21T23:18:01.102676367Z Store_Size 6417335
> 	Line 72216: 2022-02-21T23:18:01.157103970Z Store_Size 6417251
> 	Line 72236: 2022-02-21T23:18:17.312452758Z Store_Size 6417161
> 	Line 72240: 2022-02-21T23:18:17.395410487Z Store_Size 6417072
> 	Line 72338: 2022-02-21T23:23:29.697732821Z Store_Size 6416982
> 	Line 72342: 2022-02-21T23:23:29.766886769Z Store_Size 6416892
> ```
@jeydude . Can you share the `LAMP-server` logs again to check the redis store size now ?

**Comment by avaidyam** [comment] 2022-02-28 15:00
> A **tweak which we made** in this is that MAX_STORE_SIZE would be taken as 100, if CACHE_SIZE (from env) is kept as a value less than 100 , which means the data from redis gets flushed to db when it reaches the length of 100 or more.

@Linoy339 Let's remove this. If `CACHE_SIZE=0`, it should disable caching at all (which is understandably bad for the database, but may be required for some IT teams). Smaller values of `CACHE_SIZE` should also be appropriate and allowed. 

> It was already implemented in a way that a fixed number of data from cache gets flushed to db instead of entire cached data. We have done in this way to know the exact number of events flushing to db at a time. It will be 30000 in our case and 100 in case of @jeydude.

Then this needs to be a new environment variable. `CACHE_SIZE` refers to the maximum number of events the cache should hold before **the entire cache is flushed to database.** What you are referring to is more aptly described as a boolean `CACHE_FLUSH_ALL`. When set to `true`, it will flush **ALL events in the cache**, when set to `false`, it will **only flush `CACHE_SIZE` number of events.** 

> Its not recommended to have large number of data(eg:10 million) to be inserted to database at a time. So, its good **to have a fixed number from the cache to get inserted to db** which is recommended

Some databases are extremely capable of handling hundreds of millions of inserted data per operation -- this is a choice an IT team hosting LAMP needs to make, not us. Another consideration that isn't being taken here is the number of cached events exceeding `CACHE_SIZE` and thus the cache grows forever, since we never flush the entire cache to disk. That's a major bug that will lead to serious clinical concerns. 

> Here, even if we replace MAX_STORE_SIZE with CACHE_SIZE(from env), it would have the same result in case of @jeydude, as CACHE_SIZE is 100 and only 100 data gets flushed to db.

I think the point is to remove `MAX_STORE_SIZE` as a variable. _See my above note about adding `CACHE_FLUSH_ALL` instead to control this behavior._

**Comment by Linoy339** [comment] 2022-02-28 15:45
Thanks @avaidyam for the explanation.

Some clarifications :
-  Can we   take `CACHE_SIZE` as 30000 or 0 if its not defined ? Now, If we consider it as 0, caching will be disabled and if we consider it as 30000, it means that the redis cache can hold 30000 events.
-  Can we take  `CACHE_FLUSH_ALL` as false if its not defined ?

**Comment by avaidyam** [comment] 2022-02-28 15:47
Yes, the default values for `CACHE_SIZE` should be `0` (disabled), and `CACHE_FLUSH_ALL` should be `false`.

**Comment by Linoy339** [comment] 2022-02-28 15:56
Okay. This means that our environment will be implemented with these 2 variables. Right?
If so, can you keep the variables `CACHE_SIZE ` and `CACHE_FLUSH_ALL ` in env for staging as well as production and fill it as
`CACHE_SIZE ` = 30000
`CACHE_FLUSH_ALL ` = false

**Comment by avaidyam** [comment] 2022-02-28 16:35
> This means that our environment will be implemented with these 2 variables. Right?

Yes. //cc @lukeoftheshire Can you update `LAMP-worker` in our staging and production stacks to add `CACHE_SIZE=30000` and `CACHE_FLUSH_ALL=true`? Thanks! 

> I have increased and reduced CACHE_SIZE few times to move data from REDIS to CouchDB because the cache size was keep on increasing.

@jeydude You may want to bump up `CACHE_SIZE` to something like `1000` or higher to avoid this.

**Comment by lukeoftheshire** [comment] 2022-02-28 16:41
Hi @avaidyam @Linoy339 

I can absolutely update those. To be clear, I will set `CACHE_SIZE` as `30000` (i.e. as an int, not a string).

@avaidyam, can you confirm whether `CACHE_FLUSH_ALL`  should be set as `true` or `false` - I see it both ways in the discussion here.

**Comment by avaidyam** [comment] 2022-02-28 16:42
@lukeoftheshire `CACHE_FLUSH_ALL=true`! 👍

**Comment by lukeoftheshire** [comment] 2022-02-28 16:44
Set!

**Comment by Linoy339** [comment] 2022-02-28 16:58
> Yes. //cc @lukeoftheshire Can you update `LAMP-worker` in our staging and production stacks to add `CACHE_SIZE=30000` and `CACHE_FLUSH_ALL=true`? Thanks!

@avaidyam ,@lukeoftheshire . It should be kept in LAMP-server environment.

**Comment by avaidyam** [comment] 2022-02-28 18:16
That's right, my apologies - @lukeoftheshire can you move these variables to `server`? Sorry and thanks!

**Comment by lukeoftheshire** [comment] 2022-02-28 18:33
Yes - I switched the env variables to be on server (and removed them from worker)

**Comment by Linoy339** [comment] 2022-03-01 12:19
@avaidyam . We have implemented the above mentioned :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/184]( https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/184)
Its working fine. We will let you know the status my tomorrow

**Comment by Linoy339** [comment] 2022-03-03 03:52
@avaidyam . This is tested and working fine

**Comment by avaidyam** [comment] 2022-03-03 10:30
I'll close the issue for now, but @jeydude please see if the staging version (`:latest`) works well for you now! Thanks.

**Closed** 2022-03-03 10:30 UTC
Labels: bug, 2day, backend, priority MEDIUM

**Comment by jeydude** [comment] 2022-03-04 23:01
@avaidyam, Thanks for the update. 

I have added ```CACHE_FLUSH_ALL: "true"`` to LAMP server stack environment with ```latest``` image. I will test it during the weekend and let you know the status soon.
