### ISSUE TITLE
Survey Screen and Voice Recording Freezing 

### ISSUE THREAD

**Issue by akmeyer3** [BIDMCDigitalPsychiatry/LAMP-platform#522] opened 2022-02-17 16:26 UTC
**Describe the bug**

After reordering questions in a survey on the dashboard, the user tries to test the new survey in the app, but the screen freezes after he starts the survey.  Same thing happens for voice recording feature. 

Error is not reproduced on researcher dashboard; new survey questions with changes committed are viewable and functional. However, error is reproduced when logged in as a user on the dashboard. 

**Expected behavior**
Surveys to show committed changes and to be functional (not frozen). 

**Screenshots**

![IMG_6424](https://user-images.githubusercontent.com/96262286/154523649-ceda3f3f-88b8-4bcd-916e-266bc2c46404.PNG)

![IMG_6423](https://user-images.githubusercontent.com/96262286/154523673-f32bd37c-1895-4346-bf52-37662a8f02fc.PNG)

![Screen Shot 2022-02-17 at 10 36 33 AM](https://user-images.githubusercontent.com/96262286/154523880-94fddcf2-3a2a-4cdf-8ec3-9d54c596f17c.png)

![Screen Shot 2022-02-17 at 10 36 45 AM](https://user-images.githubusercontent.com/96262286/154523929-52c80da9-71de-45f9-85c3-1facb852a50f.png)

![Screen Shot 2022-02-17 at 10 44 41 AM](https://user-images.githubusercontent.com/96262286/154523975-ee5497e7-249f-48a3-b835-2ff935157234.png)

![Screen Shot 2022-02-17 at 10 47 13 AM](https://user-images.githubusercontent.com/96262286/154524028-f227c6f9-4bc0-4bec-b2c4-06acad0a7b07.png)

**Desktop (please complete the following information):**
 - OS: mac OS Big Sur 11.6
 - Browser: Safari
 - Version: 15.1

**Smartphone (please complete the following information):**
 - Device: iPhone iOSXS 14.8. AND Samsung Galaxy S9 (reproducible on both)

**Additional context**

**Comment by ZCOEngineer** [comment] 2022-02-18 03:49
We shall check on this @avaidyam

**Comment by sarithapillai8** [comment] 2022-02-18 06:35
@avaidyam We have checked the issue in different devices and not able to reproduce this issue. Could you please provide credentials to check if this is related to any specific survey/user?

**Comment by avaidyam** [comment] 2022-02-18 16:27
@sarithapillai8 [There's a public forum thread with more information here.](https://mindlamp.discourse.group/t/survey-screen-not-loading/537/6) You will need to check on the production server. @akmeyer3 can provide credentials to a test user that experiences this issue.

**Comment by tlakhtak** [comment] 2022-02-18 20:31
Activities are not loading when users go to click on them from the feed or other pages for mindLAMP on two other servers (not api-lamp-digital). This seems to be happening for a majority of users hosted on these two servers.
![screenshot1](https://user-images.githubusercontent.com/82968538/154756958-a3f17dfe-1925-4d29-8cf7-135e350e79c2.jpeg)

https://user-images.githubusercontent.com/82968538/154756967-b2e5328c-6645-4653-888b-d873419f5a0d.mp4

**Comment by avaidyam** [comment] 2022-02-19 03:09
@sarithapillai8 I thought we had discussed that if the server didn't support this, there would be a fallback URL to the old method? What happened to that?

**Comment by sarithapillai8** [comment] 2022-02-19 03:23
@avaidyam Yes But there is checking that if this is available with 

` let activitySpec = await LAMP.ActivitySpec.view(activity.spec)`

This API call is making issues. There is no executable data , then old method will be executed. Do you prefer any other change?

**Comment by avaidyam** [comment] 2022-02-19 03:36
> This API call is making issues. 

So if this API call fails, what happens?

**Comment by sarithapillai8** [comment] 2022-02-19 03:43
@avaidyam 
Not related to this issue. But FYI I am having issues with my build. There is a build issue something related with jsPdf, which I commented here : (https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/506#issuecomment-1041469440). When I tried to solve it, my local build is not working. So it will take sometime to fix that. Only after fixing that I can check this. I tried to remove jspdf for temporary fix, but it is showing showing issues with other unrelated packages.

**Comment by sarithapillai8** [comment] 2022-02-19 06:14
@avaidyam 
Exception handling added and fix updated in dashboard-staging.
//cc @michaelmenon @ZCOEngineer

**Comment by dcurrey88** [comment] 2022-04-14 17:37
The issue with re-ordering questions appears to be fixed on the dashboard. However, when I tried to create a voice recording activity (on the staging dashboard) I get an error.

<img width="1044" alt="Screen Shot 2022-04-14 at 1 35 30 PM" src="https://user-images.githubusercontent.com/21200061/163443243-e3f52636-8207-4a95-a426-96911858ce50.png">

**Comment by sarithapillai8** [comment] 2022-04-18 04:41
@dcurrey88 @avaidyam This is fixed in dashboard-staging as part of #606 .

**Comment by dcurrey88** [comment] 2022-04-19 12:17
This appears to be working in the staging dashboard now.

**Closed by dcurrey88** 2022-04-19 12:17 UTC
Labels: bug, 1day, frontend, urgent, priority HIGH, QA testing
