### ISSUE TITLE
Feature request: MANY

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#214] opened 2021-04-21 19:37 UTC
> Our team would like to reintroduce some features that were available on mindLAMP 1 that were not kept on mindLAMP 2. It would be very ideal to have a practice trial option under each cognitive test exactly the same as to what was available on mindLAMP 1. Aditya showed us how to essentially make our own activity that would be the same as the practice trial, however this makes the main screen very messy and adds several additional activities on this assess page. Additionally, when clicking on any of the cognitive tests, they no longer show the descriptions we wrote out and added on the dashboard website. It seems that recently all the descriptions have been removed? This is not very user friendly as our studies have samples with serious mental health disorders such as schizophrenia and major depression and it is very common for these participants to forget the task and need a refresher on the instructions before they begin. Please bring this back. Lastly, when clicking on each cognitive test, it shows the code of the activity (i.e., (jewels_a), (jewels_b)). This makes the app look underdeveloped and seems unnecessary to be shown to participants. It would be much more user friendly if when you click on the cognitive test, it shows the instructions and allows the user to click on the practice trial or begin the real test. These features are essential for our study and it is very disappointing to see that they have been removed.

**Comment by avaidyam** [comment] 2021-05-21 17:07
Duplicate of #76, #165, and #170.

**Closed by avaidyam** 2021-05-21 17:07 UTC
Labels: bug, duplicate, feature, frontend
