### ISSUE TITLE
Cannot delete survey responses from clinician view

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#216] opened 2021-04-21 19:43 UTC
> Cannot delete survey responses from clinician view

**Comment by avaidyam** [comment] 2021-05-21 17:11
Duplicate of #148 (the delete button was removed from the Prevent tab due to a bug but should be restored by this linked issue).

**Closed by avaidyam** 2021-05-21 17:11 UTC
Labels: bug, duplicate, frontend
