### ISSUE TITLE
"Not at All" Survey Response is not showing up for Q10 on the App, but it does show up on the web version

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#200] opened 2021-04-21 19:10 UTC
> I wanted to report an error that I noticed with the mindlamp website on 
> the chrome app on my phone and on my computer. For question 10, I cannot
>  choose the "Not at all" option for the question, but I am able to 
> select the same option on the website. I noticed today because I decided
>  to do the daily service on my computer just for today. Until now, I 
> chose the "several times" option because there wasn't a "Not at all" 
> option, so that might be an error in my results. 
> 
> I have attached screenshots for clarification."
![image](https://user-images.githubusercontent.com/82968538/115607912-92c28780-a2b3-11eb-847f-129fd49f3551.png)
![image](https://user-images.githubusercontent.com/82968538/115607920-96560e80-a2b3-11eb-859b-4d8da7001a92.png)
![image](https://user-images.githubusercontent.com/82968538/115607936-9bb35900-a2b3-11eb-9992-9ff73005e2ce.png)

**Comment by avaidyam** [comment] 2021-05-21 15:58
Duplicate of #98!

**Closed by avaidyam** 2021-05-21 15:58 UTC
