### ISSUE TITLE
Can't click on data point in Prevent graph to expand for more detail  

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#196] opened 2021-04-21 19:04 UTC
> when i am viewing the graph of scores over time for a particular survey type (like anxiety), i can no longer click on a data point to expand that survey to see the questions/responses

**Comment by avaidyam** [comment] 2021-05-21 15:52
Duplicate of #148! (This feature was removed from the Prevent tab due to bugs with it.)

**Closed by avaidyam** 2021-05-21 15:52 UTC
Labels: bug, duplicate, frontend
