### ISSUE TITLE
Cannot create surveys

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#254] opened 2021-05-18 15:08 UTC
> When creating new survey, error comes up and work is unsaved.
![image](https://user-images.githubusercontent.com/82968538/118676341-535f5c00-b7c9-11eb-9f64-61cf46d7e292.png)

**Comment by avaidyam** [comment] 2021-05-21 17:39
Duplicate of #168.

**Closed by avaidyam** 2021-05-21 17:39 UTC
