### ISSUE TITLE
Surveys scheduled before daylight savings time are not accounting for time change

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#180] opened 2021-04-21 18:23 UTC
> Surveys that were scheduled for 9 PM before daylight savings now are being sent at 10 PM. They are still appearing as scheduled for 9 PM in the activity schedule dashboard.

**Comment by avaidyam** [comment] 2021-05-21 15:38
Duplicate of #97!

**Closed by avaidyam** 2021-05-21 15:38 UTC
