### ISSUE TITLE
LAMP Analytics logs time spent on page even by researcher

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#506] opened 2022-02-08 20:38 UTC
The `lamp.analytics` sensor logs time spent on page even when a participant is being accessed by admin, or presumably researcher, which it probably should not.

For example, see these events, all logged while I accessed a sample participant's page from browser with Admin credentials: 
```
{'timestamp': 1644351983836,
   'sensor': 'lamp.analytics',
   'data': {'type': 'open_page', 'page': 'learn', 'duration': 30798}},
  {'timestamp': 1644351952902,
   'sensor': 'lamp.analytics',
   'data': {'type': 'open_page', 'page': 'assess', 'duration': 2885}},
  {'timestamp': 1644351949889,
   'sensor': 'lamp.analytics',
   'data': {'type': 'open_page', 'page': 'manage', 'duration': 1301495169}},
  {'timestamp': 1643050454545,
   'sensor': 'lamp.analytics',
   'data': {'type': 'open_page', 'page': 'assess', 'duration': 8945}}
```

If these events are also logged when an Admin user is viewing the page, these events become less useful for the purpose of determining how much time is being spent in LAMP by a user.

(As a side note, the bug where the first duration in a chain of lamp.analytics events is set to the current unix timestamp is still present.)

**Comment by sarithapillai8** [comment] 2022-02-09 07:27
@avaidyam 
Please clarify on the duration value saved for open_page analytics.  It is implemented like last tab accessed time - current time. This is the expected behavior, right?

>(As a side note, the bug where the first duration in a chain of lamp.analytics events is set to the current unix timestamp is still present.)

For this, after login when the initial tab(assess) is shown, there will be a small millisecond duration, which will be saved for this. - eg: {type: 'open_page', page: 'assess', duration: 97}
When next tab(say "Learn") will be accessed, duration will be calculated by (current time - the time saved when assess tab(previous tab) accessed)

**Comment by lukeoftheshire** [comment] 2022-02-09 13:32
Hi @sarithapillai8 ,

> last tab accessed time - current time

That is the way that it should be implemented, yes. However, as you can see from the third event above where duration is `1301495169` it seems like (certainly on the browser at least) the first time a page is accessed the `last tab accessed time` may be being set to 0 - so when the user navigates to the next page the value stored for duration is instead the current unix timestamp.

Hope this helps - let me know if I can clarify any more about this or the other issue.

**Comment by sarithapillai8** [comment] 2022-02-09 14:54
@avaidyam
This is updated in dashboard-staging.

**Comment by lukeoftheshire** [comment] 2022-02-09 15:49
Hi @sarithapillai8, @avaidyam 

First, thank you for the speed with which you responded to this issue. I apologize for the inconvenience caused by me re-opening this issue but I want to make sure we are all on the same page and I am QA-checking this appropriately.

I think there were two initial issues we were aiming to address here:

1. `lamp.analytics` sensor events can incorrectly log what is effectively a unix timestamp for the `duration` of the first page accessed by a user. This may be because when `page_closed_timestamp`-`page_opened_timestamp` is calculated, the `page opened timestamp` is incorrectly initialized to 0.
2. `lamp.analytics` sensorevents can be logged even if the credentials accessing a Participant page belong to a Admin/Researcher, not the participant themselves (@avaidyam I am assuming this is a bug).

After the issue was closed, I took the following steps:

1. In portainer, updated the lamp-dashboard staging service and pulled the latest image (confirming that the latest release was out and the build has finished).
2. Using an incognito window, went to dashboard-staging.lamp.com and logged in with admin credentials.
3. Navigated to the participant view for `U7100184772` (one of my test users)
4. Navigated from `portal`(Prevent) (the initially opened tab) to `manage` and then later back to `portal`
5. Checked the requests made by the dashboard to see what `lamp.analytics` sensor events were logged.

The first event payload:
![Screen Shot 2022-02-09 at 10 26 27 AM](https://user-images.githubusercontent.com/34659264/153234686-be604f21-6ddb-4a9f-8462-954e39cdada4.png)
As you can see, it looks like issue 1 is still happening - `duration` is exactly the same as `timestamp`

The second event payload:
![Screen Shot 2022-02-09 at 10 26 47 AM](https://user-images.githubusercontent.com/34659264/153235149-ff1e1b15-145c-4296-87f6-5e371c0a261f.png)

By happy coincidence, the Portal/Prevent page queries recent sensor events, so I happen to have the log of recent sensor events here:
![Screen Shot 2022-02-09 at 10 27 04 AM](https://user-images.githubusercontent.com/34659264/153235438-d980aa7f-2ce0-4d6c-95ad-289db6ed65eb.png)
As you can see, both events are being stored faithfully.

It seems like the issue may not be fully resolved or I made an error somewhere while checking. If either of you have thoughts on this, I would greatly appreciate it.
<hr>

There is an additional issue I noticed while checking this. As I described above, the "flow" I took through lamp to get these sensor events was:

```
PORTAL/PREVENT -> MANAGE -> PORTAL/PREVENT
```

However, only two analytics events have been logged and they suggest that my order was instead
```
MANAGE -> PORTAL
```

It seems that the `lamp.analytics` event consists of 
```
{ page: #The navigated *to* page, not the page left
duration: #The time spent on the page *LEFT*,
type: 'open_page'
}
```
I am not sure if this is a bug per se but this implementation (if I am correct) is a bit confusing and a first-time user seeing this data point would probably assume, speaking from experience, that the `duration` value reflected the time spent on the `page` page, so to speak -- which does not appear to be the case. @avaidyam, should we consider changing this?

**Comment by sarithapillai8** [comment] 2022-02-09 16:37
@lukeoftheshire 
The fix is updated in dashboard-staging.

**Comment by lukeoftheshire** [comment] 2022-02-09 18:56
Hi @sarithapillai8 

Great, thanks! I took a quick look and both issue 1 and 2 look to be fixed - the duration is normal and no events are logged from Admin users. I appreciate very much your quick response to this.

@avaidyam should we split the sensorevent format topic I briefly outlined into another issue?

**Comment by avaidyam** [comment] 2022-02-10 17:03
> @avaidyam should we split the sensorevent format topic I briefly outlined into another issue?

Yes! Good call highlighting this. Please open it as a new issue and link it here so the issues are connected.

**Comment by sarithapillai8** [comment] 2022-02-11 12:27
@avaidyam 
> is there a way to know when the the dashboard was closed from the browser?

onunload, onbeforeunload events are there. But we need to check in detail whether it is supported on all browsers.

**Comment by avaidyam** [comment] 2022-02-11 12:43
There are a few choices to use, like [`Navigator.sendBeacon()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) (preferred), but also [`visibilitychange`](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) events that we should also track.

**Comment by sarithapillai8** [comment] 2022-02-11 13:01
@avaidyam _visibilitychange_ event triggers the hidden condition even when we move to any other tab on the browser , not on closing the tab. The actual requirement is to identify the state of tab close, right? _onbeforeunload_ event works on closing the tab after any kind of user interaction in the page.

**Comment by avaidyam** [comment] 2022-02-11 13:08
[Please read the documentation linked above.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) 

> In the past, many websites have used the unload or beforeunload events to send analytics at the end of a session. However, this is extremely unreliable. In many situations, especially on mobile, the browser will not fire the unload, beforeunload, or pagehide events. For example, these events will not fire in the following situation:
> 
> 1. The user loads the page and interacts with it.
> 1. When they are finished, they switch to a different app, instead of closing the tab.
> 1. Later, they close the browser app using the phone's app manager.
> 
> Additionally, the unload event is incompatible with the back/forward cache (bfcache) implemented in modern browsers. Some browsers, such as Firefox, handle this incompatibility by excluding pages from the bfcache if they contain unload handlers, thus hurting performance. Others, such as Safari and Chrome on Android, handle it by not firing the unload event when the user navigates to another page in the same tab.

```js
document.addEventListener('visibilitychange', function logData() {
  if (document.visibilityState === 'hidden') {
    navigator.sendBeacon('/log', analyticsData);
    // You can use the LAMP.SensorEvent.create() method here instead. 
  }
});
```

**Comment by avaidyam** [comment] 2022-02-11 13:55
@sarithapillai8 Yes, this is expected behavior. (Alerts will not display until the tab returns. Use a console log instead.)

This behavior is exactly what we want because this is the user flow:
1. Patient logs in to home screen. 
    - A `login` event is fired **AND** 
    - An `open_page` event is fired with `"learn"` (or whatever tab they start off on). 
2. Patient goes to Manage. 
    - An `open_page` event is fired with `"manage"`. 
3. Patient does a Breathe activity. 
    - An `open_page` event is fired with `"activity"` or the Activity ID. (This is optional, not implemented, but would be nice to have. //cc @lukeoftheshire) 
    - The Breathe activity generates an `ActivityEvent` (the `timestamp` of the `open_page` event if implemented must be the same as the one of this `ActivityEvent`). 
4. Patient switches tabs to do something else. 
    - An `open_page` event is fired with `null` to indicate the page is hidden. 
5. Patient returns to LAMP (still on the Manage tab). 
    - An `open_page` event is fired with `"manage"`. 
6. Patient navigates to Learn.
    - An `open_page` event is fired with `"learn"`. 
7. Patient reads a Tip. 
    - An `open_page` event is fired with `"activity"` or the Activity ID, optionally. 
    - The Tip generates an `ActivityEvent` (same `timestamp` requirement as above). 
8. Patient logs out or closes tab. 
    - An `open_page` event is fired with `null` (to indicate the end of a session). 
    - If the patient has logged out, a `logout` event is fired.

**Comment by avaidyam** [comment] 2022-02-11 14:29
Yes, no duration field. Instead, implement the `login`/`logout` events as above, and the `open_page` events with `activity` and `null`.

**Comment by sarithapillai8** [comment] 2022-02-15 10:44
@avaidyam  
>A login event is fired AND If the patient has logged out, a logout event is fired.

Does this mean to have sensor events for these events?

Note : When a participant logged in, we are now having a sensor event like : LAMP.SensorEvent.create(res.identity.id, {
            timestamp: Date.now(),
            sensor: "lamp.analytics",
            data: {
              device_type: "Dashboard",
              user_agent: `LAMP-dashboard/${process.env.REACT_APP_GIT_SHA} ${window.navigator.userAgent}`,
            },
          }
Do we need to have any other SensorEvent for login with this change? If needed, let me know the format.
Also for the logout event, do we just need to add open_page with null value or any separate logout after this null data?.

**Comment by avaidyam** [comment] 2022-02-15 14:00
> Does this mean to have sensor events for these events? If needed, let me know the format.

Yes - the logout even should have the **same format** as the login event. They're both `lamp.analytics` events with `type = login` or `type = logout`. The other parameters should be the same as they are right now for the login event. 

> For the logout event, do we just need to add open_page with null value or any separate logout after this null data?.

The `open_page` with `null` value event is **separate** from the logout event. The **logout event occurs ONLY when the user presses the logout button manually**. 

> In this case, can we use the following format of data :

Yes, this makes sense. (Also, please use the markdown code block formatting!) //cc @lukeoftheshire 

> When a participant logged in, we are now having a sensor event like : 

Yes, this is the correct format. //cc @lukeoftheshire Anything else we need parameter-wise?

**Comment by sarithapillai8** [comment] 2022-02-15 15:05
@avaidyam @lukeoftheshire 

>They're both lamp.analytics events with type = login or type = logout

Do we need to have another analytics other than than below for login? 
           
data: {
              device_type: "Dashboard",
              user_agent: `LAMP-dashboard/${process.env.REACT_APP_GIT_SHA} ${window.navigator.userAgent}`,
            },


Could you please specify the correct format for logout as you said login and logout format should be same. ?

**Comment by lukeoftheshire** [comment] 2022-02-15 15:28
@avaidyam @sarithapillai8 Right now, I can't think of anything we might need to capture at log-in that we don't already capture somewhere else.

**Comment by avaidyam** [comment] 2022-02-15 15:38
> I assume 'activity' will be null when the user navigates to the page 

Agreed - this makes sense to do. Otherwise I think it all makes sense to implement now, @sarithapillai8.

**Comment by sarithapillai8** [comment] 2022-02-15 16:27
@avaidyam @lukeoftheshire 
>That data format looks good to me - I assume 'activity' will be null when the user navigates to the page (i.e., is not doing an activity).

I was planning not to have activity parameter if it is saving for tabs. Do you want to save it as null in all other cases ? 

I am still not clear with logout data format. For login, I assume there is no change required.

**Comment by avaidyam** [comment] 2022-02-15 20:29
>  Do you want to save it as null in all other cases ?

Yes. Parameters should never be missing in some cases but provided in others. If this practice is happening in other places, please let me know so we can track it as a new issue. 

> I am still not clear with logout data format. 

The same data format as `login`, but with the `type` parameter set to `logout` instead. 

> For login, I assume there is no change required.

Are you using a `type` parameter set to `login`? If not, please add that. //cc @lukeoftheshire Can you share a few sample analytics events so we can confirm there's a standard data format being used?

**Comment by sarithapillai8** [comment] 2022-02-16 06:46
@avaidyam 
 Following is the SensorEvent format that is currently using for Login : 
       LAMP.SensorEvent.create(res.identity.id, {
            timestamp: Date.now(),
            sensor: "lamp.analytics",
            data: {
              device_type: "Dashboard",
              user_agent: `LAMP-dashboard/${process.env.REACT_APP_GIT_SHA} ${window.navigator.userAgent}`,
            },
        }
There is no type parameter. I assume you are expecting something other for login and logout events.

**Comment by lukeoftheshire** [comment] 2022-02-17 13:22
@sarithapillai8 We're not sure what exactly might be causing this issue so it may just be an issue with dependencies. Because of that it's tough for us to recommend exact steps to fix this.

It looks like the only module we use that requires `canvg` is `jsPDF` but it doesn't require a version past `3.0.6` so you can maybe try reverting to an earlier version and see if that helps.

**Comment by sarithapillai8** [comment] 2022-02-21 05:36
@avaidyam 
Waiting for clarification about login/logout event. (https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/506#issuecomment-1041168809)

**Comment by avaidyam** [comment] 2022-02-21 13:33
@sarithapillai8 I already provided the answer in the comment before yours:

> Are you using a `type` parameter set to `login`? **If not, please add that.**

**Comment by avaidyam** [comment] 2022-02-21 13:37
Yes, like so: 

```js
  {
       timestamp: Date.now(),
       sensor: "lamp.analytics",
       data: {
         type: "login", // or "logout"
         device_type: "Dashboard",
         user_agent: `LAMP-dashboard/${process.env.REACT_APP_GIT_SHA} ${window.navigator.userAgent}`,
       },
   }
```

**Comment by avaidyam** [comment] 2022-02-23 16:44
@sarithapillai8 It seems to be correct from what I can see in browser-side network calls. @lukeoftheshire Can you also take a look and see if it appears to match the spec we described when using Cortex or the python API client? Thanks!

**Comment by lukeoftheshire** [comment] 2022-02-23 17:28
Hi @avaidyam, @sarithapillai8 

Here are the steps I took to QA test this:

1. Open an incognito window, navigate to dashboard-staging.lamp.digital
2. Login in using a newly created dummy user while checking network requests
3. Logout

After completing this, I used the python API client to pull the last set of analytics events, and got this:
```
{'timestamp': 1645636523823,
  'sensor': 'lamp.analytics',
  'data': {'type': 'open_page', 'page': 'assess', 'activity': None}},
 {'timestamp': 1645636523499,
  'sensor': 'lamp.analytics',
  'data': {'type': 'login',
   'device_type': 'Dashboard',
   'user_agent': 'LAMP-dashboard/dev Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'}},
```

As you can see, the login event appears to be correctly formatted (the new `type` key is present and the `user_agent` string is nice and descriptive)

However, there is no logout event. Looking at the network requests, one is correctly _fired_  (this is taken from the network tab, the formatting is correct):
```
data: {type: "logout", device_type: "Dashboard",…}
device_type: "Dashboard"
type: "logout"
user_agent: "LAMP-dashboard/dev Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"
sensor: "lamp.analytics"
timestamp: 1645636870312
```

However, it is not *received* and 
```
{
  "error": "403.security-context-out-of-scope"
}
``` 
is returned

I suspect that the user credentials are being removed before the event is fired, leading to this security error.

Additionally, I notice that when I log out, the URL does NOT change
![Screen Shot 2022-02-23 at 12 24 48 PM](https://user-images.githubusercontent.com/34659264/155373087-c65a398e-0055-46b9-84bf-ffd434151996.png)

I don't know if this is worthy of a separate issue but I think this should be fixed - I would say when a user logs out we should change the URL back to (in this case) `dashboard-staging.lamp.digital`. Related to this, another event is fired shortly after logging out:
```
activity: null
page: null
type: "open_page"
sensor: "lamp.analytics"
timestamp: 1645636870309
```
This is probably unnecessary.

Please let me know if I can offer any clarification about any of this.

**Comment by avaidyam** [comment] 2022-02-23 18:29
> I don't know if this is worthy of a separate issue but I think this should be fixed - I would say when a user logs out we should change the URL back to (in this case) dashboard-staging.lamp.digital.

@sarithapillai8 Yes, if the login screen is being displayed, it means the URL **MUST BE** `/login` or something similar. Why is the UI still not matched correctly with URL routes? 

 > Related to this, another event is fired shortly after logging out [...] This is probably unnecessary.

This event is correct and necessary; `open_page == null` is expected (see my detailed spec above):
> An open_page event is fired with null to indicate the page is hidden.

This event should be fired **in addition** to login/logout events. 

> I suspect that the user credentials are being removed before the event is fired, leading to this security error.

@sarithapillai8 The logout event should be submitted and **awaited on** when the user **presses the logout button in the logout dialog**. Once the server responds and the awaited promise is resolved, **then the credential should be removed and the UI redirected to `/login`**.

**Comment by sarithapillai8** [comment] 2022-02-24 05:07
@lukeoftheshire @avaidyam 
The issues fixed and updated. Could you please have a look?

**Comment by lukeoftheshire** [comment] 2022-02-25 16:47
Looking on dashboard staging, the URL now correctly redirects to dashboard.lamp.digital/.

However, it seems that the credential issue might not have been fixed - I can still see the logout event being rejected with a 403 error.

**Comment by sarithapillai8** [comment] 2022-02-26 02:30
@lukeoftheshire 
Ok let me try to reproduce, I could see correct events from my side.

**Comment by sarithapillai8** [comment] 2022-03-03 05:23
@lukeoftheshire 
Could you please check ? The updates are ready in dashboard-staging.

**Comment by avaidyam** [comment] 2022-03-03 10:33
I'll close this issue for now as it's implemented but @lukeoftheshire feel free to reopen if it's not implemented properly/completely.

**Closed by avaidyam** 2022-03-03 10:33 UTC
Labels: bug, 3day, frontend, priority HIGH, QA testing

**Comment by sarithapillai8** [comment] 2022-03-04 15:42
>I think as part of this change (or another?) some console.logs to note the result of the queries were added to the dashboard. But, since the result of queries is almost always {}, the end effect is just to have some empty objects show up in the console. I think we could consider removing these (unless they serve another purpose).

I have removed almost of these. I can check and remove if anything pending. Thanks.

**Comment by avaidyam** [comment] 2022-03-04 16:47
> I think this implementation is (almost) perfect and may not require any changes.

🎉 ✅ 

> it looks like the timestamps for Activity access events reflect the time of activity submission (we are currently deciding how to resolve this)

**All timestamps anywhere across anything within the LAMP Platform should ALWAYS denote the start of the user interaction,** not start of submission (which is kind of useless to collect as data?). Let's track this in #542 though. 

> I think we could consider removing these

Agreed. @sarithapillai8, thanks for going through to remove any remaining logs!

**Comment by dcurrey88** [comment] 2022-04-12 18:13
This appears to be working in staging.
