### ISSUE TITLE
TypeError: null is not an object when accessing surveys

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#422] opened 2021-11-01 13:57 UTC
When doing different survey activities, two users got these error messages. Their IDs were U1289352228 and U6596525792.
![bug 2](https://user-images.githubusercontent.com/82968538/139683133-047aebbc-48b9-4757-8d0d-867504edffc5.png)
![bug](https://user-images.githubusercontent.com/82968538/139683140-d7c551cb-54b6-49bb-9452-42325b55de84.jpg)

**Comment by SuruPa00** [comment] 2021-11-01 15:44
duplicate of #421

**Closed by SuruPa00** 2021-11-01 15:44 UTC
Labels: bug
