### ISSUE TITLE
Activity description does not show up on the app for the user

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#188] opened 2021-04-21 18:42 UTC
> So, when I add the Jewels activity to a study, there is an option to add a description which is great because I thinks Jewels B especially can be so confusing. However, the description doesn't show up on the app where it should (or anywhere)
![image](https://user-images.githubusercontent.com/82968538/115604813-cef3e900-a2af-11eb-8bb6-b2f798c98038.png)
![image](https://user-images.githubusercontent.com/82968538/115604830-d3200680-a2af-11eb-825c-aeb19c0bb33c.png)

**Comment by avaidyam** [comment] 2021-05-21 15:43
Duplicate of #170!

**Closed by avaidyam** 2021-05-21 15:43 UTC
Labels: bug, duplicate, frontend
